### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1021]
```
java.lang.RuntimeException: Exception in Application start method
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:92)
    at com.faforever.client.FafClientApplication.start(FafClientApplication.java:77)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
    at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
    at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
    ... 1 more
```

**Comment by 1-alex98** [comment]
applicationContext.getBean(UiService.class) -> applicationContext is NULL because it is set asynchronously

That is what I expect. Sady I can not reproduce it in Intelij

**Comment by 1-alex98** [comment]
I think the issue is the following, in Main class. The init method is called on none main tread, so we use platform.runlater. The start method is called afterwards but on main thread but with a different method to schedule it. So even tho platform.runlater is called first the start method will run before it. So what I do is just call Platform.runLater in start method because it grantees that runnables are called in the order they are passed to Planform.runLater ... ;)

**Comment by 1-alex98** [comment]
Ok old theory can not be true but  the fix for that might also work in my new theory. :D

**Comment by 1-alex98** [comment]
So what I think now is that in the Spring code PlatormImpl.runAndWait is called for start which will simply run the runnable if already on the main thread which would mean the start method gets called before init's Platform.runLater ... So I suggest we use PlatformImpl.runAndWait in the init method as well. When debugging it is not run on the application thread however it might be somewhere else
