### ISSUE TITLE
crash while in game

### ISSUE THREAD

**Issue by EmielWitteman** [FAForever/downlords-faf-client#1072]
Downlords client had crashed on me twice while playing ladder, this time I saved the logs, but I fear the crash reason is not logged. There was no widows error, the client just disapeared.
Any other logs which could provide clues?

game.log
```
debug: Current gametime: 00:03:30
debug: Loading module '\000/units/uaa0103/uaa0103_script.lua\000'
debug: Loading module '\000/effects/entities/debrismisc04/debrismisc04_script.lua\000'
debug: Loading module '\000/units/uea0101/uea0101_script.lua\000'
debug: Loading module '\000/units/ual0103/ual0103_script.lua\000'
debug: Current gametime: 00:04:00
warning: Error running OnRelease script in <deleted object>: ...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): Game object has been destroyed
         stack traceback:
         	[C]: in function `Play'
         	...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): in function <...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua:78>
debug: Loading module '\000/units/uea0103/uea0103_script.lua\000'
debug: Loading module '\000/units/uaa0101/uaa0101_script.lua\000'
debug: Loading module '\000/units/ueb2101/ueb2101_script.lua\000'
debug: Loading module '\000/units/uab5101/uab5101_script.lua\000'
debug: Loading module '\000/projectiles/adfdisruptor01/adfdisruptor01_script.lua\000'
debug: Loading module '\000/projectiles/laserbotterran01/laserbotterran01_script.lua\000'
info: CNetTCPBuf::Read(): recv() failed: WSAECONNRESET
warning: GPGNET: Ignoring unknown gpg.net command "ConnectionShutdown".
warning: Connection dialogue opening due to disconnection by players:
info: Poultrygeist
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
debug: Loading module '\000/lua/ui/dialogs/keybindings.lua\000'
debug: Loading module '\000/lua/keymap/properkeynames.lua\000'
debug: Loading module '\000/lua/keymap/keynames.lua\000'
debug: Loading module '\000/lua/keymap/keycategories.lua\000'
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
info: Sending game result: 2 defeat -10
info: CNetTCPBuf::Flush(): send() failed: WSAECONNRESET
debug: Loading module '\000/lua/ui/game/gameresult.lua\000'
info: Hooked /lua/ui/game/gameresult.lua with /mods/supremescoreboard/hook/lua/ui/game/gameresult.lua
info: SSB >>> TRACE GameResults: [2] = defeat -10, army = Poultrygeist
info: SSB >>> TRACE GameResults: Poultrygeist has been defeated by Poultrygeist
info: SSB >>> TRACE AnnounceDeath Poultrygeist  has been defeated by  Poultrygeist
debug: Loading module '\000/lua/ui/dialogs/score.lua\000'
debug: Loading module '\000/lua/ui/dialogs/hotstats.lua\000'
debug: Loading module '\000/lua/ui/dialogs/myeffecthelpers.lua\000'
info: SSB >>> TRACE OnBeat() player has died: Poultrygeist
info: GPGNET: setting nat handler to 0x00000000
info: Run time: 0h06m56s
```

downlords log:
```
2018-12-16 09:18:17.416  INFO 9984 --- [Thread-233] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [C:\ProgramData\FAForever\bin\ForgedAlliance.exe, /init, init.lua, /nobugreport, /uef, /log, C:\ProgramData\FAForever\logs\game.log, /gpgnet, 127.0.0.1:52276, /mean, 1478.0499, /deviation, 66.96739, /savereplay, gpgnet://127.0.0.1:52277/8975687/Mielus.SCFAreplay, /country, NL, /clan, HEL, /numgames, 2076, /team, 1, /players, 2] in directory: C:\ProgramData\FAForever\bin
2018-12-16 09:18:17.857  INFO 9984 --- [pool-3-thread-14] c.f.c.patch.GameBinariesUpdateTaskImpl   : Updating binaries to 3701
2018-12-16 09:18:17.874  WARN 9984 --- [JavaFX Application Thread] com.faforever.client.task.TaskService    : Task failed

com.github.nocatch.NoCatchException: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\bin\BugSplat.dll
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82) ~[nocatch-1.1.jar:na]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.lambda$copyGameFilesToFafBinDirectory$4(GameBinariesUpdateTaskImpl.java:130) ~[downlords-faf-client-0.9.2-beta.jar:0.9.2-beta]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.copyGameFilesToFafBinDirectory(GameBinariesUpdateTaskImpl.java:125) ~[downlords-faf-client-0.9.2-beta.jar:0.9.2-beta]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.call(GameBinariesUpdateTaskImpl.java:86) ~[downlords-faf-client-0.9.2-beta.jar:0.9.2-beta]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.call(GameBinariesUpdateTaskImpl.java:39) ~[downlords-faf-client-0.9.2-beta.jar:0.9.2-beta]
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[javafx.graphics:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\bin\BugSplat.dll
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileCopy.copy(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source) ~[na:na]
	at java.base/java.nio.file.Files.copy(Unknown Source) ~[na:na]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.lambda$copyGameFilesToFafBinDirectory$2(GameBinariesUpdateTaskImpl.java:130) ~[downlords-faf-client-0.9.2-beta.jar:0.9.2-beta]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100) ~[nocatch-1.1.jar:na]
	... 20 common frames omitted

2018-12-16 09:18:18.726 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'SparraNova' left channel: #aeolus
2018-12-16 09:18:29.599 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=gaypistachio, login=248159, hostname=5B60CBDF.878B4CB8.3B021B59.IP), userId=efe3ecef-187d-42c2-a488-b55bd6a1f39e, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:18:45.151 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Tele4erep, login=241791, hostname=EB3CCCAE.70646B5E.970B3596.IP), userId=e964ee02-3ec3-4508-be0b-c78025f7cfdf, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:18:49.774 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=BULAVA, login=250457, hostname=8C7252B1.63248B69.5F3A01C8.IP), userId=8a1ce774-82d5-4194-a534-34c6058b5836, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:18:51.666 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Legolash2o' left channel: #aeolus
2018-12-16 09:19:22.924 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=klas1, login=193500, hostname=32D22A80.59738494.AE376135.IP), userId=eb7b53b0-fcbe-435f-b104-46c0c3236ca0, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:19:24.468 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'StefanD' left channel: #aeolus
2018-12-16 09:19:24.951 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'frodon' left channel: #aeolus
2018-12-16 09:19:27.893 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Rabbit, login=18056, hostname=Clk-9F1FF118.washdc.fios.verizon.net), userId=f2e5f64d-f470-45b2-a849-dabbbca5840b, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:19:41.648 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Kiron_' left channel: #aeolus
2018-12-16 09:19:47.243 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'GOZIZ' left channel: #aeolus
2018-12-16 09:19:48.416 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=bulmakow, login=240058, hostname=Clk-22D1FA34.ltk.com.ua), userId=423cf4d9-4531-4d50-ae09-2876f6c8cce4, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:19:50.689 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'VoDka447' left channel: #aeolus
2018-12-16 09:19:55.130 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=lluvanati, login=185590, hostname=Clk-81E35504.hsd1.or.comcast.net), userId=6282f233-ec8a-44c4-842b-0c6c5ba086ef, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:19:58.814 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Saske_Kaske' left channel: #aeolus
2018-12-16 09:19:59.170 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Kiron_, login=279450, hostname=45192C10.359995A.86E5A9B0.IP), userId=214260d5-3927-4e09-bec8-b5132ce1f55a, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:20:01.331 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=VoDka447, login=190612, hostname=251108A.881211B.4EE6D1F3.IP), userId=e42b3bc8-7671-4964-9b01-6028e770aa6a, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:20:05.152 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Mere9, login=14909, hostname=Clk-EE241650.jemnicka.nat.h17.cz), userId=3d7bbcaf-38da-44ad-a0a2-fa096a9b7c10, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:20:10.835 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Nathair' left channel: #aeolus
2018-12-16 09:20:12.307 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Nathair, login=281446, hostname=Clk-361F0D85.maine.res.rr.com), userId=66d6ca75-ecd9-40f2-bf42-bb21a1e7b05e, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:20:16.558 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Qui-Gon-Jin-Noob' left channel: #aeolus
2018-12-16 09:20:35.219 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=kirovreporting, login=128843, hostname=30A5E7B2.D4E5CDB6.C2CCE9E.IP), userId=20e315dd-3c39-49f1-8510-e2e2d5ee9aec, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:20:49.022 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Samaelll, login=244149, hostname=D2EBB2A6.1BFEB2C1.5BA02DFF.IP), userId=6d214815-a48e-40be-be3b-916341c71717, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:21:19.556 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Zimbo77, login=89158, hostname=8E62D6E7.375CFB92.EEF36D64.IP), userId=e4534fda-87a0-4244-8066-74934b97a895, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:21:43.402 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Tetrapod' left channel: #aeolus
2018-12-16 09:21:48.093 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'gherv' left channel: #aeolus
2018-12-16 09:21:51.911 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'KPAKEH' left channel: #aeolus
2018-12-16 09:22:03.390 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'TroubleDefender' left channel: #aeolus
2018-12-16 09:22:15.558 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=EskyONToast, login=238385, hostname=Clk-FE93DC2.bras1.adl4.internode.on.net), userId=76c344ca-06a7-426c-9eef-55b286356eee, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:22:20.502 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Neversleep' left channel: #aeolus
2018-12-16 09:22:30.900 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=sammyhale30, login=57447, hostname=69D9E4DE.EFF8FEB7.DF72DEFF.IP), userId=beddbf72-6e54-496e-9aa2-45555f158e04, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:22:32.843 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'sammyhale30' left channel: #aeolus
2018-12-16 09:22:35.045 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Neversleep, login=21607, hostname=817F5D37.A195E140.907E010A.IP), userId=3b87dbd5-b41a-480e-94d8-58d65fa08940, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:22:46.647 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=LAH, login=257801, hostname=Clk-CAC37A7C.hsi09.unitymediagroup.de), userId=0978e1fe-439a-40fd-a32d-09735c98faf8, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:00.114 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=FynnyBlinchik, login=212252, hostname=D5B21D41.72F20C77.7F3DF85D.IP), userId=c67d2dcd-5675-45e3-b4ec-c93788b1e265, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:04.274 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=zakadikplay, login=250671, hostname=7349089C.F3687331.CF2C2151.IP), userId=dfb66063-f2e6-4655-b9a8-db8b2d39e09a, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:09.408 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Clarku-San, login=281450, hostname=Clk-ABAF8FAD.sta.dodo.net.au), userId=b4b4f3e1-5343-40d3-b5a8-b7af048d88f1, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:15.553 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Samaelll' left channel: #aeolus
2018-12-16 09:23:22.978 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Samaelll, login=244149, hostname=D2EBB2A6.1BFEB2C1.5BA02DFF.IP), userId=042fdb28-b47a-4975-b997-b91e5562e2bb, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:26.155 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'Neversleep' left channel: #aeolus
2018-12-16 09:23:29.982 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=cryptowar, login=192339, hostname=2AEB851C.73DAC3F4.236ABD96.IP), userId=2193d2f3-2d66-479d-ac91-94640cc4fa51, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:35.412 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=BigBob, login=186230, hostname=Clk-8CD8C6D1.lv.lv.cox.net), userId=542bc70e-411e-4095-a86f-b45b2f04edb4, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:37.877 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=Neversleep, login=21607, hostname=817F5D37.A195E140.907E010A.IP), userId=67fed9a0-981e-4f6c-ad42-c3d355da292f, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:23:40.462 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'zipperawm' left channel: #aeolus
2018-12-16 09:23:59.444 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=SupaDupaSmert, login=279172, hostname=E8F570A6.1E7E8F6D.6E50E848.IP), userId=d02c6917-5ab9-41b6-a42c-afec472dbc8c, realName=, awayMessage=null, ircop=false, server=, hops=0)
2018-12-16 09:24:08.985 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'seconal' left channel: #aeolus
2018-12-16 09:24:09.172 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User 'LAH' left channel: #aeolus
2018-12-16 09:24:15.560 DEBUG 9984 --- [listenerPool0-thread47] c.f.client.chat.PircBotXChatService      : User joined channel: User(super=UserHostmask(extbanPrefix=null, nick=LAH, login=257801, hostname=Clk-CAC37A7C.hsi09.unitymediagroup.de), userId=b8399775-9a4a-44e4-a44d-fce251b7a4fd, realName=, awayMessage=null, ircop=false, server=, hops=0)
```

**Comment by 1-alex98** [comment]
First of all what does crash mean did it freeze or did it crash ?

**Comment by 1-alex98** [comment]
It froze right?

**Comment by 1-alex98** [comment]
If it should happen again pls have a look at the RAM usage of the client and tell us the number so we know if it is a memory leak.

**Comment by EmielWitteman** [comment]
the downlord client crashed so the game got in disconnect timer mode, there was no downlords-faf-client.exe running any more it just vanished from taskmgr, ForgedAlliance.exe was still running. 
I'll start monitoring the ram usage of the client.

**Comment by EmielWitteman** [comment]
memory usage increased:
<img width="465" alt="2018-12-16 21_18_13-task manager" src="https://user-images.githubusercontent.com/38175365/50058992-18cce180-0181-11e9-85ca-fe3a41e36b9f.png">

**Comment by 1-alex98** [comment]
Strange so it did not freeze

**Comment by 1-alex98** [comment]
Might be outofmemory exception

**Comment by 1-alex98** [comment]
Have u got v0.9.2?

**Comment by EmielWitteman** [comment]
v0.9.2-beta

**Comment by EmielWitteman** [comment]
v0.9.3-beta same problem, played 2 games, 30-40 mins or so

**Comment by Brutus5000** [comment]
Why is the client trying to touch a game DLL?
```com.github.nocatch.NoCatchException: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\bin\BugSplat.dll```
I guess this might be related, but I don't know why it is happening.

**Comment by germanicianus** [comment]
I think this is the important part of the error log:
```
com.github.nocatch.NoCatchException: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\bin\BugSplat.dll
[...]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.lambda$copyGameFilesToFafBinDirectory$4(GameBinariesUpdateTaskImpl.java:130) ~[downlords-faf-client-0.9.2-beta.jar:0.9.2-beta]
[...]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.copyGameFilesToFafBinDirectory(GameBinariesUpdateTaskImpl.java:125) ~[downlords-faf-client-0.9.2-beta.jar:0.9.2-beta]
```
My guess is the following:
Client tries to update FA's files while it's running -> OS denies write access -> client exception -> client crash.

**Comment by EmielWitteman** [comment]
I really hope a client update is never attempted while in the game!

**Comment by micheljung** [comment]
@germanicianus The log posted EmielWitteman says that ForgedAlliance.exe has been started 400ms before it tried to download updates. Something is wrong in the order, probably related to threading issues

**Comment by EmielWitteman** [comment]
I'm currently trying the script from issue https://github.com/FAForever/downlords-faf-client/issues/1080 
I'll report any crashes or success after I tried this for some time...

**Comment by EmielWitteman** [comment]
I have had no more crashes since I start with the script from issue #1080, so it seems to be a java related problem.

**Comment by EmielWitteman** [comment]
the downlords ice release client v10.0.4-beta crashed twice on me again, the ice adapter stayed online though and the game can be finished (unlike the post #1080 from tomaskir), I restarted the lobby while in game and both games got reported to the server. I did not use a special script to start the client. I did also have a crash with the older client and the special start script(after 19 feb). Although I think the script helps to make crashes less frequent. But I had little time to investigate the matter further

**Comment by 1-alex98** [comment]
@EmielWitteman I think your client runs out of RAM or memory

**Comment by 1-alex98** [comment]
Please have a look at the install directory of the client and look if you can find a file called  java_pid<something>.hprof

**Comment by 1-alex98** [comment]
To quickly fix this issue you can edit the downlords-faf-client.vmoptions to use more memory/RAM by editing the number Xmx512m to Xmx812m for example
Tho this will only delay the crash in most cases

**Comment by 1-alex98** [comment]
Forwarding the mentioned file will enable us to see what uses all the memory on your machine

**Comment by EmielWitteman** [comment]
Thanks for the feedback. I just installed v.010.5-beta, don't see any file named java_pid.hprof, did change the downlords-faf-client.vmoptions file to Xmx4096m. I have 32Gb physical memory, so no worries there. Let's see if this will prevent crashes

**Comment by 1-alex98** [comment]
Ehm yes if you reinstall the files are delted

**Comment by 1-alex98** [comment]
I mean update==reinstall

**Comment by EmielWitteman** [comment]
even with Xmx4096m still a crash

**Comment by 1-alex98** [comment]
Did it use 4gb ram or not
?

**Comment by 1-alex98** [comment]
Log again please then

**Comment by 1-alex98** [comment]
Please have a look again at the install directory of the client and look if you can find a file called java_(....).hprof

**Comment by 1-alex98** [comment]
What is your OS?

**Comment by EmielWitteman** [comment]
can't find java_pid.hprof, win 10 pro x64 1803, i'll try to monitor the mem usage

**Comment by jonathanhillwebsite** [comment]
I've also had the same issue, maybe 3 times now, with the new client. Twice today.

Happened literally just now for the second time today. The client just closes by itself with the game still running. No message to say it crashed, it just disappears. So it disconnects from the server and looks like I've dc'd. Tried logging back in but that doesn't help.

Earlier it crashed when I hosted a game, ~3 mins in. Now it crashed when I joined a game, 16 mins in.

Not sure how to check the logs. 

Using Windows 10. Decent computer with well over the specs to run the game and a good steady ethernet connection. Only difference over the past month is the new client and that I've switched over to bitdefender antivirus, but there's no messages on the antivirus to indicate that's the problem

**Comment by micheljung** [comment]
@axel1200 what indicates that he ran out of memory? The client doesn't just disappear when it runs out of memory, it freezes as the GC consumes all CPU.

I highly recommend understanding the symptoms better before suggesting things like increasing memory.

**Comment by 1-alex98** [comment]
Well it does freeze and then dissapear if he is in game the client can freeze and then disappear however when in game it might be that the user did not notice the freeze...

**Comment by 1-alex98** [comment]
To be honest I also experienced this issue right at the start once, nothing that hints at the crash anywhere

**Comment by 1-alex98** [comment]
Form what it is written into the client logs it looked like I had normally clicked the x button. Executor service was shutdown etc. From what it looks like it was like a normal shutdown when clicking x. Maybe it is a ui glitch and you can click the x button through the game which is above it ....

**Comment by 1-alex98** [comment]
Or a different programm.

**Comment by 1-alex98** [comment]
Maybe we can add a log statements at this point
