### ISSUE TITLE
make ForgedAlliance.exe executable on Linux

### ISSUE THREAD

**Issue by muellni** [FAForever/downlords-faf-client#1081]
when starting a game on Linux the following error occures: 
```
2019-01-02 13:00:26.006  WARN 7291 --- [     Thread-627] com.faforever.client.game.GameService    : Game could not be started

java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "~/.faforever/bin/ForgedAlliance.exe" (in directory "~/.faforever/bin"): error=13, Permission denied
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:109) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Caused by: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/home/sws/.faforever/bin/ForgedAlliance.exe" (in directory "/home/sws/.faforever/bin"): error=13, Permission denied
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82) ~[nocatch-1.1.jar:na]
	at com.faforever.client.game.GameService.lambda$startGame$33(GameService.java:467) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[na:na]
	... 4 common frames omitted
Caused by: java.io.IOException: Cannot run program "/home/sws/.faforever/bin/ForgedAlliance.exe" (in directory "/home/sws/.faforever/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[na:na]
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[na:na]
	at com.faforever.client.fa.ForgedAllianceService.launch(ForgedAllianceService.java:128) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.fa.ForgedAllianceService.startGame(ForgedAllianceService.java:73) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.lambda$startGame$32(GameService.java:467) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100) ~[nocatch-1.1.jar:na]
	... 7 common frames omitted
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method) ~[na:na]
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339) ~[na:na]
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270) ~[na:na]
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[na:na]
	... 12 common frames omitted
```

Setting the executable bit on `~/.faforever/bin/ForgedAlliance.exe` fixes this error

**Comment by tatsujb** [comment]
@muellni you said :

> Setting the executable bit on ~/.faforever/bin/ForgedAlliance.exe

what do you mean by that?

you made it executable but are you telling FAF to point to that for FA in it's settings? what exactly are you doing?

asking because I also have problems.

**Comment by muellni** [comment]
> what do you mean by that?

I mean `chmod +x ~/.faforever/bin/ForgedAlliance.exe`. The client downloads and runs this executable automatically. But on Linux this file need the executable flag, else the system won't start it.
I suggest that the client sets the executable flag (since it downloads/creates that file).

**Comment by tatsujb** [comment]
@muellni  ok then I correctly understood you.

what I don't understand is why after having made it executable nothing changed for me.

I could join and host global games but couldn't join 1v1s

and after making it executable, all of the above remains true.

what did it change for you? 

also do you have one of these issues?

https://github.com/FAForever/downlords-faf-client/issues/1096
https://github.com/FAForever/downlords-faf-client/issues/1095

**Comment by tatsujb** [comment]
Ok so I hadn't deleted my .faforever folder and .com.faforever.client.FafClientApplication folder.

deleting them caused the fact that .faforever/bin/ForgedAlliance.exe was now executable to be taken into consideration and now I no longer experience those two bugs.

thanks for posting this issue. it helped me understand mine.

**Comment by tatsujb** [comment]
hey @muellni (also @Geosearchef ) could you take a look at this new install method : https://www.youtube.com/watch?v=4B6EsXtL8C0 (Steam instead of wine)

I get everything working except 1v1 

I'm getting the same error as before but this time removing the .`faforever` and `.com.faforever.client.FafClientApplication` folders and making all of `.faforever/bin/` executable doesn't fix it like it did before  :  
![image](https://user-images.githubusercontent.com/5132359/51779175-0d68c080-2106-11e9-904a-00d9f49ca845.png)


```
Failed to setup initial search path.

Program : Z:\home\t\.faforever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /cybran /log /home/t/.faforever/logs/game.log /gpgnet 127.0.0.1:46637 /mean 863.749 /deviation 66.2989 /savereplay gpgnet://127.0.0.1:46019/9212315/tatsu.SCFAreplay /country FR /clan BPT /numgames 2193 /team 1 /players 2

Callstack:
    unavailable.

Last 100 lines of log...

warning: Running "Z:\home\t\.faforever\bin\init.lua" failed: cannot read init_faf.lua: No such file or directory
         stack traceback:
         	[C]: in function `dofile'
         	Z:\home\t\.faforever\bin\init.lua(1): in main chunk
```


JAVA stack : 
```
2019-01-26 00:57:04.650  WARN 2400 --- [pool-2-thread-6] c.f.c.patch.BireusFeaturedModUpdater     : Error while testing http://content.faforever.com/bireus/ladder1v1/

java.io.FileNotFoundException: http://content.faforever.com/bireus/ladder1v1//info.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
	at java.base/java.net.URL.openStream(URL.java:1117) ~[na:na]
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1595) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:793) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2959) ~[jackson-databind-2.9.7.jar:2.9.7]
	at com.faforever.client.patch.BireusFeaturedModUpdater.canUpdate(BireusFeaturedModUpdater.java:57) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.patch.GameUpdaterImpl.updateFeaturedMod(GameUpdaterImpl.java:164) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.patch.GameUpdaterImpl.update(GameUpdaterImpl.java:79) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.updateGameIfNecessary(GameService.java:424) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.lambda$startSearchLadder1v1$25(GameService.java:374) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

2019-01-26 00:57:04.662  INFO 2400 --- [pool-2-thread-7] c.f.client.relay.LocalRelayServerImpl    : GPG relay server listening on port 38357
2019-01-26 00:57:05.272  INFO 2400 --- [pool-2-thread-5] c.f.c.patch.GameBinariesUpdateTaskImpl   : Updating binaries to 3703
2019-01-26 00:57:05.324 DEBUG 2400 --- [erPool0-thread6] c.f.client.chat.PircBotXChatService      : 
2019-01-26 00:57:07.524 DEBUG 2400 --- [erPool0-thread1] c.f.client.chat.PircBotXChatService      : 
2019-01-26 00:57:32.148  INFO 2400 --- [      Thread-11] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [/home/t/Documents/proton_t/run, /home/t/.faforever/bin/ForgedAlliance.exe, /init, init.lua, /nobugreport, /aeon, /log, /home/t/.faforever/logs/game.log, /gpgnet, 127.0.0.1:38357, /mean, 863.749, /deviation, 66.2989, /savereplay, gpgnet://127.0.0.1:44247/9184307/tatsu.SCFAreplay, /country, FR, /clan, BPT, /numgames, 2193, /team, 1, /players, 2] in directory: /home/t/.faforever/bin
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libnss3.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libnss3.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

```

**Comment by douglasg14b** [comment]
Also having the same issue as @tatsujb kinda sucks since I have 0 rank and 0 games played, makes it difficult to get into custom games...

I wonder if the previous 1v1 support should be re-opened and this be there instead? Would be more semantic given the title of this issue.

**Comment by Wesmania** [comment]
How are you supposed to run a Windows executable on Linux directly? You should run them via wine anyway, and it doesn't care if the file it runs is marked as executable. If running the executable directly, then it's probably because the system associated Windows executables with Wine, but that's not the case in every distro.

**Comment by douglasg14b** [comment]
Linking to the 1v1 thread for the above issues tatsu and I where having: https://github.com/FAForever/downlords-faf-client/issues/1095
