### ISSUE TITLE
Gateway address can't be detected on Russian system

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1094]
From http://forums.faforever.com/viewtopic.php?f=3&t=17116#p171204

`netstat -rn` returns:
```
    Microsoft Windows [Version 6.1.7601]
    (c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

    C:\Users\NUDNUD>netstat -rn
    ===========================================================================
    Список интерфейсов
    23...........................Tele2 Internet RU
    16...58 2c 80 13 92 63 ......Mobile Connect - Network Card #2
    11...00 23 54 cd b7 c3 ......Сетевая карта Realtek RTL8102E/RTL8103E Family PCI
    -E Fast Ethernet NIC (NDIS 6.20)
      1...........................Software Loopback Interface 1
    12...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP
    13...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #2
    15...00 00 00 00 00 00 00 e0 Адаптер Microsoft ISATAP #3
    ===========================================================================

    IPv4 таблица маршрута
    ===========================================================================
    Активные маршруты:
    Сетевой адрес           Маска сети      Адрес шлюза       Интерфейс  Метрика
              0.0.0.0          0.0.0.0         On-link     10.100.155.57     26
        10.100.155.57  255.255.255.255         On-link     10.100.155.57    281
            127.0.0.0        255.0.0.0         On-link         127.0.0.1   4531
            127.0.0.1  255.255.255.255         On-link         127.0.0.1   4531
      127.255.255.255  255.255.255.255         On-link         127.0.0.1   4531
            224.0.0.0        240.0.0.0         On-link         127.0.0.1   4531
            224.0.0.0        240.0.0.0         On-link     10.100.155.57     26
      255.255.255.255  255.255.255.255         On-link         127.0.0.1   4531
      255.255.255.255  255.255.255.255         On-link     10.100.155.57    281
    ===========================================================================
    Постоянные маршруты:
      Отсутствует

    IPv6 таблица маршрута
    ===========================================================================
    Активные маршруты:
    Метрика   Сетевой адрес            Шлюз
      1    306 ::1/128                  On-link
      1    306 ff00::/8                 On-link
    ===========================================================================
    Постоянные маршруты:
      Отсутствует
```

This isn't parsed correctly:

```
Caused by: java.net.UnknownHostException: Р­С‚РѕС‚ С…РѕСЃС‚ РЅРµРёР·РІРµСЃС‚РµРЅ (On-link)
    at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
    at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
    at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
    at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
    at java.base/java.net.InetAddress.getAllByName(Unknown Source)
    at java.base/java.net.InetAddress.getAllByName(Unknown Source)
    at java.base/java.net.InetAddress.getByName(Unknown Source)
    at com.faforever.client.net.GatewayUtil.findGateway(GatewayUtil.java:43)
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100)
```

I suspect that the encoding needs to be specified correctly.

**Comment by Iridescens** [comment]
According to data presented by player it is clear that the GatewayUtil code itself is working despite having garbled characters. Fixing encoding issues will not solve this particular case as player's network config is a busted by not having a default GW. The "On-link" GW for 0.0.0.0 is FUBAR.
Can't imagine this happening as he/she shouldn't be able to connect to Internet as well.

**Comment by micheljung** [comment]
This has become obsolete by the ICE adapter integration.
