### ISSUE TITLE
[ Linux ] [ v0.9.3-beta ] join global game support

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1096]
This is what I run into for a lot of global games (around 50%) when I try to join :
![screenshot from 2019-01-21 17-53-38](https://user-images.githubusercontent.com/5132359/51488302-81713480-1da5-11e9-86e4-e5cbada2c82f.png)

Here's what the stacktrace contains :
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.faforever.client.task.CompletableTask.lambda$new$2(CompletableTask.java:18)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1358)
	at javafx.concurrent.Task.setState(Task.java:725)
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1436)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at java.base/java.nio.file.Files.provider(Files.java:99)
	at java.base/java.nio.file.Files.isDirectory(Files.java:2220)
	at com.faforever.client.map.MapService.readMap(MapService.java:223)
	at com.faforever.client.map.MapService.addSkirmishMap(MapService.java:210)
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$15(MapService.java:439)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$16(MapService.java:439)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 22 more

```

the criteria for this issue occurring seems to be that the map is non-vanilla (although how to define that is unclear because hosting and joining non-vanilla maps sometimes works sometimes doesn't)

for reference I am using this guide : https://youtu.be/RRINgZQl7LU
(text version here : https://pastebin.com/jNrTFxvV )

with the sole difference of having made all of the contents of $HOME/.faforever/bin executable on top of the other things I do in my guide.

**Comment by tatsujb** [comment]
fixed by making  `$HOME/.faforever/bin/ForgedAlliance.exe` executable, as indicated in : https://github.com/FAForever/downlords-faf-client/issues/1081

the solution is therefore that that file be tarballed with executable permissions on.

extracting with `tar -pxvzf xxx.tar.gz` will then preserve the permissions.
