### ISSUE TITLE
[ v0.9.3-beta ] Replay vault: search for ID throws an error if query contains non numeric characters

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1097]
Searching with any option and any keyword under the "Vault" -> "Online Replays" tab results in this 
![screenshot from 2019-01-21 18-02-33](https://user-images.githubusercontent.com/5132359/51488780-c34eaa80-1da6-11e9-9b44-029bb0c95a2b.png)

Here is the content of the Stacktrace :

```
java.util.concurrent.CompletionException: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:279)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:79)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:97)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:172)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:310)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:587)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:574)
	at com.faforever.client.api.FafApiAccessorImpl.findReplaysByQuery(FafApiAccessorImpl.java:322)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
	at com.sun.proxy.$Proxy60.findReplaysByQuery(Unknown Source)
	at com.faforever.client.remote.FafService.findReplaysByQuery(FafService.java:299)
	at com.faforever.client.remote.FafService$$FastClassBySpringCGLIB$$6c91c77e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	... 4 more

```

for reference I am using this guide : https://youtu.be/RRINgZQl7LU
(text version here : https://pastebin.com/jNrTFxvV )

with the sole difference of having made all of the contents of $HOME/.faforever/bin executable on top of the other things I do in my guide.

(search under maps and mods works)

**Comment by Brutus5000** [comment]
This only happens if you give an alphanumeric value for the ID property because our API expects a number here. On the title, this does not throw an error.

**This is not a Linux issue. All platforms are affected.**

Unfortunately, this is not easily solvable. JSONAPI declares ID to be a String, but technically it remains a number in the database. I will try to tackle this in the query criteria refactor I am working on.

**Comment by Geosearchef** [comment]
This also happens when using contains and entering any ID as the api probably doesn't expect the non numeric stars in the id:

https://api.faforever.com/data/game?filter=id==%22*9351058*%22

**Comment by Chubbly** [comment]
For further information, at least part of this bug appears to be intermittent and related specifically to Download's client, not the API call. In my client (0.9.3 beta) from New Zealand, all search requests return a 400 Bad Request error. However, a friend of mine in Germany tried the ID search and had no issues. I mention the countries just on the off-chance it is relevant.

Also, I have no issues when doing a similar search using the legacy client.

**Comment by Sheikah45** [comment]
Cannot reproduce in current client
