### ISSUE TITLE
the bireus error

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1129]
Upon hosting a game in FAF client I get this  in the console that is running FAF client with a short and a long variant.  

short : 
```
2019-03-05 00:52:50.474  WARN 4859 --- [ool-2-thread-10] c.f.c.patch.BireusFeaturedModUpdater     : Error while testing http://content.faforever.com/bireus/faf/

java.io.FileNotFoundException: http://content.faforever.com/bireus/faf//info.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
	at java.base/java.net.URL.openStream(URL.java:1117) ~[na:na]
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1595) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:793) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2959) ~[jackson-databind-2.9.7.jar:2.9.7]
	at com.faforever.client.patch.BireusFeaturedModUpdater.canUpdate(BireusFeaturedModUpdater.java:57) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.patch.GameUpdaterImpl.updateFeaturedMod(GameUpdaterImpl.java:164) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.patch.GameUpdaterImpl.update(GameUpdaterImpl.java:79) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.updateGameIfNecessary(GameService.java:424) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.lambda$joinGame$9(GameService.java:248) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
```
long :
```
2019-03-05 00:28:26.435  WARN 4217 --- [lication Thread] c.f.c.patch.BireusFeaturedModUpdater     : Error while testing http://content.faforever.com/bireus/faf/

java.io.FileNotFoundException: http://content.faforever.com/bireus/faf//info.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
	at java.base/java.net.URL.openStream(URL.java:1117) ~[na:na]
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1595) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:793) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2959) ~[jackson-databind-2.9.7.jar:2.9.7]
	at com.faforever.client.patch.BireusFeaturedModUpdater.canUpdate(BireusFeaturedModUpdater.java:57) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.patch.GameUpdaterImpl.updateFeaturedMod(GameUpdaterImpl.java:164) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.patch.GameUpdaterImpl.update(GameUpdaterImpl.java:79) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.updateGameIfNecessary(GameService.java:424) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.hostGame(GameService.java:226) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.CreateGameController.onCreateButtonClicked(CreateGameController.java:400) [downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) [na:na]
	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) [javafx-fxml-11-linux.jar:na]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784) [javafx-fxml-11-linux.jar:na]
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670) [javafx-fxml-11-linux.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [javafx-base-11-linux.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [javafx-base-11-linux.jar:na]
	at javafx.scene.Node.fireEvent(Node.java:8879) [javafx-graphics-11-linux.jar:na]
	at javafx.scene.control.Button.fire(Button.java:200) [javafx-controls-11-linux.jar:na]
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206) [javafx-controls-11-linux.jar:na]
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274) ~[javafx-controls-11-linux.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [javafx-base-11-linux.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [javafx-base-11-linux.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851) ~[javafx-graphics-11-linux.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579) ~[javafx-graphics-11-linux.jar:na]
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849) ~[javafx-graphics-11-linux.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) ~[javafx-graphics-11-linux.jar:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.View.notifyMouse(View.java:942) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277) ~[javafx-graphics-11-linux.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

```
I also get a FAF error report inside FAF gui on modded map join : 
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.faforever.client.task.CompletableTask.lambda$new$2(CompletableTask.java:18)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1358)
	at javafx.concurrent.Task.setState(Task.java:725)
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1436)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at java.base/java.nio.file.Files.provider(Files.java:99)
	at java.base/java.nio.file.Files.isDirectory(Files.java:2220)
	at com.faforever.client.map.MapService.readMap(MapService.java:223)
	at com.faforever.client.map.MapService.addSkirmishMap(MapService.java:210)
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$15(MapService.java:439)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$16(MapService.java:439)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 22 more

```
I can't really explain this bug since after checking everything, every sort of factor that could be at play system-wide I can't really find a cause.

this: `http://content.faforever.com/bireus/faf/` seems weird to me. why the heck is this being called?

**Comment by 1-alex98** [comment]
Bireus is not yet running at FAF bireus is a patcher so this exception is just fine please open up another issues for the other bug
