### ISSUE TITLE
Coop mission name resolving seems to not work correctly

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1134]
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Map folder name did not match with any coop mission
        at com.faforever.client.coop.CoopController.lambda$initialize$20(CoopController.java:172)
at java.base/java.util.Optional.orElseThrow(Unknown Source)
```

**Comment by 1-alex98** [comment]
Lets first display unknow map instead of throwing an exception

**Comment by Askaholic** [comment]
Is there still something to do here?

**Comment by 1-alex98** [comment]
The Exception is still in the logs for some missions so yes. Something is wrong there.

**Comment by Sheikah45** [comment]
How do you reproduce this?

**Comment by 1-alex98** [comment]
You have luck that somebody hosts missions that have this issue...

**Comment by 1-alex98** [comment]
or u try do that yourself

**Comment by Marc-Spector** [comment]
The issue is not relevant. All mission names are displayed correctly.
