### ISSUE TITLE
0.10.0 natives/faf-uid: Operation not permitted on Linux

### ISSUE THREAD

**Issue by dcelasun** [FAForever/downlords-faf-client#1157]
This started happenning after the update, can't start FAF at all.

![Screenshot_2019-04-21_16-17-19](https://user-images.githubusercontent.com/144373/56471278-fad5fd00-6450-11e9-800a-016f3cab8566.png)

I've made sure the file is executable, even tried `chmod 777` but it doesn't work:

```sh
$ cd /usr/share/java/downlords-faf-client/
$ ls -alh
total 48K
drwxr-xr-x  5 root root 4.0K Apr 20 20:52 .
drwxr-xr-x 10 root root 4.0K Apr 10 08:38 ..
-rwxr-xr-x  1 root root  12K Apr 20 20:52 downlords-faf-client
-rw-r--r--  1 root root   84 Apr 20 20:52 downlords-faf-client.vmoptions
-rwxr-xr-x  1 root root 3.5K Apr 20 20:52 icon.png
drwxr-xr-x  2 root root 4.0K Apr 20 20:52 .install4j
drwxr-xr-x  2 root root  12K Apr 20 20:58 lib
drwxr-xr-x  2 root root 4.0K Apr 20 20:52 natives
$ ls -alh natives/
total 10M
drwxr-xr-x 2 root root 4.0K Apr 20 20:52 .
drwxr-xr-x 5 root root 4.0K Apr 20 20:52 ..
-rwxrwxrwx 1 root root 4.8M Apr 20 20:52 faf-ice-adapter.jar
-rwxrwxrwx 1 root root 3.0M Apr 20 20:52 faf-uid
-rwxrwxrwx 1 root root 2.3M Apr 20 20:52 faf-uid.exe

```

Stack trace:

```
java.nio.file.FileSystemException: natives/faf-uid: Operation not permitted
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:254) ~[na:na]
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:276) ~[na:na]
        at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2071) ~[na:na]
        at com.faforever.client.legacy.PosixUidService.generate(PosixUidService.java:25) ~[downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at com.faforever.client.remote.FafServerAccessorImpl.logIn(FafServerAccessorImpl.java:478) [downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at com.faforever.client.remote.FafServerAccessorImpl.onSessionInitiated(FafServerAccessorImpl.java:473) [downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at com.faforever.client.remote.FafServerAccessorImpl.lambda$parseServerObject$1(FafServerAccessorImpl.java:438) [downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at com.faforever.client.remote.FafServerAccessorImpl.parseServerObject(FafServerAccessorImpl.java:438) [downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at com.faforever.client.remote.FafServerAccessorImpl.onServerMessage(FafServerAccessorImpl.java:407) [downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at com.faforever.client.remote.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:44) ~[downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:253) ~[downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:225) ~[downlords-faf-client-0.10.0-beta.jar:0.10.0-beta]
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425) ~[javafx-graphics-11-linux.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at javafx.concurrent.Service.lambda$executeTask$6(Service.java:725) ~[javafx-graphics-11-linux.jar:na]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
        at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724) ~[javafx-graphics-11-linux.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
```

**Comment by dcelasun** [comment]
Ah, I think I've found the problem, looks like the client now expects the FAF install directory to be **owned** by the running user (`java.nio.file.Files.setPosixFilePermissions`).

I understand why you might wanna do this, but maybe just make it a warning in the console and keep going? After all, the permissions are *already* correct.
