### ISSUE TITLE
Coop replays are broken

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#1164]
Example replay: 9576247

Seems like it can't read the map properly.
It can be launched via python client without any issues.
```
java.util.concurrent.CompletionException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://content.faforever.com/faf/vault/maps/.zip
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.lambda$call$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://content.faforever.com/faf/vault/maps/.zip
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:55)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:22)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://content.faforever.com/faf/vault/maps/.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.base/java.net.URLConnection.getHeaderFieldLong(Unknown Source)
	at java.base/java.net.URLConnection.getContentLengthLong(Unknown Source)
	at java.base/java.net.URLConnection.getContentLength(Unknown Source)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:51)
	... 6 more
```

**Comment by CyrilPaulus** [comment]
I've checked the code and it seems that the URL to download the replay is not correctly built.
Instead of using the replay Id, the client use the ID of the entry in the leaderboard.
That why there is a file not found exception.

**Comment by 1-alex98** [comment]
If you wan to you can fork the project fix the bug and make a PR ;)

**Comment by CyrilPaulus** [comment]
I'd like to but I'm unable to correctly setup the project on my computer with Intellij Community.

**Comment by 1-alex98** [comment]
There is a youtube video in the read me

**Comment by 1-alex98** [comment]
Make sure u use oracle jdk 10

**Comment by 1-alex98** [comment]
Also if you give me your email I can invite u to slack

**Comment by CyrilPaulus** [comment]
Yep I saw this video but I guess it's not working because I can't find the oracle jdk 10 anywhere.
Where can I send you my email ? I'd prefer to avoid posting it there.

Edit: Just found the link for the JDK.

**Comment by CyrilPaulus** [comment]
Okay so it was easy to fix the bug by using the CoopResult getGame().getId() instead of getId() for binding the replay download button.

But for some reason for coop replays the map field in the json is empty. Thus when it tries to download the map a exception is raised.

Now an easy fix is to edit the method downloadMapIfNecessary to ignore empty map name. But it seems more a hack than a correct fix.

And when launched the game will desync because the coop script are not downloaded before hand.

One way to fix that would be to download all the necessary coop scripts/map/mods before running the replay but it seems it should be handled the same way as a normal replay.

I'm a bit stuck now.

**Comment by 1-alex98** [comment]
write me alexander.von.trostorff@gmail.com

**Comment by 1-alex98** [comment]
I am not into it too much but we can have a look together like e.g. tonight
