### ISSUE TITLE
"The requested operation requires elevation" - Fixed by running as admin - Warning on launch.

### ISSUE THREAD

**Issue by RoraRaven** [FAForever/downlords-faf-client#1238]
When the FAF client is run without administrator privileges, this error is presented when you try to enter a game.

    java.util.concurrent.CompletionException: java.io.IOException: Cannot run program "i:\program 
    files\downlord's faf client\jre\bin\java.exe" (in directory "I:\Program Files\Downlord's FAF 
    Client\natives"): CreateProcess error=740, The requested operation requires elevation
	    at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
	    at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
	    at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
	    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown 
    Source)
	    at com.faforever.client.fa.relay.ice.IceAdapterImpl.lambda$start$6(IceAdapterImpl.java:232)
	    at java.base/java.lang.Thread.run(Unknown Source)
    Caused by: java.io.IOException: Cannot run program "i:\program files\downlord's faf 
    client\jre\bin\java.exe" (in directory "I:\Program Files\Downlord's FAF Client\natives"): 
    CreateProcess error=740, The requested operation requires elevation
	    at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	    at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	    at com.faforever.client.fa.relay.ice.IceAdapterImpl.lambda$start$6(IceAdapterImpl.java:198)
	    ... 1 more
    Caused by: java.io.IOException: CreateProcess error=740, The requested operation requires 
    elevation
	    at java.base/java.lang.ProcessImpl.create(Native Method)
	    at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	    at java.base/java.lang.ProcessImpl.start(Unknown Source)
	    ... 4 more

If the FAF client is run as administrator, this issue disappears. However, you're then warned about running the client in admin mode, every time.

Could a "Don't Show This Warning Again" option be added to the admin mode warning?

**Comment by 1-alex98** [comment]
No I dont want to. You should not run as admin and if you do you will be reminded on every startup

**Comment by 1-alex98** [comment]
There is something wrong with the permission needed  for those files i:\program files\downlord's faf 
client\jre\bin\java.exe

**Comment by RoraRaven** [comment]
The thing is, it only works on admin, otherwise I get the "requires elevation" notification.

I've purged the ProgramData and Program Files folders. Totally fresh install, still wouldn't launch without running as admin.
