### ISSUE TITLE
Coop leaderboards errors

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#1330]
By default the coop leaderboards load Black Day missions, results for 2 players.
One thing, can you make it default to All players?

Second if I switch to all I get this error:
```
java.util.concurrent.CompletionException: org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Server Error
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:279)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Server Error
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:99)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:84)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:310)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:625)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:612)
	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:602)
	at com.faforever.client.api.FafApiAccessorImpl.getCoopLeaderboard(FafApiAccessorImpl.java:495)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:53)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:365)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:420)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy67.getCoopLeaderboard(Unknown Source)
	at com.faforever.client.remote.FafService.getCoopLeaderboard(FafService.java:214)
	at com.faforever.client.remote.FafService$$FastClassBySpringCGLIB$$6c91c77e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	... 4 more

```

**Comment by Askaholic** [comment]
I noticed that there are some missions for which the "All" query will load correctly, and others for which it throws this error. This may be a client issue, or maybe an API issue. Someone should investigate the query and look at the API logs.

**Comment by Brutus5000** [comment]
The reason here is an issue on server side. If you look into the payload you will see an error that is in theory impossible to happen:
```
{
    "requestId": "ffdda9cd-6b0b-4645-a5ed-e712f0db14ed",
    "errors": [
        {
            "status": "500",
            "title": "javax.persistence.EntityNotFoundException",
            "detail": "Unable to find com.faforever.api.data.domain.Game with id 9839438"
        }
    ]
}
```

Meaning we have a game id in a coop table where is no corresponding record in the game table.

**Comment by Brutus5000** [comment]
Error is fixed in the db table by a foreign key constraint. The root cause still resides in the server and will probably never be found...
