### ISSUE TITLE
Discord Join if game has password fails

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1334]
```
java.lang.IllegalStateException: Not on FX application thread; currentThread = Timer-0
	at javafx.graphics/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/javafx.stage.Stage.<init>(Unknown Source)
	at com.faforever.client.game.EnterPasswordController.showPasswordDialog(EnterPasswordController.java:81)
	at com.faforever.client.game.JoinGameHelper.join(JoinGameHelper.java:83)
	at com.faforever.client.game.JoinGameHelper.join(JoinGameHelper.java:59)
	at com.faforever.client.game.JoinGameHelper.join(JoinGameHelper.java:112)
	at com.faforever.client.game.JoinGameHelper.onDiscordGameJoinEvent(JoinGameHelper.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:368)
	at com.faforever.client.discord.ClientDiscordEventHandler.onJoinGame(ClientDiscordEventHandler.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:414)
	at com.sun.jna.Function.invoke(Function.java:360)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at net.arikia.dev.drpc.$Proxy70.Discord_RunCallbacks(Unknown Source)
	at net.arikia.dev.drpc.DiscordRPC.discordRunCallbacks(DiscordRPC.java:92)
	at com.faforever.client.discord.DiscordRichPresenceService$1.run(DiscordRichPresenceService.java:55)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)
```

**Comment by 1-alex98** [comment]
Mak it use Platform.runlater
