### ISSUE TITLE
Downlord's FAF Client not starting , as it crashes reading server settings

### ISSUE THREAD

**Issue by ghost** [FAForever/downlords-faf-client#1368]
Tried to start FAF client and got this java startup error.
Log;

Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.github.nocatch.NoCatchException: javafx.fxml.LoadException: 
file:/D:/Program%20Dosyalar%c4%b1%20(x86)/Downlord's%20FAF%20Client/lib/downlords-faf-client-0.10.7.jar!/theme/login.fxml

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.theme.UiService.loadFxml(UiService.java:412)
	at com.faforever.client.theme.UiService$$FastClassBySpringCGLIB$$2b0b2208.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.faforever.client.theme.UiService$$EnhancerBySpringCGLIB$$d9340258.loadFxml(<generated>)
	at com.faforever.client.main.MainController.enterLoggedOutState(MainController.java:389)
	at com.faforever.client.main.MainController.display(MainController.java:371)
	at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:116)
	at com.faforever.client.FafClientApplication.start(FafClientApplication.java:100)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	... 1 more
Caused by: javafx.fxml.LoadException: 
file:/D:/Program%20Dosyalar%c4%b1%20(x86)/Downlord's%20FAF%20Client/lib/downlords-faf-client-0.10.7.jar!/theme/login.fxml

	at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 23 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:865)
	at com.faforever.client.preferences.PreferencesService.getRemotePreferences(PreferencesService.java:351)
	at com.faforever.client.login.LoginController.initialize(LoginController.java:150)
	... 33 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 37 more

**Comment by taz4hvn** [comment]
Same here, since about an hour ago.

**Comment by ronybeck** [comment]
Same here for myself and my friend.  Is this perhaps a server problem?

**Comment by axel1200** [comment]
no this problem is really strange but heard of it before

**Comment by axel1200** [comment]
What would help is if u gave me the following file any of you that has problems with it D:/Program%20Dosyalar%c4%b1%20(x86)/Downlord's%20FAF%20Client/lib/downlords-faf-client-0.10.7.jar

**Comment by axel1200** [comment]
downlords-faf-client-0.10.7.jar in the lib folder of the installation

**Comment by 1-alex98** [comment]
Send me your client.prefs file
![image](https://user-images.githubusercontent.com/19996713/61995629-2b9a8380-b08b-11e9-885f-3580959888a4.png)
And then delete it... It will probably work again after this

**Comment by 1-alex98** [comment]
userhome /AppData/Roaming/Forged Alliance Forever

U need to tell explorer to show hidden files

**Comment by salvationFPS** [comment]
i can send mine, i have same issue 

[client.zip](https://github.com/FAForever/downlords-faf-client/files/3438268/client.zip)

**Comment by 1-alex98** [comment]
@slvtn also your exact error the pls, you saying it is exactly the same is cool but did you check line by line???

**Comment by 1-alex98** [comment]
And if u are done 
> And then delete it... It will probably work again after this

**Comment by salvationFPS** [comment]
> @slvtn also your exact error the pls, you saying it is exactly the same is cool but did you check line by line???

its very strange, right now im execute client and it runs fine, but a few hours ago it crash with same error as discribed in this issue i swear :)))

**Comment by 1-alex98** [comment]
ups, actually i missread the error it is not about client.prefs...
Those are server prefs @Brutus5000

**Comment by 1-alex98** [comment]
We have some settings that are automatically fetched, but those seem to be malformed

**Comment by 1-alex98** [comment]
Probably @Brutus5000 changed something that broke it

**Comment by taz4hvn** [comment]
well starts again for me now, but hangs in the "play" tab throwing a lot of "java.lang.ArrayIndexOutOfBoundsException"

**Comment by taz4hvn** [comment]
everything back to normal. thx

**Comment by RWolfing** [comment]
I am running into the same error when trying to start the client as initially mentioned. 
Stacktrace: [error.txt](https://github.com/FAForever/downlords-faf-client/files/4032658/error.txt)

EDIT: Reinstalling the newest version of the client fixes the issue. It is hard to see the notification that the client should be updated if one can not start the client anymore ;).
