### ISSUE TITLE
Wrong file is started instead of ice adapter

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1392]
java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\Program Files\Downlord's FAF Client"): CreateProcess error=2, Не удается найти указанный файл
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
    at com.faforever.client.fa.relay.ice.IceAdapterImpl.lambda$start$8(IceAdapterImpl.java:233)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\Program Files\Downlord's FAF Client"): CreateProcess error=2, Не удается найти указанный файл
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.base/java.lang.reflect.Constructor.newInstance(Unknown Sourc

**Comment by 1-alex98** [comment]
I have no idea what u mean

**Comment by Geosearchef** [comment]
Read the stacktrace again.
The line launching the ice adapter throws an exception as it cannot start the file init, probably as it is not an executable. It shouldn't start that file.

**Comment by 1-alex98** [comment]
This error normally happens with the user has no %s in executable decorator setting

**Comment by Geosearchef** [comment]
The executable decorator has nothing to do with the adapter.

**Comment by 1-alex98** [comment]
I do think it does.... This stack trace is incomplete and the important part is missing

**Comment by 1-alex98** [comment]
It is exactly as I said:

This execption is thrown when I set my executable decorator to ""
```

java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.faforever.client.fa.relay.ice.IceAdapterImpl.lambda$start$8(IceAdapterImpl.java:233)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82)
	at com.faforever.client.game.GameService.lambda$startGame$27(GameService.java:470)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 4 more
Caused by: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.faforever.client.fa.ForgedAllianceService.launch(ForgedAllianceService.java:128)
	at com.faforever.client.fa.ForgedAllianceService.startGame(ForgedAllianceService.java:73)
	at com.faforever.client.game.GameService.lambda$startGame$26(GameService.java:470)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 12 more


```

**Comment by 1-alex98** [comment]
Tell the user to set it to "%s"

**Comment by 1-alex98** [comment]
So we need to add a check in that makes "" result into the default but I thought I already did so
