### ISSUE TITLE
Trying to launch the game Getting error message. 

### ISSUE THREAD

**Issue by TheWilson1** [FAForever/downlords-faf-client#1426]
Game was working fine up until a few days ago. 

I am now getting this error when i try and create/join a game. 

java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at com.faforever.client.fa.relay.ice.IceAdapterImpl.lambda$start$8(IceAdapterImpl.java:233)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, The system cannot find the file specified
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82)
	at com.faforever.client.game.GameService.lambda$startGame$27(GameService.java:470)
	... 5 more
Caused by: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.faforever.client.fa.ForgedAllianceService.launch(ForgedAllianceService.java:128)
	at com.faforever.client.fa.ForgedAllianceService.startGame(ForgedAllianceService.java:73)
	at com.faforever.client.game.GameService.lambda$startGame$26(GameService.java:470)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100)
	... 7 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 13 more

Tried full uninstall of both the client and the game. Any help will be appreciated.

**Comment by TheWilson1** [comment]
Now when i create a game it says that the title is missing.

**Comment by 1-alex98** [comment]
ok so there are two options for u here u either delete client.prefs file located in your home directory then AppData\Roaming\Forged Alliance Forever

**Comment by 1-alex98** [comment]
or u enter "%s" including the " into settings here 
![image](https://user-images.githubusercontent.com/19996713/64473579-bd0c1380-d168-11e9-826c-c3af4d5e8f8d.png)

**Comment by 1-alex98** [comment]
We know about this and will be fixed in next release,
You basically entered something in this field and deleted it again which made it change from null to ""

**Comment by TheWilson1** [comment]
Thanks for the help. 

I got help in the discord server and it was fixed by deleting the bin folder in programdata>faforevor>bin. 

It now works fine.

**Comment by 1-alex98** [comment]
strange would not have expected that

**Comment by TheWilson1** [comment]
Me neither. But having tried many things. that was what fixed it. Anyway. Case closed. hope it helps someone out in the future.

**Comment by 1-alex98** [comment]
I am pretty certain it was what I think. I got a lot of those requests

**Comment by 1-alex98** [comment]
And deleting bin folder would not help there ....

**Comment by TheWilson1** [comment]
I can only tell you what worked for me. The "%s" has never been changed. The game location was correct and the execution directory was blank. 

But i got the error when i tried to create or join a game. Like i said i went through forums and discord help channels and the only thing that fixed it was deleting the bin folder i mentioned. The game works fine through the launcher now. Mods enabled. Happy days!
