### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by oceyral** [FAForever/downlords-faf-client#1438]
**Describe the bug**
The 0.10.7 client crashes on startup when calling `checkVaultFileSystemLocation`, at https://github.com/FAForever/downlords-faf-client/blob/v0.10.7/src/main/java/com/faforever/client/vault/VaultFileSystemLocationChecker.java#L46

The traceback is the following : 
```
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.github.nocatch.NoCatchException: javafx.fxml.LoadException: 
file:/usr/share/java/downlords-faf-client/lib/downlords-faf-client-0.10.7.jar!/theme/main.fxml

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.theme.UiService.loadFxml(UiService.java:412)
	at com.faforever.client.theme.UiService$$FastClassBySpringCGLIB$$2b0b2208.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.faforever.client.theme.UiService$$EnhancerBySpringCGLIB$$c58fa49b.loadFxml(<generated>)
	at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:115)
	at com.faforever.client.FafClientApplication.start(FafClientApplication.java:100)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Caused by: javafx.fxml.LoadException: 
file:/usr/share/java/downlords-faf-client/lib/downlords-faf-client-0.10.7.jar!/theme/main.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2595)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2591)
	... 20 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.ascii()Lcom/google/common/base/CharMatcher;
	at com.faforever.client.vault.VaultFileSystemLocationChecker.checkVaultFileSystemLocation(VaultFileSystemLocationChecker.java:46)
	at com.faforever.client.main.MainController.initialize(MainController.java:196)
	... 32 more
```

Manually editing the `client.prefs` to set `forgedAlliance.vaultCheckDone` to `true` bypasses the code block and the client successfully launches, but I'm not sure whether this causes problems or not.

**OS**
Linux

**Comment by 1-alex98** [comment]
Thats what happens if nobody tests my changes on linux XD Well acctually some guys tested them

**Comment by 1-alex98** [comment]
Looks like ther is a different version of guava at runtime than at compile time
Dependency insight on guava... now i have to find out how to read that
```


> Configure project :
Platform is: win

> Task :dependencyInsight
com.google.guava:failureaccess:1.0
   variant "runtime" [
      org.gradle.status = release (not requested)
   ]

com.google.guava:failureaccess:1.0
\--- com.google.guava:guava:27.0-jre
     +--- compile
     \--- com.github.FAForever.faf-java-commons:faf-commons-data:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
          +--- com.github.FAForever:faf-java-commons:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
          |    \--- compile
          \--- com.github.FAForever.faf-java-commons:faf-commons-api:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
               \--- com.github.FAForever:faf-java-commons:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b (*)

com.google.guava:guava:27.0-jre (selected by rule)
   variant "default+runtime" [
      org.gradle.status = release (not requested)
   ]

com.google.guava:guava:27.0-jre
\--- compile

com.google.guava:guava:21.0-rc1 -> 27.0-jre
\--- com.github.FAForever.faf-java-commons:faf-commons-data:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
     +--- com.github.FAForever:faf-java-commons:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
     |    \--- compile
     \--- com.github.FAForever.faf-java-commons:faf-commons-api:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
          \--- com.github.FAForever:faf-java-commons:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b (*)

com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
   variant "runtime" [
      org.gradle.status = release (not requested)
   ]

com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
\--- com.google.guava:guava:27.0-jre
     +--- compile
     \--- com.github.FAForever.faf-java-commons:faf-commons-data:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
          +--- com.github.FAForever:faf-java-commons:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
          |    \--- compile
          \--- com.github.FAForever.faf-java-commons:faf-commons-api:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b
               \--- com.github.FAForever:faf-java-commons:9aaa2591adaaa9dff07e7e08f7bc9597b477b91b (*)

```

**Comment by 1-alex98** [comment]
Seems like java-comons injects older guava version into our project

**Comment by 1-alex98** [comment]
Would suggest an exclusion like so

```
compile("com.github.FAForever:faf-java-commons:${fafCommonsVersion}") {
    exclude module: 'guava'
  }
```

**Comment by 1-alex98** [comment]
We might consider gradle to fail on cnflicts so we avoid this things all together

**Comment by 1-alex98** [comment]
@oceyral was it after an update???

**Comment by oceyral** [comment]
It was some time ago, but yes I think it was after an update, using the aur package : https://aur.archlinux.org/packages/downlords-faf-client/

**Comment by 1-alex98** [comment]
was linux i forgot. well no idea then
