### ISSUE TITLE
Error downloading files with space characters in file name

### ISSUE THREAD

**Issue by oceyral** [FAForever/downlords-faf-client#1440]
**Describe the bug**
The mod vault (and possibly map vault too) doesn't appear to URLescape space characters (possibly other special characters too), resulting in 400 errors when downloading files.

**To Reproduce**
- Try installing a mod with a space in file name, like common mod tools (`http://content.faforever.com/mods/Common Mod Tools.v0001.zip`)

**Expected behavior**
- The mod is installed

**Actual behavior**
- There is an error with the following text and traceback : 

```
Mod 'Common Mod Tools' could not be installed: java.io.IOException: Server returned HTTP response code: 400 for URL: http://content.faforever.com/mods/Common Mod Tools.v0001.zip
```
```
java.util.concurrent.CompletionException: java.io.IOException: Server returned HTTP response code: 400 for URL: http://content.faforever.com/mods/Common Mod Tools.v0001.zip
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:777)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1358)
	at javafx.concurrent.Task.setState(Task.java:709)
	at javafx.concurrent.Task$TaskCallable.lambda$call$2(Task.java:1455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://content.faforever.com/mods/Common Mod Tools.v0001.zip
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor92.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at com.faforever.client.mod.InstallModTask.call(InstallModTask.java:66)
	at com.faforever.client.mod.InstallModTask.call(InstallModTask.java:32)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://content.faforever.com/mods/Common Mod Tools.v0001.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3033)
	at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
	at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
	at java.base/java.net.URLConnection.getContentLength(URLConnection.java:492)
	at com.faforever.client.mod.InstallModTask.call(InstallModTask.java:63)
	... 6 more
```

This can be trivially reproduced with a simple `curl` :
```
% curl 'http://content.faforever.com/mods/Common Mod Tools.v0001.zip'
400 Bad Request
```
But the download completes successfully when spaces are urlescaped : 
```
% curl 'http://content.faforever.com/mods/Common%20Mod%20Tools.v0001.zip' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25889  100 25889    0     0   468k      0 --:--:-- --:--:-- --:--:--  468k
```

**OS**
Linux

**Comment by PhilipJFryFAF** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1373

**Comment by 1-alex98** [comment]
Duplicate

**Comment by 1-alex98** [comment]
Dowload newest rc(pre-release) if u wanna download it
