### ISSUE TITLE
Map download issue on Linux

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1442]
A bug was reported where Maps fail to download on Linux since the RC 1.0

**Comment by Katharsas** [comment]
Ok, so there is an exception thrown by `MapService # addSkirmishMap(...)` that isn't printed anywhere:
```
java.lang.NullPointerException: null
	at java.base/java.nio.file.Files.provider(Files.java:100) ~[na:na]
	at java.base/java.nio.file.Files.isDirectory(Files.java:2228) ~[na:na]
	at com.faforever.client.map.MapService.readMap(MapService.java:258) ~[main/:na]
	at com.faforever.client.map.MapService.addSkirmishMap(MapService.java:237) ~[main/:na]
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$17(MapService.java:492) ~[main/:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34) ~[nocatch-1.1.jar:na]
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$18(MapService.java:492) ~[main/:na]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at com.faforever.client.task.CompletableTask.lambda$new$2(CompletableTask.java:18) ~[main/:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[javafx-base-11-linux.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[javafx-base-11-linux.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[javafx-base-11-linux.jar:na]
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219) ~[javafx-graphics-11-linux.jar:na]
	at javafx.concurrent.Task.fireEvent(Task.java:1358) ~[javafx-graphics-11-linux.jar:na]
	at javafx.concurrent.Task.setState(Task.java:725) ~[javafx-graphics-11-linux.jar:na]
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1436) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx-graphics-11-linux.jar:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277) ~[javafx-graphics-11-linux.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by Katharsas** [comment]
@axel1200 
The problem is case sensitivity. The code
```
  public Path getPathForMap(String technicalName) {
    Path path = customMapsDirectory.resolve(technicalName);
    if (Files.notExists(path)) {
      return null;
    }
    return path;
  }
```
in `MapService` returns null because it looks for a folder called
`.faforever/user/My Games/Gas Powered Games/Supreme Commander Forged Alliance/maps/sentina iii.v0001`
but the folder that exists is 
`.faforever/user/My Games/Gas Powered Games/Supreme Commander Forged Alliance/maps/Sentina III.v0001`

So this probably has nothing to do with spaces. So the question is now: Why does this work in 0.10.7 and which change caused the case-sensitivity issue?

**Comment by Katharsas** [comment]
Possibly not a regression, since trying to reproduce in 0.10.7 leads to greyed out `N/A` button instead of `Install` button?
