### ISSUE TITLE
Gradle task downloadNativeDependencies downloads to wrong folder

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1443]
- This task copies native dependencies into `/build/resources/native` whereas the task `gradle bootRun` expects them to be in `/lib`. This means that in an IDE (except IntelliJ?) or when only using gradle without IDE, you need to copy around the native files manually before being able to run the client.

- This task should be a dependency of any task that runs the client (like `bootRun`) so that it doesn't need to be executed manually. (DONE)

**Comment by Katharsas** [comment]
`

**Comment by 1-alex98** [comment]
Well the issue then is it downloads it every time and this takes long as well that it does not work offline. So yes u are right but take into account that these checks need to be done (is the file there already, am I offline)

**Comment by 1-alex98** [comment]
Also these are two issue

**Comment by Katharsas** [comment]
Download:
1. Gradle can mark the task as `Up to Date` if the native files already exits which will prevent unneeded re-execution.
2. The "problem" then is that if the native files get changed on the server, they won't get downloaded automatically. But thats not worse than right now, we already need to run the task manually to update the native files anyway. Solution: Ideally the HTTP request for the download contains some info about the file we already have (if thats the case) so the HTTP response can simply be `304 Not Modified` (either the native download has a creation date as part of filename or hashing is used or ...).

Offline Mode:
If you have no internet, your first build will not work because Gradle will not be able to download all the other dependencies anyway. On subsequent builds, you just use the cached native files like you use cached dependencies (via `Up to Date` functionality in Gradle, see above).

**Comment by Katharsas** [comment]
Btw the fact that native dependencies do not come with version information (does the native code even use versioning?) and can be changed at any time "behind the back" of the client means that technically our builds are not reproducable. If a native file changes in the future, we will no longer be able to reproduce exact behaviour of an older version of the client.

This is a separate issue but kinda related to this one. If we had proper versioning for native dependencies we would know that we only ever need internet to download the files when we change the version we depend on.

To solve that i think our native dependencies should have creation date or version in the file name. Alternativly we could setup a proper repo for those files but thats overkill imo.

**Comment by 1-alex98** [comment]
I mean it was this way before that they were downloaded automatically, but we had the issue that i described above. No offline and run on every task...

**Comment by Katharsas** [comment]
That's just a matter of properly using gradle's functionality to implement the task.

**Comment by 1-alex98** [comment]
yeah

**Comment by Sheikah45** [comment]
Is this still an issue?

**Comment by Sheikah45** [comment]
I don't think so reopen if it is.

**Comment by Katharsas** [comment]
This is still an issue. Eclipse example (but running gradle from cmd will run into the same problem):
<details>
<summary>Expand</summary>
<p>

```
com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "lib/faf-uid.exe": CreateProcess error=2, The system cannot find the file specified
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82)
	at com.faforever.client.remote.FafServerAccessorImpl.lambda$connectAndLogIn$5(FafServerAccessorImpl.java:126)
	at com.faforever.commons.lobby.FafLobbyClient$handle$1.call(FafLobbyClient.kt:169)
	at com.faforever.commons.lobby.FafLobbyClient$handle$1.call(FafLobbyClient.kt:164)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:425)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:542)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:1006)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:425)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:265)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:371)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:381)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Cannot run program "lib/faf-uid.exe": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:591)
	at java.base/java.lang.Runtime.exec(Runtime.java:450)
	at com.faforever.client.os.OsUtils.execAndGetOutput(OsUtils.java:21)
	at com.faforever.client.legacy.WindowsUidService.generate(WindowsUidService.java:20)
	at com.faforever.client.remote.FafServerAccessorImpl.lambda$connectAndLogIn$4(FafServerAccessorImpl.java:126)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100)
	... 44 common frames omitted
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:483)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 51 common frames omitted
```

</p></details>
