### ISSUE TITLE
Incomplete termination of client

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1453]
**Describe the bug**
Client does not terminate but window closes still shown in task manager

**To Reproduce**
Happens approx. every 10th time

**Expected behavior**
Client process closes

**Screenshots**
Responsible is the following thread
```
java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@10.0.2/Native Method)
        - parking to wait for  <0x00000000e2e9db58> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@10.0.2/Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@10.0.2/Unknown Source)
        at java.util.concurrent.LinkedBlockingDeque.takeFirst(java.base@10.0.2/Unknown Source)
        at java.util.concurrent.LinkedBlockingDeque.take(java.base@10.0.2/Unknown Source)
        at sun.nio.fs.AbstractWatchService.take(java.base@10.0.2/Unknown Source)
        at com.faforever.client.map.MapService.lambda$startDirectoryWatcher$7(MapService.java:172)
        at com.faforever.client.map.MapService$$Lambda$618/1056276267.run(Unknown Source)
        at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
        at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
        at com.faforever.client.map.MapService.lambda$startDirectoryWatcher$8(MapService.java:166)
        at com.faforever.client.map.MapService$$Lambda$617/1691552520.run(Unknown Source)
        at java.lang.Thread.run(java.base@10.0.2/Unknown Source)
```

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
In theory the thread should be interrupted from what i read in the code. But it looks like that is not always the case in some edge case, instead of investigating this further and potentially using a lot of time i suggest just make the thread a daemon thread.... There is no reason the client termination should wait for the given file watcher!
