### ISSUE TITLE
Replays in the vault fail to load more often than not

### ISSUE THREAD

**Issue by ShittyReplayVault** [FAForever/downlords-faf-client#1608]
Starting replays (particularly larger team games) from the vault will very often start the game but then give an error and just leave FA on the menu.
The errors given look like this:

java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 'init_fafbeta.lua' could be found.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.lambda$call$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'init_fafbeta.lua' could be found.
	at org.springframework.util.Assert.isTrue(Assert.java:118)
	at com.faforever.client.patch.SimpleHttpFeaturedModUpdaterTask.call(SimpleHttpFeaturedModUpdaterTask.java:83)
	at com.faforever.client.patch.SimpleHttpFeaturedModUpdaterTask.call(SimpleHttpFeaturedModUpdaterTask.java:26)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more

**To Reproduce**
Start a replay from the vault such as this one: "https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11183892"

**Comment by Brutus5000** [comment]
The vault has become sentient. This is how it all starts! 😱

**Comment by 1-alex98** [comment]
![grafik](https://user-images.githubusercontent.com/19996713/75967528-40b27d00-5ecc-11ea-9e2d-ade11bd8a809.png)
Can u give an example of a game with regular faf as well or does it only aplly to faf beta?

**Comment by 1-alex98** [comment]
And I get the same error for your replay

**Comment by 1-alex98** [comment]
The replay u sent has malformatted info in it as it seems the replay file says it is a faf game the server says it is a faf beta game, I cosider that replay file as broken

**Comment by Sheikah45** [comment]
This seems to be based on bad replay data. Also #1866 should fix issues although may still desync
