### ISSUE TITLE
[ Linux ] [ v1.1.9 ] FAF opens links with firefox. always. no matter what.

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1840]
**Describe the bug**
All links clicked within FAF open firefox when on linux build.

I tried running from console to see what it would say when firefox is not installed, it does not even make a new line.

The error.log file did have this : 

```
java.lang.Exception: No web browser found
	at com.sun.javafx.application.HostServicesDelegate$StandaloneHostService.showDocument(HostServicesDelegate.java:146)
	at javafx.application.HostServices.showDocument(HostServices.java:115)
	at com.faforever.client.fx.PlatformService.showDocument(PlatformService.java:42)
	at com.faforever.client.fx.BrowserCallback.openUrl(BrowserCallback.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.webkit.MethodHelper.invoke(MethodHelper.java:83)
	at com.sun.webkit.Utilities.lambda$fwkInvokeWithContext$0(Utilities.java:60)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.webkit.Utilities.fwkInvokeWithContext(Utilities.java:59)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:809)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1008)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$3(WebView.java:1131)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**OS**
Linux

**Comment by 1-alex98** [comment]
I thought I fixed that

**Comment by 1-alex98** [comment]
Oh no I did not

**Comment by 1-alex98** [comment]
Probably using awt is the solution then https://stackoverflow.com/questions/5226212/how-to-open-the-default-webbrowser-using-java

**Comment by tatsujb** [comment]
that should do it yeah.

**Comment by foodlfg** [comment]
on 1.2.0-RC1 i have no issues with it. 
i have Chrome set up as default application in Gnome 3 and the client opens links in Chrome.

**Comment by 1-alex98** [comment]
Maybe cause we update to java 14

**Comment by tatsujb** [comment]
nah I still have this in v1.2.0-RC2 with openjdk 14. 
i'll test oracle jdk/jre and also inside of a VM later. 

I doubt between gnome 3 and gnome 3 with ubuntu mod there lies the diff that causes the bug.

**Comment by foodlfg** [comment]
@tatsujb 
i use PopOS 20.04 (almost Ubuntu)
it has a more native (less modified) Gnome3 than what Ubuntu uses. and the link openings in Chrome work. 

did you select Chrome as the default application in Gnome settings?
https://i.imgur.com/FrLPO3Z.png

**Comment by tatsujb** [comment]
I did.

I think it might be a openjdk vs oracle jdk thing.

**Comment by 1-alex98** [comment]
Could be

**Comment by tatsujb** [comment]
tried with oracle jdk still have it.

**Comment by tatsujb** [comment]
it might just be a vanilla ubuntu-java bug.

**Comment by tatsujb** [comment]
I dunno why but this no longer happens. dunno why :(
