### ISSUE TITLE
mod vault gives me this error when i try to download mods.

### ISSUE THREAD

**Issue by aow-lizardshaman** [FAForever/downlords-faf-client#1847]
**Describe the bug**
from what ive seen this could be that faf is unable to access the mods folder within its location because for some un-known reason win 10 marks folders as read-only not sure though. 

**To Reproduce**
not sure what the steps are for this issue 

This is my log file:java.util.concurrent.CompletionException: java.nio.file.AccessDeniedException: C:\Users\lizardshaman\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\mods\All_Faction_Quantum_Gate\mod_icon.png
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1358)
	at javafx.concurrent.Task.setState(Task.java:709)
	at javafx.concurrent.Task$TaskCallable.lambda$call$2(Task.java:1455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: C:\Users\lizardshaman\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\mods\All_Faction_Quantum_Gate\mod_icon.png
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at com.faforever.commons.io.Unzipper.unzip(Unzipper.java:46)
	at com.faforever.client.mod.InstallModTask.extractMod(InstallModTask.java:104)
	at com.faforever.client.mod.InstallModTask.call(InstallModTask.java:76)
	at com.faforever.client.mod.InstallModTask.call(InstallModTask.java:33)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

**Expected behavior**
i expected to be able to re-download mods as i recently purged my mods folder.

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/28312288/89129360-a9207d00-d4b1-11ea-8cdd-0514f40d4282.png)

**OS**
 Windows 10

**Comment by Brutus5000** [comment]
The access denied error is coming from windows.
Either the file is already there or the client does not have the permissions to write to this folder. Please check if it exists (and if so just delete it once) or if not exist check the permissions of the parent folder (maybe only an admin is allowed to write there)

In some cases it could also be related to OneDrive. There is a dedicated OneDrive workaround switch in the settings.
