### ISSUE TITLE
Exception thrown on Linux Launch

### ISSUE THREAD

**Issue by safield** [FAForever/downlords-faf-client#1857]
Running FAF on Linux Mint 20. FAF is installed through steam. FAF Linux install wiki has been followed. Upon launching FA throgh faf, I get the following exception...

```
java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/home/user/Games/javaFafClient/downlords-faf-client-1.1.2/run" (in directory "/home/user/.faforever/bin"): error=2, No such file or directory
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.faforever.client.fa.relay.ice.IceAdapterImpl.lambda$start$8(IceAdapterImpl.java:229)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/home/user/Games/javaFafClient/downlords-faf-client-1.1.2/run" (in directory "/home/user/.faforever/bin"): error=2, No such file or directory
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82)
	at com.faforever.client.game.GameService.lambda$startGame$41(GameService.java:583)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 4 more
Caused by: java.io.IOException: Cannot run program "/home/user/Games/javaFafClient/downlords-faf-client-1.1.2/run" (in directory "/home/user/.faforever/bin"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.faforever.client.fa.ForgedAllianceService.launch(ForgedAllianceService.java:136)
	at com.faforever.client.fa.ForgedAllianceService.startGame(ForgedAllianceService.java:81)
	at com.faforever.client.game.GameService.lambda$startGame$40(GameService.java:583)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 12 more

```

**Comment by Brutus5000** [comment]
Cannot run program "/home/user/Games/javaFafClient/downlords-faf-client-1.1.2/run" (in directory "/home/user/.faforever/bin")
Seems like you have misconfigured the launch command in the settings.
**Also: Update to the latest version! Bug reports for older versions won't be processed.**

**Comment by safield** [comment]
I have the launch option listed in this guide.

https://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux

Also, I am using the latest version 1.1.9. No clue why the error message list 1.1.2.

**Comment by Brutus5000** [comment]
Can you manually execute the run binary? Is the folder `/home/user/.faforever/bin` existing? Are the permissions setup correctly?

**Comment by 1-alex98** [comment]
You must have missed the "Copy the Steam RUN script" step

**Comment by 1-alex98** [comment]
The wiki just uses the 1.1.2 as a name in the directory name is should have no effect

**Comment by 1-alex98** [comment]
The /home/user/Games/javaFafClient/downlords-faf-client-1.1.2/run files does not exist!!! So you did not successfully copy it over `cp /tmp/proton_test1/run ~/Games/javaFafClient/downlords-faf-client-1.1.2/` Either there was no `/tmp/proton_test1/run ` or u missed out on it
