### ISSUE TITLE
[Linux] 1.2.0 crashes on startup, openjdk 14.0.2+12

### ISSUE THREAD

**Issue by foodlfg** [FAForever/downlords-faf-client#1883]
**Describe the bug**
Java with the Client 1.2.0 crashes on startup on Majaro Linux. Fatal error.
```
JRE version: OpenJDK Runtime Environment (14.0.2+12) (build 14.0.2+12)
Java VM: OpenJDK 64-Bit Server VM (14.0.2+12, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
```

Only one user reported this (BlackYps#2718 on discord).
1.1.9 works for him with Java 11.

**To Reproduce**
Start the client : )

**Log or error message**
This is the log file: 
[hs_err_pid18854.log](https://github.com/FAForever/downlords-faf-client/files/5170659/hs_err_pid18854.log)

**OS**
Linux

**Comment by foodlfg** [comment]
It is working for me on Ubuntu btw with 
```
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)
```

**Comment by 1-alex98** [comment]
this normally happens if u got 2 clients open on linux. Tell him to restart PC and try again. Btw @BlackYps contributes  to the client himself XD I know him

**Comment by tneo** [comment]
I have the same issue. Restarted pc and populates the error message:

`java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationListener : org.springframework.boot.cloud.CloudFoundryVcapEnvironmentPostProcessor
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:437)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:419)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:269)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:249)
	at org.springframework.boot.builder.SpringApplicationBuilder.createSpringApplication(SpringApplicationBuilder.java:104)
	at org.springframework.boot.builder.SpringApplicationBuilder.<init>(SpringApplicationBuilder.java:92)
	at com.faforever.client.FafClientApplication.init(FafClientApplication.java:94)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	... 2 more
Caused by: java.lang.IllegalArgumentException: class org.springframework.boot.cloud.CloudFoundryVcapEnvironmentPostProcessor is not assignable to interface org.springframework.context.ApplicationListener
	at org.springframework.util.Assert.assignableCheckFailed(Assert.java:673)
	at org.springframework.util.Assert.isAssignable(Assert.java:604)
	at org.springframework.util.Assert.isAssignable(Assert.java:635)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:431)
	... 10 more
`
Used JDK version:
`openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-suse-1.2-x8664)
OpenJDK 64-Bit Server VM (build 14.0.2+12-suse-1.2-x8664, mixed mode)
`

Downgraded back to 1.1.19

**Comment by 1-alex98** [comment]
This is certainly not the same issue @tneo

**Comment by 1-alex98** [comment]
Concerning theo's issue it says https://stackoverflow.com/questions/35844263/run-spring-boot-application-error-cannot-instantiate-interface-org-springframew we might have a version missmatch somewhere

**Comment by 1-alex98** [comment]
@tneo are u even on linux?

**Comment by 1-alex98** [comment]
> Concerning theo's issue it says https://stackoverflow.com/questions/35844263/run-spring-boot-application-error-cannot-instantiate-interface-org-springframew we might have a version missmatch somewhere

Reading the build.gradle it seems like that is not the case tho.

**Comment by 1-alex98** [comment]
If you are on windows @tneo reinstall it might be that there is some old file that is left over in an old version that tends to happen(which is sad but that is a problem of the installer which we can do little about)

**Comment by tneo** [comment]
I'm on Linux :-)
`fafclient_1_2_0> uname -a
Linux myOs 5.8.4-1-default #1 SMP Wed Aug 26 10:53:09 UTC 2020 (64fe492) x86_64 x86_64 x86_64 GNU/Linux
`
I was able to launch by extracting the tar file to a fresh location, whereas previously I just overwrote the 1.19 location.

**Comment by 1-alex98** [comment]
that makes sense you know what must have heppend ;) old files were not deleted and there were old files with old version there...

**Comment by 1-alex98** [comment]
I am sure BlackYPs had two clients opened at the same time

**Comment by BlackYps** [comment]
I only had one client open. I fixed the issue by using the OpenJDK Oracle build from the AUR instead.
