### ISSUE TITLE
Error accessing replays in the vault

### ISSUE THREAD

**Issue by Gy1e** [FAForever/downlords-faf-client#1901]
I search for replays with values "One of the player's global ratings" "is greater than" "1500" 

I get the same errors or very similar ones with every variable i seem to enter in the vaults search functions.

I get the following error message,

java.util.concurrent.CompletionException: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"errors":["InvalidValueException: Invalid value: Combination of pagination, sorting over relationship and filtering over toMany relationships unsupported"]}]
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:279)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"errors":["InvalidValueException: Invalid value: Combination of pagination, sorting over relationship and filtering over toMany relationships unsupported"]}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:177)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:132)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:315)
	at com.faforever.client.api.FafApiAccessorImpl.getPageWithMeta(FafApiAccessorImpl.java:652)
	at com.faforever.client.api.FafApiAccessorImpl.getPageWithMeta(FafApiAccessorImpl.java:627)
	at com.faforever.client.api.FafApiAccessorImpl.findReplaysByQueryWithMeta(FafApiAccessorImpl.java:336)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy69.findReplaysByQueryWithMeta(Unknown Source)
	at com.faforever.client.remote.FafService.findReplaysByQueryWithPageCount(FafService.java:320)
	at com.faforever.client.remote.FafService$$FastClassBySpringCGLIB$$6c91c77e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	... 4 more

![Screenshot (169)](https://user-images.githubusercontent.com/71211396/93014673-d715d880-f5aa-11ea-8299-b20dcaf08bfe.png)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Seems like we broke that by implementing pagination. This is probably gonna be hard to fix. Elide just does not support it. Maybe we need to disable pagination for those relationship but that seems still unsatisfactory.

**Comment by 1-alex98** [comment]
@bukajsytlos @Brutus5000  u know if https://elide.io 5 will support this?

**Comment by bukajsytlos** [comment]
this is my contribution to Elide😊. This is not supported by sql so there is no way around it. you need distinct when joining toMany otherwise pagination is broken. and you cant sort over fields you are not selecting when distinct is used. so unfortunately as the error says this combination is not supported.

**Comment by 1-alex98** [comment]
Now I am confused. So what does this mean for us? What do we need to do? Or what can we not do? 

I saw your contribution but I thought is is gonna fix the wrong page count.

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/93072365-91780f00-f681-11ea-9186-951574888438.png)
Nice we are having a conversation in the future XD

**Comment by bukajsytlos** [comment]
this is it https://github.com/yahoo/elide/pull/1254/files
Well I guess there are only two options.
1. disable this kind of combination in UI
2. make error from API "nicer"

**Comment by 1-alex98** [comment]
What do u think is best? Disable the sort? But then you get fucking old games right?

**Comment by 1-alex98** [comment]
on the other hand then you can jump to the end with pagination

**Comment by 1-alex98** [comment]
I mean you could filter x started before 2019 or something

**Comment by 1-alex98** [comment]
@Gy1e if you need this for searching replays to cast you can go back to the version before. This is probably take some time to fix. Otherwise all searches going over toMany relationships seem to have broken. This is probably almost all searches

**Comment by Gy1e** [comment]
understood, thanks fellas. how do i roll back the update?

**Comment by bukajsytlos** [comment]
you can sort on fields of the main entity (game I guess in case of replays)

**Comment by 1-alex98** [comment]
Go to the releases on github and install whatever version you like. You can find the releases on the right site in the "Code" tab.

**Comment by bukajsytlos** [comment]
what have changed in the client? there was no pagination till now?

**Comment by Brutus5000** [comment]
In theory you don't need to perform server side pagination. You can fetch the complete result, keep it in background and do ui based pagination on your cached result.

**Comment by 1-alex98** [comment]
I guess so. I mean there was kind of, be asked for pageNum before

**Comment by 1-alex98** [comment]
Before we had pageSize and pageNum set or whatever they are called and now we also have pageTotals

**Comment by bukajsytlos** [comment]
but this only changed the way the response from server is handled, right? request is still the same, so I think downgrading client would not help, but I may be missing something

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/93077872-c5efc900-f689-11ea-9730-4ec239be2ec1.png)
I can make the query without problems lol

**Comment by bukajsytlos** [comment]
you have sorted over start time, @Gy1e over max players (this is probably joined attribute)

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/93078130-40b8e400-f68a-11ea-8539-30cd4b92c9fd.png)

**Comment by 1-alex98** [comment]
Yes it is, it comes from the map. Is sorting with joint attributes not possible?

**Comment by 1-alex98** [comment]
Now I get the error 
![image](https://user-images.githubusercontent.com/19996713/93078230-6f36bf00-f68a-11ea-9d55-8be179b8fe69.png)

**Comment by bukajsytlos** [comment]
https://blog.jooq.org/2018/07/13/how-sql-distinct-and-order-by-are-related/

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/93081757-0d795380-f690-11ea-952c-56d30d342013.png)

**Comment by 1-alex98** [comment]
@Gy1e seems you can keep using/update to 1.2.0 but u need to be careful not all options for sorting work but I think it should be the same in earlier versions.

**Comment by bukajsytlos** [comment]
just to be sure, you can sort on whatever you want if it is not in combination with toMany filtering

**Comment by 1-alex98** [comment]
Well i think filtering is more important and we already have a sortable boolean, I say we just update sortable boolean to be false for all too many Relationships

**Comment by 1-alex98** [comment]
In SearchablePropertyMappings set all sortable properties to false if it includes toMany relationship

**Comment by 1-alex98** [comment]
Interesting that seems to already be the case

**Comment by 1-alex98** [comment]
@Gy1e sorted by mapVersion.maxPlayers which is not a toMany relationship right?

**Comment by 1-alex98** [comment]
Oh wait all joined attributes can not be filtered you say?

**Comment by 1-alex98** [comment]
@bukajsytlos like that?

**Comment by bukajsytlos** [comment]
no, 
`I search for replays with values "One of the player's global ratings" "is greater than" "1500"` => toMany join for filtering purpose
`sort by max players` join due to sorting
this combination is forbidden.
But you can filter on toMany relationships if you do not sort on joined attributes (ie. sort on "createdAt")
You can sort on joined attributes if you do not filter on toMany relationships

**Comment by 1-alex98** [comment]
Man that would need some serious extra logic, so I suggest we use the PR above and just restrict sorting

**Comment by bukajsytlos** [comment]
or just handle that error in user friendly way.
and api should send it nicer way too
