### ISSUE TITLE
User list empty chat

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1925]
**Describe the bug**
On startup chat user list stays empty

**To Reproduce**
Probably a race condition

**Log or error message**
This is my log file:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.collections.ObservableListWrapper.removeAll(ObservableListWrapper.java:173)
	at com.faforever.client.chat.ChannelTabController.lambda$onUserLeft$37(ChannelTabController.java:554)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
**Expected behavior**
The chat controllers are loaded before these kind of events.

**OS**
Linux or Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Have not seen this recently
