### ISSUE TITLE
Startup Error - Versions 1.2.0, 1.2.1 & 1.2.2 tried

### ISSUE THREAD

**Issue by Archine-1** [FAForever/downlords-faf-client#2002]
Hi all, So on first boot up of my client (it was version 1.2.1 at the time) it worked fine, checked out the co-op campaign and booted one up (convinced a mate to join me so was doing some legwork to check how it all works).

Came back the next day and the below error message appeared when I tried to boot up the client. It has been the same (I'm eyeballing it admittedly, but checking a few the values they appear the same. The below copy paste is just now, and the attachment was yesterday on different installs and I *think* they are identical)

The three versions above tried and a delete and reinstall of SC: FA itself (just in case)

**To Reproduce**
Boot up from desktop of the client

**Log or error message**
This is my log file:
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: no glass in java.library.path: [.]
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:268)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.UnsatisfiedLinkError: no glass in java.library.path: [.]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:110)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:118)
	at com.sun.glass.ui.win.WinApplication.access$300(WinApplication.java:39)
	at com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:101)
	at com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:82)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.sun.glass.ui.win.WinApplication.<clinit>(WinApplication.java:82)
	at com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:39)
	at com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:36)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	... 6 more

[NOTE - that '... 6 more' does not expand or change by the look of it so I don't know what the six are!]
[FAF issue.txt](https://github.com/FAForever/downlords-faf-client/files/5408590/FAF.issue.txt)

**OS** Windows 64

**Comment by 1-alex98** [comment]
Have you tried uninstalling? Instead of overwriting the current application

**Comment by 1-alex98** [comment]
Maybe removing other Java installations from the PATH variable might help

**Comment by Archine-1** [comment]
Full uninstalled both the client and the game on Steam. Not sure on removing other Java Installations? How do I do that?

**Comment by 1-alex98** [comment]
https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/ remove java installation from PATH

**Comment by Archine-1** [comment]
Legend, seems to have worked. I'll run something later. Boot off  and try again tomorrow to confirm. Thanks!

**Comment by 1-alex98** [comment]
What fixed it?

**Comment by Archine-1** [comment]
Removing the Java Variables. Just tried again after I finished work and seems to have stuck as a fix. Thanks Axel. Happy to have it working now.
