### ISSUE TITLE
Game crash ~45-55 minute mark

### ISSUE THREAD

**Issue by chreman** [FAForever/downlords-faf-client#2045]
**Describe the bug**
Everything works perfect until it doesn't. At a certain point, which is not connected to any specific in-game action or event, the screen freezes, with sound effects looping from the point of freezing. Mousemovement is still possible but clicking has no effect.

I followed the instructions from here https://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux about performance issues and crashes, and the problems occurred without minimap and without splitscreen. DXVK_HUD=1 shows Vulkan 1.2.133

**To Reproduce**
* Unfortunately, I know of no specific way to reproduce it other than playing the game.

**Log or error message**

From the client:
```
2020-11-24 02:08:49.974  WARN 360526 --- [      JJsonPeer] c.f.client.fa.relay.GpgClientCommand     : Unknown lobby action: EnforceRating






^Cit.lua: ../nptl/pthread_mutex_lock.c:438: __pthread_mutex_lock_full: Assertion `robust || (oldval & FUTEX_OWNER_DIED) == 0' failed.
2020-11-24 02:23:12.435  WARN 360526 --- [extShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'pircBotXChatService': java.lang.IllegalArgumentException: Not connected to server
2020-11-24 02:23:12.435 ERROR 360526 --- [pool-3-thread-3] org.pircbotx.PircBotX                    : Exception encountered during connect

java.lang.RuntimeException: Cannot shutdown listener com.faforever.client.chat.PircBotXChatService$$Lambda$1437/0x00000008014a7c40@e29c03b executing event DisconnectEvent(userChannelDaoSnapshot=org.pircbotx.snapshot.UserChannelDaoSnapshot@13c23756, disconnectException=null)
	at org.pircbotx.hooks.managers.ThreadedListenerManager.shutdown(ThreadedListenerManager.java:139)
	at org.pircbotx.PircBotX.shutdown(PircBotX.java:636)
	at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:356)
	at org.pircbotx.PircBotX.connect(PircBotX.java:339)
	at org.pircbotx.PircBotX.startBot(PircBotX.java:187)
	at com.faforever.client.chat.PircBotXChatService$1.call(PircBotXChatService.java:473)
	at com.faforever.client.chat.PircBotXChatService$1.call(PircBotXChatService.java:465)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at org.pircbotx.hooks.managers.ThreadedListenerManager.shutdown(ThreadedListenerManager.java:137)
	... 11 common frames omitted

2020-11-24 02:23:12.449  INFO 360526 --- [extShutdownHook] com.faforever.client.config.AsyncConfig  : Shutting down ExecutorService 'taskExecutor'
2020-11-24 02:23:12.450  WARN 360526 --- [ool-3-thread-10] com.faforever.client.game.GameService    : Error during post-game processing

java.lang.InterruptedException: null
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:321)
	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:474)
	at com.faforever.client.game.GameService.lambda$spawnTerminationListener$45(GameService.java:661)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

2020-11-24 02:23:12.451  INFO 360526 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
```
From error.log:
```
Exception in thread "Thread-13" com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:295)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer.play(NativeMediaAudioClipPlayer.java:319)
	at com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer.clipScheduler(NativeMediaAudioClipPlayer.java:112)
	at com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer.access$000(NativeMediaAudioClipPlayer.java:47)
	at com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer$Enthreaderator.lambda$static$0(NativeMediaAudioClipPlayer.java:85)
	at java.base/java.lang.Thread.run(Thread.java:832)
Exception in thread "pool-3-thread-11" com.github.nocatch.NoCatchException: java.lang.InterruptedException: sleep interrupted
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.fa.OnGameFullNotifier.lambda$onGameFull$1(OnGameFullNotifier.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.faforever.client.fa.OnGameFullNotifier.lambda$onGameFull$0(OnGameFullNotifier.java:71)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
```
from ForgedAlliance_d3d9.log
```
info:  Game: ForgedAlliance.exe
info:  DXVK: v1.7-8-g51531e4a7
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to initialize OpenVR
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 1080 Ti:
info:    Driver: 450.80.2
info:    Vulkan: 1.2.133
info:    Memory Heap[0]: 
info:      Size: 11264 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 36115 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 1080 Ti:
info:    Driver: 450.80.2
info:    Vulkan: 1.2.133
info:    Memory Heap[0]: 
info:      Size: 11264 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 36115 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : GeForce GTX 1080 Ti
info:    Driver version   : 450.80.2
info:  Enabled device extensions:
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:  DXVK: Read 530 valid state cache entries
info:  DXVK: Using 7 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  2
info:    Exclusive FS: 0
info:  Setting display mode: 1920x1080@60
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_X
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_Y
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_W
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  2
info:    Exclusive FS: 0
```

**Expected behavior**

**Screenshots**

**OS**
Linux (Ubuntu 20.04), Proton 5.0-10, Client 1.2.3

GTX 1080 Ti

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
This is the repository for the client. Your problem is pretty obviously a game issue hence this issue is in the wrong place. Please close the issue and open it in the FA repository instead.
