### ISSUE TITLE
Cant start application after update

### ISSUE THREAD

**Issue by opengs** [FAForever/downlords-faf-client#2160]
**Describe the bug**
Application fails to start with exeption

**To Reproduce**
jdk-15.0.2
I tried v1.3 and v1.4 and both dont work for me

**Log or error message**
```
16:07:25.374 [main] DEBUG com.faforever.client.preferences.PreferencesService - Logger initialized
16:07:26.007 [JavaFX-Launcher] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: unknown
16:07:26.021 [JavaFX-Launcher] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: ConfigFileApplicationListener [org.springframework.boot.context.config.ConfigFileApplicationListener] is deprecated and can only be used as an EnvironmentPostProcessor
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:198)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:203)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:196)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:170)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:148)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144)
	at com.faforever.client.FafClientApplication.init(FafClientApplication.java:110)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**OS**
Ubuntu 18.04.5

**Comment by micheljung** [comment]
The client comes with its own JDK so 15.0.2 should be irrelevant. If for some reason however this interferes, which I can't tell from the log, that could (but is unlikely, from the logs) be an issue.

A more likely possibility is that there are files from previous versions (maybe an RC?) that didn't get uninstalled properly so you could try uninstalling the client, make sure that its installation directory is actually empty (delete files manually if it's not) and try installing it again.

**Comment by cdglitch** [comment]
Installed the 1.4.2 update today and the launcher is completely borked for me no matter what I try :(

```
java.lang.RuntimeException: Exception in Application init method
	  at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	  at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	  at java.base/java.lang.Thread.run(Thread.java:832)
  Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8080 is already in use
	  at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	  at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	  at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	  at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	  at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:942)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144)
	  at com.faforever.client.FafClientApplication.init(FafClientApplication.java:110)
	  at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	  ... 2 more
  Caused by: org.springframework.boot.web.server.PortInUseException: Port 8080 is already in use
	  at org.springframework.boot.web.server.PortInUseException.lambda$throwIfPortBindingException$0(PortInUseException.java:70)
	  at org.springframework.boot.web.server.PortInUseException.lambda$ifPortBindingException$1(PortInUseException.java:85)
	  at org.springframework.boot.web.server.PortInUseException.ifCausedBy(PortInUseException.java:103)
	  at org.springframework.boot.web.server.PortInUseException.ifPortBindingException(PortInUseException.java:82)
	  at org.springframework.boot.web.server.PortInUseException.throwIfPortBindingException(PortInUseException.java:69)
	  at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:228)
	  at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)
	  at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	  ... 17 more
  Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
	  at org.apache.catalina.core.StandardService.addConnector(StandardService.java:231)
	  at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)
	  at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
	  ... 19 more
  Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	  at org.apache.catalina.connector.Connector.startInternal(Connector.java:1067)
	  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	  at org.apache.catalina.core.StandardService.addConnector(StandardService.java:227)
	  ... 21 more
  Caused by: java.net.BindException: Address already in use: bind
	  at java.base/sun.nio.ch.Net.bind0(Native Method)
	  at java.base/sun.nio.ch.Net.bind(Net.java:550)
	  at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:249)
	  at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
	  at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:228)
	  at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:211)
	  at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1141)
	  at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1227)
	  at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:592)
	  at org.apache.catalina.connector.Connector.startInternal(Connector.java:1064)
	  ... 23 more
```


This is on 8.1 build 9600

**Comment by cdglitch** [comment]
After some testing, it seems like everything after 1.4.0 is broken in the same way for me. I tried all the 1.4.1 versions including the RCs and no dice.

**Comment by Brutus5000** [comment]
#2170 fixes this. Workaround in the meantime: Make sure no other application runs on port 8080.

**Comment by Mimic0445** [comment]
How to make sure no other application is running on port 8080:
![image](https://user-images.githubusercontent.com/18315545/109401766-2e6bf300-7916-11eb-8cd0-22738048807e.png)

**Comment by cdglitch** [comment]
In my case, it was a service part of the National Instruments shared components for labview. Now theres nothing running on :8080 it just dies this death instead:


```
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.github.nocatch.NoCatchException: javafx.fxml.LoadException: 
file:/C:/Program%20Files/Downlord's%20FAF%20Client/lib/downlords-faf-client-1.4.2.jar!/theme/statusbar/status_bar.fxml:13
file:/C:/Program%20Files/Downlord's%20FAF%20Client/lib/downlords-faf-client-1.4.2.jar!/theme/main.fxml:106

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.theme.UiService.loadFxml(UiService.java:420)
	at com.faforever.client.theme.UiService$$FastClassBySpringCGLIB$$2b0b2208.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.faforever.client.theme.UiService$$EnhancerBySpringCGLIB$$d29e5a31.loadFxml(<generated>)
	at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:138)
	at com.faforever.client.FafClientApplication.start(FafClientApplication.java:122)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
Caused by: javafx.fxml.LoadException: 
file:/C:/Program%20Files/Downlord's%20FAF%20Client/lib/downlords-faf-client-1.4.2.jar!/theme/statusbar/status_bar.fxml:13
file:/C:/Program%20Files/Downlord's%20FAF%20Client/lib/downlords-faf-client-1.4.2.jar!/theme/main.fxml:106

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2685)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1156)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:756)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2808)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2634)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2517)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	... 17 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'statusBarController' defined in URL [jar:file:/C:/Program%20Files/Downlord's%20FAF%20Client/lib/downlords-faf-client-1.4.2.jar!/com/faforever/client/ui/statusbar/StatusBarController.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.faforever.client.chat.ChatService' available: expected single matching bean but found 2: kittehChatService,pircBotXChatService
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1206)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1235)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1179)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:940)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:982)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:229)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2808)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2634)
	... 25 more
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.faforever.client.chat.ChatService' available: expected single matching bean but found 2: kittehChatService,pircBotXChatService
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1345)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 43 more
```

**Comment by Brutus5000** [comment]
Classic case of the installer didn't wipe the old version properly. Please uninstall, manually delete remaining files and reinstall.

Is it possible that you updated, while the FAF client was still running?

**Comment by Sheikah45** [comment]
@Brutus5000 I know this is the case with people who updated who helped test tmm as there was a jar that had to be manually placed in the install folder and if it isnt removed there is namespace collision
