### ISSUE TITLE
When did the client start using port 8080?

### ISSUE THREAD

**Issue by dev-nulled** [FAForever/downlords-faf-client#2173]
**Describe the bug**
Seems the new FAF client is using port 8080.  Great if nothing else is, but for those of us who do Springboot coding on the same computer, this means one has to change.  (and this is the default port for us devs)

**To Reproduce**
Fire up anything that uses port 8080 locally and the client throws an exception launching.

**Log or error message**
Web server failed to start. Port 8080 was already in use.

```
java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8080 is already in use
```

**Expected behavior**
Either not use port 8080, or provide a way to set that port.

**Screenshots**

![startup](https://user-images.githubusercontent.com/47699221/109401450-7427bc00-7914-11eb-8fd6-317564abd241.png)

Linux or Windows
(yes)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
fixed in #2170
