### ISSUE TITLE
Preferences file could not be read

### ISSUE THREAD

**Issue by dhardy** [FAForever/downlords-faf-client#2244]
**Describe the bug**
On first start (or after deleting `client.prefs`), the client starts as expected. On subsequent starts (whether or not any settings have been changed in the UI), the game fails to start with the following log message:
```
2021-05-20 17:40:53.727  WARN 252182 --- [JavaFX-Launcher] c.f.c.preferences.PreferencesService     : Preferences file /home/dhardy/.faforever/client.prefs could not be read

java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.net.HttpCookie.name accessible: module java.base does not "opens java.net" to unnamed module @470e2030
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.google.gson.Gson.fromJson(Gson.java:994)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at com.faforever.client.preferences.gson.PropertyTypeAdapter.deserialize(PropertyTypeAdapter.java:123)
	at com.faforever.client.preferences.gson.PropertyTypeAdapter.deserialize(PropertyTypeAdapter.java:41)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:865)
	at com.faforever.client.preferences.PreferencesService.readExistingFile(PreferencesService.java:254)
	at com.faforever.client.preferences.PreferencesService.afterPropertiesSet(PreferencesService.java:173)
```
That doesn't sound like an error in the preferences file to me?

Other than that the client seems to work okay (able to launch games).

**To Reproduce**
Installed on Fedora Linux as per [instructions](https://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux#Java_Downlord.27s_Client) (except using openjdk 16 from Fedora packages, which I have successfully used in the past).

**OS**
Fedora Linux 34

**Comment by dhardy** [comment]
It turns out the `prefs` file ended eight lines short (line 125 of 133). Adding `}`  to the end was enough to make the client start.

No idea why this happened (repeatedly), but I might as well close this.

**Comment by dhardy** [comment]
This is not solved. Usually the lua file is syntactically valid but still fails to load, as above.

**Comment by Brutus5000** [comment]
We encountered the same if we run the client on Java 16. Are you sure you run on java 15 ?

**Comment by Sheikah45** [comment]
Brutus beat me to asking about the java version

**Comment by dhardy** [comment]
Yes, running on Java 16.

**Comment by Sheikah45** [comment]
Yes then you need to run with java 15 as we are not yet compatible with java 16

**Comment by dhardy** [comment]
Aha, thanks.
