### ISSUE TITLE
GetResource: Invalid name

### ISSUE THREAD

**Issue by metaben** [FAForever/downlords-faf-client#2273]
45 mins into a game with friends and two AIx Sorian, the game hung with no error. The game had to be killed with task manager. The map was mezmerizing_paradise_betav2.v0002. We're not sure if this is mods or FAFclient (eg. Restrictions). Thanks for all your hard work!

**Mods:**
"RK's Explosions" mod
"Graphicenhancement mod v1.1" mod
"Total Mayhem" mod

**Restrictions:**
info: RestrictedCategories    1 = "NUKENAVAL"
info: RestrictedCategories    2 = "NUKET3DEF"
info: RestrictedCategories    3 = "NUKET3ML"
info: RestrictedCategories    4 = "NUKET4ML"
info: RestrictedCategories    5 = "BILLY"

**Platform:** Win 10 and FAFclient 1.4.6

**Replay:** 53min 41s replay exists (96k) but disabled/won't play in client

{"host":"beeej","uid":14704492,"title":"electricdeath","mapname":"mezmerizing_paradise_betav2.v0002","state":"closed","game_type":"unknown","featured_mod":"faf","max_players":10,"num_players":3,"sim_mods":{"GRAPHICE-NHAN-CEME-NT01-000000000000":"Graphicenhancement mod v1.1","62e2j64a-TOMA-3652-01370-146as555a8u3":"Total Mayhem","90312bd2-6fbd-4aa6-874e-rksbooms-v12":"RK's Explosions"},"teams":{"2":["beeej","Amethi","brit"]},"featured_mod_versions":{},"complete":true,"recorder":"beeej","version_info":{"lobby":"dfaf-1.4.6"},"game_end":1.623529493E9,"game_time":0.0,"launched_at":1.623526877E9}

**Extract from client.log:**

2021-06-12 21:26:05.741  INFO 2540 --- [Thread-977] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [C:\ProgramData\FAForever\bin\ForgedAlliance.exe, /init, init.lua, /nobugreport, /log, C:\ProgramData\FAForever\logs\game_14704903.log, /gpgnet, 127.0.0.1:41790, /mean, 1500.0, /deviation, 500.0, /savereplay, gpgnet://127.0.0.1:62977/14704903/beeej.SCFAreplay, /country, GB, /numgames, 0] in directory: C:\ProgramData\FAForever\bin
2021-06-12 21:59:08.940  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:08.941  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:08.958  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:08.958  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:08.959  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:19.981  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:19.982  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:19.982  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:24.011  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:24.011  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:24.031  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:24.031  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:24.031  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:49.995  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:49.995  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:50.011  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:50.012  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 21:59:50.012  WARN 2540 --- [JavaFX Application Thread] c.faforever.client.coop.CoopController   : No coop mission found for folder name: x1ca_coop_001
2021-06-12 22:22:18.837  WARN 2540 --- [Thread-976] c.f.client.replay.ReplayServerImpl       : Error while recording replay

java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:981)
	at java.base/java.io.InputStream.read(InputStream.java:218)
	at com.faforever.client.replay.ReplayServerImpl.recordAndRelay(ReplayServerImpl.java:146)
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:99)
	at java.base/java.lang.Thread.run(Thread.java:832)

2021-06-12 22:22:18.838  WARN 2540 --- [Thread-976] c.f.client.replay.ReplayServerImpl       : Error in replay server

java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:981)
	at java.base/java.io.InputStream.read(InputStream.java:218)
	at com.faforever.client.replay.ReplayServerImpl.recordAndRelay(ReplayServerImpl.java:146)
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:99)
	at java.base/java.lang.Thread.run(Thread.java:832)

2021-06-12 22:22:18.960  INFO 2540 --- [pool-3-thread-22] com.faforever.client.game.GameService    : Forged Alliance terminated with exit code 1
2021-06-12 22:22:19.205  INFO 2540 --- [Thread-977] c.f.client.fa.relay.ice.IceAdapterImpl   : ICE adapter terminated normally
2021-06-12 22:23:06.396  INFO 2540 --- [Discord RPC] c.f.client.discord.DiscordEventHandler   : Discord disconnected with code '1' and message 'Pipe closed'
2021-06-12 22:23:08.136  WARN 2540 --- [JavaFX Application Thread] c.f.client.fa.relay.ice.IceAdapterImpl   : Ignoring call to ICE adapter as we are not connected: quit([])
2021-06-12 22:23:08.141  INFO 2540 --- [JavaFX Application Thread] com.faforever.client.config.AsyncConfig  : Shutting down ExecutorService 'taskExecutor'
2021-06-12 22:23:08.142  INFO 2540 --- [JavaFX Application Thread] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'

**Extract from game.log:**

debug: Current gametime: 00:37:30
debug: Current gametime: 00:38:00
debug: Current gametime: 00:38:30
debug: Loading module '\000/projectiles/cifprotonbomb01/cifprotonbomb01_script.lua\000'
debug: Loading module '\000/effects/entities/effectprotonambient01/effectprotonambient01_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/units/brnt3shpd/brnt3shpd_script.lua\000'
debug: Loading module '\000/units/ueb0303/ueb0303_script.lua\000'
debug: Loading module '\000/units/uel0301/uel0301_script.lua\000'
debug: Current gametime: 00:39:00
debug: Loading module '\000/mods/totalmayhem/units/brnbt1hart/brnbt1hart_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/projectiles/brnt3shpdproj/brnt3shpdproj_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/projectiles/brnt3shbmnewrl2aproj/brnt3shbmnewrl2aproj_script.lua\000'
debug: Current gametime: 00:39:30
warning: Error running lua script: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3759): Game object has been destroyed
         stack traceback:
         	[C]: in function `PlaySound'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3759): in function `PlayUnitSound'
         	...ed alliance\mods\rks_explosions\lua\sdexplosions.lua(227): in function <...ed alliance\mods\rks_explosions\lua\sdexplosions.lua:219>
warning: Error running lua script: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3759): Game object has been destroyed
         stack traceback:
         	[C]: in function `PlaySound'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3759): in function `PlayUnitSound'
         	...ed alliance\mods\rks_explosions\lua\sdexplosions.lua(227): in function <...ed alliance\mods\rks_explosions\lua\sdexplosions.lua:219>
debug: Current gametime: 00:40:00
debug: Current gametime: 00:40:30
debug: Loading module '\000/units/ueb2304/ueb2304_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/units/brmt3advbtbot/brmt3advbtbot_script.lua\000'
debug: Total Mayhem: Injecting BuilderGroups
debug: Total Mayhem: Injecting FormerGroups
debug: Loading module '\000/mods/totalmayhem/units/brmt3pd/brmt3pd_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/units/brnt3pdro/brnt3pdro_script.lua\000'
debug: Current gametime: 00:41:00
debug: Current gametime: 00:41:30
debug: Loading module '\000/projectiles/tifsmallyieldnuclearbomb01/tifsmallyieldnuclearbomb01_script.lua\000'
debug: Current gametime: 00:42:00
debug: Loading module '\000/units/xrb3301/xrb3301_script.lua\000'
debug: Current gametime: 00:42:30
debug: Current gametime: 00:43:00
debug: Loading module '\000/units/ueb2101/ueb2101_script.lua\000'
debug: Loading module '\000/units/uab1301/uab1301_script.lua\000'
debug: Loading module '\000/projectiles/cdfrocketiridium01/cdfrocketiridium01_script.lua\000'
debug: Loading module '\000/projectiles/cdfbolter03/cdfbolter03_script.lua\000'
debug: Current gametime: 00:43:30
debug: Loading module '\000/mods/totalmayhem/units/brnt3ow/brnt3ow_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/projectiles/brmt1advbotrlproj/brmt1advbotrlproj_script.lua\000'
debug: Loading module '\000/mods/rks_explosions/effects/entities/sr_debris/sr_debris_script.lua\000'
debug: Current gametime: 00:44:00
debug: Loading module '\000/mods/totalmayhem/projectiles/brmt1hvyproj/brmt1hvyproj_script.lua\000'
debug: Loading module '\000/units/uab3104/uab3104_script.lua\000'
debug: *AIExecuteBuildStructure: We cant decide whatToBuild! AI-faction: CYBRAN, Building Type: "T3StrategicMissileDefense", engineer-faction: "CYBRAN"
debug: *AIExecuteBuildStructure: Found template: "T3StrategicMissileDefense" - Using UnitID: "urb4302"
debug: *AIExecuteBuildStructure: Need engineer with Techlevel (3) for BuildUnitWithID: "urb4302"
debug: *AIExecuteBuildStructure: Engineer ("url0309") has Techlevel (3)
debug: *AIExecuteBuildStructure: Engineer with Techlevel (3) can build TECH3 BuildUnitWithID: "urb4302"
debug: *AIExecuteBuildStructure: AI-faction: CYBRAN, Engineer with faction (CYBRAN) can build faction (CYBRAN) - BuildUnitWithID: "urb4302"
warning: *AIExecuteBuildStructure: Unit is Restricted!!! Building Type: "T3StrategicMissileDefense", faction: "CYBRAN" - Unit:urb4302
debug: Loading module '\000/effects/entities/debrisboneattachlow01/debrisboneattachlow01_script.lua\000'
debug: Loading module '\000/lua/genericdebris.lua\000'
debug: Current gametime: 00:44:30
debug: Loading module '\000/units/url0402/url0402_script.lua\000'
info: Hooked /units/url0402/url0402_script.lua with /mods/rks_explosions/hook/units/url0402/url0402_script.lua
debug: Current gametime: 00:45:00
debug: Loading module '\000/mods/totalmayhem/units/brot3shpd/brot3shpd_script.lua\000'
debug: Loading module '\000/lua/seraphimweapons.lua\000'
debug: Loading module '\000/lua/defaultbufffield.lua\000'
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
warning: Connection dialogue opening due to disconnection by players:
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: send Ptr: 1AF20002 
info: ren_oblivion true
info: ren_ui false
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: send Ptr: EEC10002 
info: SafeQuit sync timed out.

**Comment by Sheikah45** [comment]
This is not a client issue, this is an fa game issue. You can post this in the technical help discord. However since you are running with a mod some big there is most likely the cause. 

As fir the replay it looks like you just lost connection to the replay server.
