### ISSUE TITLE
java.lang.RuntimeException: Forged Alliance Crashed with exit code 1. See game_14805280.log for more information     at com.faforever.client.game.GameService.lambda$spawnTerminationListener$43(GameService.java:696)     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)     at java.base/java.lang.Thread.run(Thread.java:832)

### ISSUE THREAD

**Issue by dimidrolio0** [FAForever/downlords-faf-client#2296]
So , this problem occured every game i tried to play , after same period of time , would like to see if some of you guys could help me with finding solution to this problem , again , the error:
java.lang.RuntimeException: Forged Alliance Crashed with exit code 1. See game_14805280.log for more information
    at com.faforever.client.game.GameService.lambda$spawnTerminationListener$43(GameService.java:696)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832) (The game is Supreme Commander:Forged Alliance)

**Comment by Sheikah45** [comment]
This is a game issue and not a client issue. Best source of help for this is the technical help on the discord or the forum.

**Comment by Uveso** [comment]
we continued here:
https://forum.faforever.com/topic/1856/game-starts-freezing-then-crashes
