### ISSUE TITLE
Show friendly error messages on login failure (Throttled login)

### ISSUE THREAD

**Issue by DotNetSimon** [FAForever/downlords-faf-client#2309]
**Describe the bug**
When attempting failed login multiple times in a row, you get an error report instead of a nice client error

**To Reproduce**
Login with wrong password 3x quickly in a row

**Log or error message**
This is my log file:
```java.lang.RuntimeException: Error during login
	at com.faforever.client.login.LoginController.lambda$initialize$13(LoginController.java:207)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyStringPropertyBase.fireValueChangedEvent(ReadOnlyStringPropertyBase.java:72)
	at javafx.beans.property.ReadOnlyStringWrapper.fireValueChangedEvent(ReadOnlyStringWrapper.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
	at javafx.scene.web.WebEngine.updateLocation(WebEngine.java:434)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1364)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1239)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2524)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2369)
	at com.sun.webkit.network.URLLoaderBase.twkWillSendRequest(Native Method)
	at com.sun.webkit.network.HTTP2Loader.lambda$willSendRequest$14(HTTP2Loader.java:497)
	at com.sun.webkit.network.HTTP2Loader.lambda$callBackIfNotCanceled$10(HTTP2Loader.java:437)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Expected behavior**
Show a user friendly error message saying something along the lines of "You have to wait a little before trying to login again."

**Screenshots**
![image](https://user-images.githubusercontent.com/86734095/125452144-e1cdd4a2-f56a-4a1e-a3db-b41b3691d638.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Can you add either the full log file or the full error this looks like only part of it

**Comment by Brutus5000** [comment]
Interesting. The user service should redirect you onto a website showing a nicer message.
Need to check on that.

**Comment by DotNetSimon** [comment]
```
2021-07-13 11:41:46.391  WARN 6936 --- [background-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-07-13 11:41:46.587  INFO 6936 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application using Java 15.0.1 on %CPU_NAME% with PID 6936 (started by %USER% in D:\Games\Downlord's FAF Client)
2021-07-13 11:41:46.588  INFO 6936 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : The following profiles are active: prod,windows
2021-07-13 11:41:47.821  INFO 6936 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'asyncConfig' of type [com.faforever.client.config.AsyncConfig$$EnhancerBySpringCGLIB$$7dc4ab06] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-07-13 11:41:47.851  INFO 6936 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'cacheConfig' of type [com.faforever.client.config.CacheConfig$$EnhancerBySpringCGLIB$$df035e4c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-07-13 11:41:48.180  INFO 6936 --- [JavaFX-Launcher] c.f.c.preferences.PreferencesService     : Switching FA Forever logging configuration to INFO
2021-07-13 11:41:48.268  INFO 6936 --- [JavaFX-Launcher] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2021-07-13 11:41:49.194  INFO 6936 --- [JavaFX-Launcher] c.f.c.map.generator.MapGeneratorService  : Deleting leftover generated maps...
2021-07-13 11:41:49.503  INFO 6936 --- [JavaFX-Launcher] com.faforever.client.update.Version      : The current application version is: 1.5.0-RC2
2021-07-13 11:41:49.572  INFO 6936 --- [JavaFX-Launcher] c.f.c.update.ClientUpdateServiceImpl     : Current version: 1.5.0-RC2
2021-07-13 11:41:49.619  INFO 6936 --- [pool-3-thread-3] c.f.client.update.CheckForUpdateTask     : Checking for client update
2021-07-13 11:41:49.632  INFO 6936 --- [pool-3-thread-4] c.f.c.update.CheckForBetaUpdateTask      : Checking for client update (pre-release channel)
2021-07-13 11:41:50.524  INFO 6936 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 4.953 seconds (JVM running for 6.81)
2021-07-13 11:41:52.569  INFO 6936 --- [ForkJoinPool.commonPool-worker-3] com.faforever.client.update.Version      : fromVersion '1.4.6' is not newer than toVersion '1.5-rc-2'. No update is required.
2021-07-13 11:41:54.562  INFO 6936 --- [Discord RPC] c.f.client.discord.DiscordEventHandler   : Discord is ready with user 'Trenair'
2021-07-13 11:42:13.739  WARN 6936 --- [JavaFX Application Thread] c.f.client.login.LoginController         : Error during login error: url http://localhost/?error=login_throttled&error_description=&state=A5Bq2Uxd6CUQFZh0DLLZoItOU86DiT3UV0J5guIfA7Vsj4gBk5gdaxiDgs8zcw5XwJ6ulZeg; error login_throttled; 
```

Maybe it's the URL aiming at localhost? 😮

**Comment by Sheikah45** [comment]
@Brutus5000 that was probably me. I added in an html error catcher client side that when an error is reported will report to the user with the client interface and then redirect the login webview to the front login page.

The main reason for this being that once the login webview directs away from the login flow in anyway there is no way from the client to get back there besides closing and opening the client application.

**Comment by Sheikah45** [comment]
Also yes the redirects all point to local host

**Comment by DotNetSimon** [comment]
Ok makes sense then!

**Comment by Brutus5000** [comment]
I'm transferring over this issue to the faf-user-service because there is where we need to fix it.
