### ISSUE TITLE
Cannot run program "/home/[omitted]/Games/forged_alliance/downlords-faf-client-1.5.0/lib/faf-uid": error=2, No such file or directory

### ISSUE THREAD

**Issue by piisawheel** [FAForever/downlords-faf-client#2320]
This shows when I try to run faf on linux.
Ubuntu 20.04 LTS
Current Linux Steam
Proton 4.11

It occurs to me that faf-uid is located in /natives/faf-uid and *not* /lib/faf-uid, although I don't know how to fix it, and I'm assuming it's compiled in somewhere.
Same configuration runs 1.4.6 just fine. There's no spaces in the username.

Here's the full error:
```
java.io.IOException: Cannot run program "/home/[omitted]/Games/forged_alliance/downlords-faf-client-1.5.0/lib/faf-uid": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:591)
	at java.base/java.lang.Runtime.exec(Runtime.java:450)
	at com.faforever.client.os.OsUtils.execAndGetOutput(OsUtils.java:21)
	at com.faforever.client.legacy.PosixUidService.generate(PosixUidService.java:22)
	at com.faforever.client.remote.FafServerAccessorImpl.logIn(FafServerAccessorImpl.java:508)
	at com.faforever.client.remote.FafServerAccessorImpl.onSessionInitiated(FafServerAccessorImpl.java:503)
	at com.faforever.client.remote.FafServerAccessorImpl.lambda$parseServerObject$1(FafServerAccessorImpl.java:469)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.faforever.client.remote.FafServerAccessorImpl.parseServerObject(FafServerAccessorImpl.java:469)
	at com.faforever.client.remote.FafServerAccessorImpl.onServerMessage(FafServerAccessorImpl.java:443)
	at com.faforever.client.remote.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:43)
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:239)
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:213)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 22 more
```

**Comment by Sheikah45** [comment]
There should be a .vmoptions file in your downlord's client install you need to add -DnativeDir=natives
