### ISSUE TITLE
"Could not log in (504)" error

### ISSUE THREAD

**Issue by danfoster** [FAForever/downlords-faf-client#236]
When attempting to login, the client attempts to login for a long time but eventually gives an error of "Could not log in (504)".

The matching logs are as follows. The last log line is logged quickly, nothing if logged curing the long timeout.

```
21:25:24.006 [JavaFX Application Thread] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@12443da: startup date [Mon Jun 13 21:25:24 BST 2016]; root of context hierarchy
21:25:24.676 [JavaFX Application Thread] INFO  c.f.c.preferences.PreferencesService - Game path is not specified or non-existent, trying to detect
21:25:24.677 [JavaFX Application Thread] INFO  c.f.c.preferences.PreferencesService - Game path could not be detected
21:25:25.098 [JavaFX Application Thread] WARN  c.g.a.c.u.store.FileDataStoreFactory - unable to change permissions for everybody: C:\Users\dan\AppData\Roaming\Forged Alliance Forever\oauth
21:25:25.100 [JavaFX Application Thread] WARN  c.g.a.c.u.store.FileDataStoreFactory - unable to change permissions for owner: C:\Users\dan\AppData\Roaming\Forged Alliance Forever\oauth
21:25:25.183 [JavaFX Application Thread] INFO  c.f.c.c.ConnectivityServiceImpl - Opened public UDP socket: 0.0.0.0/0.0.0.0:6112
21:25:26.959 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - Trying to connect to FAF server at lobby.faforever.com:8001
21:25:26.987 [Thread-13] DEBUG c.f.c.remote.JsonMessageSerializer - Writing to server: {"version": "0.6.11-alpha","user_agent": "downlords-faf-client","command": "ask_session"}    
21:25:26.987 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - FAF server connection established
21:25:27.057 [Thread-13] DEBUG c.f.c.remote.AbstractServerAccessor - Message from server: {"session": 1109290944, "command": "session"}
21:25:27.060 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - FAF session initiated, session ID: 1109290944
21:25:30.222 [Thread-13] DEBUG c.f.c.remote.JsonMessageSerializer - Writing to server: {"login": "TP2k","password": "********","session": 1109290944,"unique_id": "******","local_ip": "10.42.2.2","command": "hello"}   1109290944
21:25:30.222 [Thread-13] DEBUG c.f.c.remote.AbstractServerAccessor - Message from server: {"command": "matchmaker_info", "queues": [{"boundary_80s": [[590, 990]], "boundary_75s": [[690, 890]], "queue_name": "ladder1v1"}]}
21:25:30.398 [Thread-13] DEBUG c.f.c.remote.AbstractServerAccessor - Message from server: {"login": "TP2k", "id": 13803, "command": "welcome"}
21:25:30.398 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - FAF login succeeded
```

**Comment by micheljung** [comment]
Thx for reporting.

Your log looks fine, the one from seero however shows:
```
23:09:46.854 [Thread-14] WARN  c.f.client.login.LoginController - Login failed
java.util.concurrent.CompletionException: java.lang.RuntimeException: Could not log in (504)
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[na:1.8.0_92]
	at com.faforever.client.remote.FafServerAccessorImpl.onFafLoginSucceeded(FafServerAccessorImpl.java:396) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.lambda$parseServerObject$413(FafServerAccessorImpl.java:371) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_92]
	at com.faforever.client.remote.FafServerAccessorImpl.parseServerObject(FafServerAccessorImpl.java:371) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.onServerMessage(FafServerAccessorImpl.java:348) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:44) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:199) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:175) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_92]
	at javafx.concurrent.Service.lambda$null$492(Service.java:725) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_92]
	at javafx.concurrent.Service.lambda$executeTask$493(Service.java:724) ~[jfxrt.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_92]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_92]
Caused by: java.lang.RuntimeException: Could not log in (504)
	at com.faforever.client.api.FafApiAccessorImpl.authorize(FafApiAccessorImpl.java:258) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.api.FafApiAccessorImpl.authorize(FafApiAccessorImpl.java:152) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_92]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at com.sun.proxy.$Proxy29.authorize(Unknown Source) ~[na:na]
	at com.faforever.client.user.UserServiceImpl.lambda$login$452(UserServiceImpl.java:57) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	... 20 common frames omitted
```

Which happens due to an API timeout. Maybe this is caused by https://github.com/FAForever/api/issues/63, I'll keep an eye on it

**Comment by micheljung** [comment]
@danfoster is this still reproducible?

**Comment by danfoster** [comment]
I get something different now:

(timezone is BST if you want to match server logs)
```
18:44:40.591 [JavaFX Application Thread] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@12443da: startup date [Thu Jun 16 18:44:40 BST 2016]; root of context hierarchy
18:44:41.363 [JavaFX Application Thread] INFO  c.f.c.preferences.PreferencesService - Game path is not specified or non-existent, trying to detect
18:44:41.363 [JavaFX Application Thread] INFO  c.f.c.preferences.PreferencesService - Game path could not be detected
18:44:41.816 [JavaFX Application Thread] WARN  c.g.a.c.u.store.FileDataStoreFactory - unable to change permissions for everybody: C:\Users\dan\AppData\Roaming\Forged Alliance Forever\oauth
18:44:41.817 [JavaFX Application Thread] WARN  c.g.a.c.u.store.FileDataStoreFactory - unable to change permissions for owner: C:\Users\dan\AppData\Roaming\Forged Alliance Forever\oauth
18:44:41.899 [JavaFX Application Thread] INFO  c.f.c.c.ConnectivityServiceImpl - Opened public UDP socket: 0.0.0.0/0.0.0.0:6112
18:44:43.746 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - Trying to connect to FAF server at lobby.faforever.com:8001
18:44:43.771 [Thread-13] DEBUG c.f.c.remote.JsonMessageSerializer - Writing to server: {"version": "0.6.11-alpha","user_agent": "downlords-faf-client","command": "ask_session"}    
18:44:43.771 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - FAF server connection established
18:44:43.791 [Thread-13] DEBUG c.f.c.remote.AbstractServerAccessor - Message from server: {"session": 292773969, "command": "session"}
18:44:43.794 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - FAF session initiated, session ID: 292773969
18:44:46.956 [Thread-13] DEBUG c.f.c.remote.JsonMessageSerializer - Writing to server: {"login": "TP2k","password": "********","session": 292773969,"unique_id": "*********","local_ip": "10.42.2.2","command": "hello"}   292773969
18:44:47.116 [Thread-13] DEBUG c.f.c.remote.AbstractServerAccessor - Message from server: {"login": "TP2k", "id": 13803, "command": "welcome"}
18:44:47.117 [Thread-13] INFO  c.f.c.remote.FafServerAccessorImpl - FAF login succeeded
18:44:47.507 [Thread-13] WARN  c.f.client.login.LoginController - Login failed
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[na:1.8.0_92]
	at com.faforever.client.remote.FafServerAccessorImpl.onFafLoginSucceeded(FafServerAccessorImpl.java:396) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.lambda$parseServerObject$413(FafServerAccessorImpl.java:371) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_92]
	at com.faforever.client.remote.FafServerAccessorImpl.parseServerObject(FafServerAccessorImpl.java:371) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.onServerMessage(FafServerAccessorImpl.java:348) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:44) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:199) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:175) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_92]
	at javafx.concurrent.Service.lambda$null$492(Service.java:725) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_92]
	at javafx.concurrent.Service.lambda$executeTask$493(Service.java:724) ~[jfxrt.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_92]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_92]
Caused by: java.lang.NullPointerException: null
	at com.faforever.client.api.FafApiAccessorImpl.authorize(FafApiAccessorImpl.java:279) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at com.faforever.client.api.FafApiAccessorImpl.authorize(FafApiAccessorImpl.java:152) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_92]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201) ~[spring-aop-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at com.sun.proxy.$Proxy29.authorize(Unknown Source) ~[na:na]
	at com.faforever.client.user.UserServiceImpl.lambda$login$452(UserServiceImpl.java:57) ~[downlords-faf-client-0.6.11-alpha.jar:0.6.11-alpha]
	... 20 common frames omitted
```

**Comment by heelix** [comment]
I'm seeing the same permission error on my box.

ri\1.2.1\16c3879644cf9e987df22aa66bd144ed7cd77c89\jain-sip-ri-1.2.1.jar;C:\Users\root\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.13\7fcf30c25b8f4a9379b9dad0d3f487b25272c026\slf4j-api-1.7.13.jar;D:\IntelliJ
IDEA 2016.1.2\lib\idea_rt.jar"
com.intellij.rt.execution.application.AppMain com.faforever.client.Main
12:54:03.058 [JavaFX Application Thread] INFO
 o.s.c.a.AnnotationConfigApplicationContext - Refreshing
org.springframework.context.annotation.AnnotationConfigApplicationContext@7ca520:
startup date [Thu Jun 16 12:54:03 CDT 2016]; root of context hierarchy
*12:54:03.706 [JavaFX Application Thread] INFO
 c.f.c.preferences.PreferencesService - Game path is not specified or
non-existent, trying to detect*
*12:54:03.706 [JavaFX Application Thread] INFO
 c.f.c.preferences.PreferencesService - Game path could not be detected*
*12:54:04.009 [JavaFX Application Thread] WARN
 c.g.a.c.u.store.FileDataStoreFactory - unable to change permissions for
everybody: C:\Users\root\AppData\Roaming\Forged Alliance Forever\oauth*
*12:54:04.009 [JavaFX Application Thread] WARN
 c.g.a.c.u.store.FileDataStoreFactory - unable to change permissions for
owner: C:\Users\root\AppData\Roaming\Forged Alliance Forever\oauth*
12:54:04.100 [JavaFX Application Thread] INFO
 c.f.c.c.ConnectivityServiceImpl - Opened public UDP socket:
0.0.0.0/0.0.0.0:6112

That normal?

**Comment by micheljung** [comment]
Can you all please try deleting `%APPDATA%\Forged Alliance Forever\oauth`

**Comment by micheljung** [comment]
@heelix the permission thing is just a warning, not an error, and it's "expected" to happen under windows

**Comment by micheljung** [comment]
Please let me know if you still have problems, otherwise I assume it was caused by faulty API server.
