### ISSUE TITLE
As a mod uploader, I want to be shown an error with a stack trace should the client fail to parse the mod_info.lua

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#2365]
**To Reproduce**
Try uploading the attached mod

**Expected behavior**
Works

**OS**
Windows

I have not tried uploading it yet myself but since I don't wanna forget about it I open this ticket.

[Advanced Strategic Icons medium size.zip](https://github.com/FAForever/downlords-faf-client/files/7232103/Advanced.Strategic.Icons.medium.size.zip)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Is it the zipping that takes forever? Or that it communicates with the server forever?

**Comment by 1-alex98** [comment]
I have not tried as I said

**Comment by 1-alex98** [comment]
Just told him gimme the mod I will see

**Comment by 1-alex98** [comment]
```
java.util.concurrent.CompletionException: com.faforever.commons.mod.ModLoadException: org.luaj.vm2.LuaError: load @624586584: java.lang.NumberFormatException: multiple points
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.faforever.commons.mod.ModLoadException: org.luaj.vm2.LuaError: load @624586584: java.lang.NumberFormatException: multiple points
	at com.faforever.commons.mod.ModReader.readModInfo(ModReader.java:102)
	at com.faforever.client.mod.ModService.extractModInfo(ModService.java:285)
	at com.faforever.client.mod.ModService.extractModInfo(ModService.java:279)
	at com.faforever.client.mod.ModService$$FastClassBySpringCGLIB$$aae9cfd3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.faforever.client.mod.ModService$$EnhancerBySpringCGLIB$$636d8ded.extractModInfo(<generated>)
	at com.faforever.client.mod.ModUploadController.lambda$setModPath$0(ModUploadController.java:91)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	... 3 common frames omitted
Caused by: org.luaj.vm2.LuaError: load @624586584: java.lang.NumberFormatException: multiple points
	at org.luaj.vm2.LuaValue.error(Unknown Source)
	at org.luaj.vm2.Globals.load(Unknown Source)
	at com.faforever.commons.lua.LuaLoader.load(LuaLoader.java:29)
	at com.faforever.commons.mod.ModReader.readModInfo(ModReader.java:73)
	... 11 common frames omitted
```

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/134825396-d5645673-1246-45f4-b6f8-84d2c69052c0.png)
Also says reading `map` while it is reading the `mod`. If the error lies within the mod to upload it should at least show an exception to the user ;)

**Comment by 1-alex98** [comment]
It is about the mod_info.lua it contains verion=3.3.1 but numbers can only have one point at most

**Comment by 1-alex98** [comment]
So take away here would be improve the useablity by acctually showiung an error

**Comment by Sheikah45** [comment]
Well maybe not the error but at least a warning or something

**Comment by 1-alex98** [comment]
Well we normally display stack traces so I guess we would here as well.

**Comment by 1-alex98** [comment]
And for me `java.lang.NumberFormatException: multiple points` was pretty helpful. I had no idea before what the issue was the lua looked pretty good

**Comment by Sheikah45** [comment]
Yeah I just meant to have a clear message and not rely purely on the stack trace

**Comment by 1-alex98** [comment]
Yeah sure
