### ISSUE TITLE
Automatic client update fails on Linux

### ISSUE THREAD

**Issue by marwonline** [FAForever/downlords-faf-client#2479]
**Describe the bug**
Automatic update points to wrong URL.

**To Reproduce**

- Have an "older" installation of the FAF client via [Lutris](https://lutris.net/games/forged-alliance-forever/)
- Click the "download update" button
- Wait "forever".... actually nothing happens and the following error is in the logs

**Log or error message**

```
java.util.concurrent.CompletionException: java.io.FileNotFoundException: https://github.com/FAForever/downlords-faf-client/releases/download/v2021.10.0/dfc_unix_2021_11_0.tar.gz
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:18)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1358)
	at javafx.concurrent.Task.setState(Task.java:709)
	at javafx.concurrent.Task$TaskCallable.lambda$call$2(Task.java:1455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.FileNotFoundException: https://github.com/FAForever/downlords-faf-client/releases/download/v2021.10.0/dfc_unix_2021_11_0.tar.gz
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1167)
	at com.faforever.client.update.DownloadUpdateTask.call(DownloadUpdateTask.java:52)
	at com.faforever.client.update.DownloadUpdateTask.call(DownloadUpdateTask.java:22)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	... 1 common frames omitted
```

**Expected behavior**
The game client downloads the update. 

The URL points to 

`https://github.com/FAForever/downlords-faf-client/releases/download/v2021.10.0/dfc_unix_2021_11_0.tar.gz`

but should point to

`https://github.com/FAForever/downlords-faf-client/releases/download/v2021.10.0/dfc_unix_2021_10_0.tar.gz`

**Screenshots**

- 

**OS**
Linux

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
@Brutus5000 if you have a chance can you fix the remote config json. I could do it tomorrow if you don't get to it.

**Comment by Brutus5000** [comment]
It doesn't matter. The auto-update doesn't work on Linux anyway.

**Comment by marwonline** [comment]
:smile: Okay. Then re-installing seems to be the only option (for now).

Thank you for your fast replies. I really appreciate your work.

**Comment by Brutus5000** [comment]
Maybe we shouldn't change this button for Linux users

**Comment by Sheikah45** [comment]
Do you mean show the auto update button? Maybe. At least until someone fixes it
