### ISSUE TITLE
The rating chart does not load for some players

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2514]
Open `Show user info` window for `NiCAD` player. It can be found in the leaderboard.
After opening, the error will be printed in the log file.
From log file:

```2022-01-10 03:28:51.039 ERROR 1188 --- [JavaFX Application Thread] com.faforever.client.fx.JavaFxUtil       : Uncaught Application Thread Error

java.lang.NullPointerException: Cannot invoke "java.time.OffsetDateTime.isAfter(java.time.OffsetDateTime)" because the return value of "com.faforever.client.domain.GamePlayerStatsBean.getScoreTime()" is null
	at com.faforever.client.player.PlayerInfoWindowController.lambda$plotPlayerRatingGraph$42(PlayerInfoWindowController.java:447)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.faforever.client.player.PlayerInfoWindowController.plotPlayerRatingGraph(PlayerInfoWindowController.java:450)
	at com.faforever.client.fx.JavaFxUtil.runLater(JavaFxUtil.java:487)
	at com.faforever.client.player.PlayerInfoWindowController.lambda$onRatingTypeChange$39(PlayerInfoWindowController.java:428)
	at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
	at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
	at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2185)
	at com.faforever.client.player.PlayerInfoWindowController.onRatingTypeChange(PlayerInfoWindowController.java:428)
	at com.faforever.client.player.PlayerInfoWindowController.setOnlinePlayer(PlayerInfoWindowController.java:219)
	at com.faforever.client.player.PlayerInfoWindowController.setPlayer(PlayerInfoWindowController.java:204)
	at com.faforever.client.fx.AbstractPlayerContextMenuController.onShowUserInfoSelected(AbstractPlayerContextMenuController.java:100)
	at com.faforever.client.fx.AbstractPlayerContextMenuController.lambda$initialize$0(AbstractPlayerContextMenuController.java:77)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by Marc-Spector** [comment]
For `C00KIE` player was printed that error (just one line):
```

2022-01-10 03:38:45.950 ERROR 1188 --- [JavaFX Application Thread] com.faforever.client.fx.JavaFxUtil       : Uncaught Application Thread Error

java.lang.NullPointerException: null
