### ISSUE TITLE
(Dev environment) Error when closing the client

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2552]
This is not the bug (although I am not sure), but just an inconvenience and annoyance for developers.

When you do something (it does not matter) in the "Custom Games" tab, if at least one tooltip shows us, the error will be printed when closing the client:

<details>
  <summary>Error</summary>
  
    2022-01-30 05:07:21.449 ERROR 1076 --- [lication Thread] c.f.c.exception.GlobalExceptionHandler   : Exception on Thread Thread[JavaFX Application Thread,5,main]: 

    com.faforever.client.exception.FxmlLoadException: Could not load fxml theme/player_card_tooltip.fxml
	    at com.faforever.client.theme.UiService.loadFxml(UiService.java:444)
	    at com.faforever.client.theme.UiService$$FastClassBySpringCGLIB$$2b0b2208.invoke(<generated>)
	    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	    at com.faforever.client.theme.UiService$$EnhancerBySpringCGLIB$$cb275642.loadFxml(<generated>)
	    at com.faforever.client.game.TeamCardController.setPlayersInTeam(TeamCardController.java:81)
	    at com.faforever.client.game.TeamCardController.createAndAdd(TeamCardController.java:65)
	    at com.faforever.client.game.GameDetailController.createTeams(GameDetailController.java:183)
	    at com.faforever.client.game.GameDetailController.lambda$resetListeners$8(GameDetailController.java:165)
	    at javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
	    at com.faforever.client.fx.JavaFxUtil.addAndTriggerListener(JavaFxUtil.java:277)
	    at com.faforever.client.game.GameDetailController.setGame(GameDetailController.java:153)
	    at com.faforever.client.game.CustomGamesController.setSelectedGame(CustomGamesController.java:236)
	    at com.faforever.client.game.CustomGamesController.lambda$onTableButtonClicked$10(CustomGamesController.java:208)
	    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	    at com.faforever.client.game.GamesTableController.lambda$initializeGameTable$25(GamesTableController.java:152)
	    at com.faforever.client.fx.JavaFxUtil.runLater(JavaFxUtil.java:473)
	    at com.faforever.client.game.GamesTableController.lambda$initializeGameTable$26(GamesTableController.java:152)
	    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	    at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	    at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:105)
	    at javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateSelectedIndex(TableView.java:3005)
	    at javafx.scene.control.TableView$TableViewArrayListSelectionModel.select(TableView.java:2507)
	    at javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearAndSelect(TableView.java:2437)
	    at javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearAndSelect(TableView.java:2397)
	    at javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(TableView.java:2204)
	    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	    at javafx.collections.transformation.SortedList.sourceChanged(SortedList.java:111)
	    at javafx.collections.transformation.TransformationList.lambda$getListener$0(TransformationList.java:106)
	    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	    at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	    at javafx.collections.transformation.FilteredList.sourceChanged(FilteredList.java:147)
	    at javafx.collections.transformation.TransformationList.lambda$getListener$0(TransformationList.java:106)
	    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	    at javafx.collections.FXCollections$SynchronizedObservableList.lambda$new$0(FXCollections.java:1217)
	    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	    at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	    at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:183)
	    at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:171)
	    at javafx.collections.FXCollections$SynchronizedList.remove(FXCollections.java:1074)
	    at com.faforever.client.fx.JavaFxUtil.lambda$attachListToMap$1(JavaFxUtil.java:192)
	    at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	    at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	    at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	    at com.sun.javafx.collections.ObservableMapWrapper.clear(ObservableMapWrapper.java:203)
	    at com.faforever.client.game.GameService.lambda$afterPropertiesSet$4(GameService.java:227)
	    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	    at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	    at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:72)
	    at com.faforever.client.remote.FafServerAccessor.disconnect(FafServerAccessor.java:160)
	    at com.faforever.client.remote.FafServerAccessor.destroy(FafServerAccessor.java:306)
	    at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:212)
	    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1161)
	    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1154)
	    at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
	    at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075)
	    at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	    at com.faforever.client.FafClientApplication.stop(FafClientApplication.java:165)
	    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$10(LauncherImpl.java:865)
	    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	    at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	    at java.base/java.lang.Thread.run(Thread.java:832)
    Caused by: javafx.fxml.LoadException: 
    /D:/Git/FAForever/downlords-faf-client/build/resources/main/theme/player_card_tooltip.fxml:10
    
	    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
	    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2685)
	    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2517)
	    at com.faforever.client.theme.UiService.loadFxml(UiService.java:441)
	    ... 99 common frames omitted
    Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'playerCardTooltipController' defined in file [D:\Git\FAForever\downlords-faf-client\build\classes\java\main\com\faforever\client\game\PlayerCardTooltipController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'countryFlagService': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1282)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1243)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
	    at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:940)
	    at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:982)
	    at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:229)
	    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
	    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2808)
	    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2634)
	    ... 102 common frames omitted
    Caused by: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'countryFlagService': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	    ... 121 common frames omitted
    
    2022-01-30 05:07:21.457  INFO 1076 --- [lication Thread] c.f.c.map.generator.MapGeneratorService  : Deleting leftover generated maps...
    2022-01-30 05:07:21.468  INFO 1076 --- [lication Thread] com.faforever.client.config.AsyncConfig  : Shutting down ExecutorService 'taskExecutor'
    
    Process finished with exit code 0

</details>

Follow these steps to get the error:
1. Select any game in the "Custom Games" tab.
2. Hover over any game and wait for the tooltip to appear.
3. Close the client.

**Comment by Sheikah45** [comment]
Yeah I haven't figured out how to avoid it because it is due to the destruction order of the beans and the reception of a game message while it is shutting down.
