### ISSUE TITLE
(Dev environment) Repair broken `reload` profile

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2555]
When the client starts, it gives the error:

    23:40:40.254 [main] DEBUG com.faforever.client.logging.LoggingService - Logger initialized
    2022-02-01 23:40:43.147  INFO 3928 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application using Java 15.0.2 on %CPU_NAME% with PID 3928 (started by %USER% in D:\Git\FAForever\downlords-faf-client)
    2022-02-01 23:40:43.149  INFO 3928 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : The following profiles are active: windows,reload
    2022-02-01 23:40:44.564  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'faf-client-com.faforever.client.config.ClientProperties' of type [com.faforever.client.config.ClientProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.572  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'fafClientApplication' of type [com.faforever.client.FafClientApplication$$EnhancerBySpringCGLIB$$253690cf] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.588  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'platformService' of type [com.faforever.client.fx.PlatformService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.590  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'reportingService' of type [com.faforever.client.reporting.ReportingService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.596  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'baseConfig' of type [com.faforever.client.config.BaseConfig$$EnhancerBySpringCGLIB$$53cefcec] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.602  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'messageSource' of type [org.springframework.context.support.ReloadableResourceBundleMessageSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.875  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'preferencesService' of type [com.faforever.client.preferences.PreferencesService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.880  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'i18n' of type [com.faforever.client.i18n.I18n] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.885  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'notificationService' of type [com.faforever.client.notification.NotificationService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:44.887  INFO 3928 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'asyncConfig' of type [com.faforever.client.config.AsyncConfig$$EnhancerBySpringCGLIB$$38b22407] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2022-02-01 23:40:46.134  INFO 3928 --- [JavaFX-Launcher] c.f.client.logging.LoggingService        : Switching FA Forever logging configuration to INFO
    2022-02-01 23:40:46.163  INFO 3928 --- [JavaFX-Launcher] com.faforever.client.update.Version      : The current application version is: snapshot
    2022-02-01 23:40:46.164  INFO 3928 --- [JavaFX-Launcher] c.f.client.update.ClientUpdateService    : Current version: snapshot
    2022-02-01 23:40:46.174  INFO 3928 --- [pool-3-thread-3] c.f.client.update.CheckForUpdateTask     : Checking for client update
    2022-02-01 23:40:46.200  INFO 3928 --- [pool-3-thread-4] c.f.c.update.CheckForBetaUpdateTask      : Checking for client update (pre-release channel)
    2022-02-01 23:40:46.732  INFO 3928 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 5.384 seconds (JVM running for 8.173)
    > Patching com/sun/webkit/WebPage ...
    > com/sun/webkit/WebPage patching succeeded!
    Exception in Application start method
    2022-02-01 23:40:49.233  WARN 3928 --- [lication Thread] c.f.client.fa.relay.ice.IceAdapterImpl   : Ignoring call to ICE adapter as we are not connected: quit([])
    2022-02-01 23:40:49.237  INFO 3928 --- [lication Thread] c.f.client.remote.FafServerAccessor      : Closing lobby server connection
    2022-02-01 23:40:49.237  WARN 3928 --- [lication Thread] com.faforever.commons.lobby.FafLobbyApi  : Attempting to disconnect while never connected
    2022-02-01 23:40:49.238  INFO 3928 --- [lication Thread] c.f.c.map.generator.MapGeneratorService  : Deleting leftover generated maps...
    2022-02-01 23:40:49.244  INFO 3928 --- [lication Thread] com.faforever.client.config.AsyncConfig  : Shutting down ExecutorService 'taskExecutor'
    2022-02-01 23:40:51.286  WARN 3928 --- [           main] c.f.c.exception.GlobalExceptionHandler   : Uncaught exception on Thread[main,5,main]: 
    
    java.lang.RuntimeException: Exception in Application start method
	    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	    at java.base/java.lang.Thread.run(Thread.java:832)
    Caused by: com.faforever.client.exception.FxmlLoadException: Could not load fxml theme/login/login.fxml
	    at com.faforever.client.theme.UiService.loadFxml(UiService.java:444)
	    at com.faforever.client.theme.UiService$$FastClassBySpringCGLIB$$2b0b2208.invoke(<generated>)
	    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	    at com.faforever.client.theme.UiService$$EnhancerBySpringCGLIB$$39715b0f.loadFxml(<generated>)
	    at com.faforever.client.main.MainController.enterLoggedOutState(MainController.java:384)
	    at com.faforever.client.main.MainController.display(MainController.java:356)
	    at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:140)
	    at com.faforever.client.FafClientApplication.start(FafClientApplication.java:122)
	    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	    at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	    ... 1 common frames omitted
    Caused by: javafx.fxml.LoadException: 
    /D:/Git/FAForever/downlords-faf-client/build/resources/main/theme/login/login.fxml
    
	    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
	    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2677)
	    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2517)
	    at com.faforever.client.theme.UiService.loadFxml(UiService.java:441)
	    ... 17 common frames omitted
    Caused by: java.lang.reflect.InvocationTargetException: null
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	    at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	    at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	    at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2673)
	    ... 20 common frames omitted
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'browserCallback' defined in file [D:\Git\FAForever\downlords-faf-client\build\classes\java\main\com\faforever\client\fx\BrowserCallback.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "String.split(String)" because "urlFormat" is null
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1282)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1243)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
	    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
	    at com.faforever.client.fx.WebViewConfigurer.configureWebView(WebViewConfigurer.java:52)
	    at com.faforever.client.login.LoginController.initialize(LoginController.java:190)
	    ... 32 common frames omitted
    Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "urlFormat" is null
	    at com.faforever.client.fx.BrowserCallback.afterPropertiesSet(BrowserCallback.java:57)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	    ... 44 common frames omitted
    
    
    Process finished with exit code 1

**Comment by Sheikah45** [comment]
The reload profile isn't meant to be used alone. You need to also specify prod, test or local. The main with reload configuration shows how to properly use it
