### ISSUE TITLE
Connection to FAF interrupted due to timeout

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2706]
There were no attempts to reconnect automatically. I had to manually connect it.

**To Reproduce**
Do not know. It seems that this issue appears if you are online for more than an hour.

**Log or error message**
```
2022-05-19 00:12:07.413 ERROR 13196 --- [parallel-4] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'next' (and no fallback has been configured)
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'next' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**OS**
Windows

Client Version: 2022.4.1

**Comment by Marc-Spector** [comment]
It looks like this is not the client issue, but a library issue.

**Comment by Sheikah45** [comment]
Not necessarily in the last client I implemented a 60 second timeout for pong from the server to check the connection. It should have tried to reconnect if the server didn't respond to the ping in 60 seconds

**Comment by Sheikah45** [comment]
@Marc-Spector if you can reproduce this and post the full logs on debug mode I can see what the server messages are

**Comment by Sheikah45** [comment]
Should also see a log message saying the server did not respond in the log as well
