### ISSUE TITLE
Cannot Run FAF Client in DWM

### ISSUE THREAD

**Issue by GeorgeZack** [FAForever/downlords-faf-client#2838]
**Describe the bug**
Unable to run the FAF Client in DWM (Dynamic Window Manager) [link here](https://dwm.suckless.org/). I use the followin command to run the client:
`_JAVA_AWT_WM_NONREPARENTING=1 INSTALL4J_JAVA_HOME="/usr/lib/jvm/java-19-openjdk/" ~/faf/faf-client-2022.10.0/faf-client`
And have set my `wmname` to various different values like `LG3D`, `compiz`, `Metacity`, and `Gnome`. But none work.
I have followed the Linux FAQ/Guide on the wiki but without luck.

**To Reproduce**
Run the client in a DWM environment.

**Log or error message**
This is my log file:
[error.log](https://github.com/FAForever/downlords-faf-client/files/9923997/error.log)

**Expected behavior**
I expect to run the client without error.

**Screenshots**
![2022-11-02-153047_960x727_scrot](https://user-images.githubusercontent.com/19842313/199597935-789a3ba7-e98d-4caa-af08-32dd60915105.png)

**OS**
Linux
OS: Artix Linux x86_64
Kernal: 6.0.2-artix1-1.1

I'm fully aware of the pain I'm inducing on myself by playing games on a DWM environment. I'm half tempted to setup a VM for gaming. DWM seems to have issues with games and fullscreen applications, and anything written in Java.

**Comment by Sheikah45** [comment]
The underlying network library we use can't handle your wlan dns server or something on your machine isn't allowing it to be resolved

**Comment by GeorgeZack** [comment]
> The underlying network library we use can't handle your wlan dns server or something on your machine isn't allowing it to be resolved

Wow, thank you for pointing that out. When I looked at my `/etc/resolv.conf` file I had that peculiar inet6 type address. Removing that solved the issue. I'm now able to get to the login screen. We'll see if I can login though. (For any other users with this issue, I was using NMCLI. I had to set the ipv6 dns to blank and set the ipv6 dns to ignore auto dns settings.)

**Comment by GeorgeZack** [comment]
Unfortunately I cannot login, I keep getting `Operator called default onErrorDropped` and
```
Client Version: 2022.10.0
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 60000ms in 'sinkOneMulticast' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
	at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by GeorgeZack** [comment]
My bad. Figured it out. I moved the contents of the `~/faf/faf-client-2022.10.0/` into `~/faf/`.
