### ISSUE TITLE
Java bug - Unmappable Character Exception - handling file encoding part 2

### ISSUE THREAD

**Issue by magge-faf** [FAForever/downlords-faf-client#2905]
**Situation:**

Since committing following code to fix the occasionally file encoding issues, https://github.com/FAForever/downlords-faf-client/pull/2898 there were numerous reports in Discord/Forum about following new error which users encountered when they click a button like 'create game'. They have not changed anything and it worked before. with their 'Game.prefs' file:

<details>
  <summary>error text</summary>
  

`java.lang.Error: java.nio.charset.UnmappableCharacterException: Input length = 2
at java.base/java.lang.String.decodeWithDecoder(String.java:1212)
at java.base/java.lang.String.newStringNoRepl1(String.java:786)
at java.base/java.lang.String.newStringNoRepl(String.java:738)
at java.base/java.lang.System$2.newStringNoRepl(System.java:2390)
at java.base/java.nio.file.Files.readString(Files.java:3369)
at com.faforever.client.mod.ModService.readPreferencesFile(ModService.java:314)
at com.faforever.client.mod.ModService.readActiveMods(ModService.java:330)
at com.faforever.client.mod.ModService.enableSimMods(ModService.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:699)
at com.faforever.client.mod.ModService$$SpringCGLIB$$0.enableSimMods(<generated>)
at com.faforever.client.game.GameService.lambda$joinGame$10(GameService.java:332)
at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
at com.faforever.client.task.CompletableTask.lambda$new$2(CompletableTask.java:19)
at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
at javafx.event.Event.fireEvent(Event.java:198)
at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
at javafx.concurrent.Task.fireEvent(Task.java:1359)
at javafx.concurrent.Task.setState(Task.java:725)
at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1437)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 2
at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:275)
at java.base/java.lang.String.decodeWithDecoder(String.java:1205)
... 38 more`
  
</details>

---

**Temporary solution:**

Removing 'Game.prefs' manually and let the FAF client create a new one, but it can bug out randomly again and file needs to be removed again.

---

**Investigation**:

The behavior of the code was completely different from what was expected, because the exception was not catchable. This should not happen with our code. After several reading materials about the UnmappableCharacterException error and with the helpful input of Sheikah45, the trace lead to a possible Java Bug https://bugs.openjdk.org/browse/JDK-8286287 , which was discussed here in more detail: https://stackoverflow.com/questions/72127702/error-which-shouldnt-happen-caused-by-malformedinputexception-when-reading-fi

---

**Reproduce:**

Try the attached 'Game.prefs' file with following code (change path to the file) that code part is currently in use for the FAF client:

```
public static void main(String[] args) {
        final Logger logger = Logger.getLogger(MainFix.class.getName());

        Path filePath = Path.of("D:\\Daten\\chrome_downloads\\Game.prefs"); // change path to file
        Map<String, Charset> availableCharsets = Charset.availableCharsets();
        String preferencesContent = null;
        for (Charset charset : availableCharsets.values()) {
            try {
                logger.info("Trying to read preferences file with charset: " + charset.displayName());
                preferencesContent = Files.readString(filePath, charset);
                logger.info("Successfully read preferences file with charset: " + charset.displayName());
                break;
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

```
---

**Possible long term solution:**

We need to get around this bug somehow, my initial ideas were like:

A. Open file and save it with different encodings
B. Read file byte by byte and convert it into different encoding
C. Open file, search for malformed input and remove it

which are all not suitable, because they will lead to more trouble, when you have so many users with countless different environments, you can not blueprint force such thing.

After some tinkering, this is a possible way to tackle the issue:

```
 private String readPreferencesFile(Path preferencesFile) throws IOException {
    Map<String, Charset> availableCharsets = Charset.availableCharsets();
    String preferencesContent = null;
    for (Charset charset : availableCharsets.values()) {
      CharsetDecoder decoder = charset.newDecoder();
      decoder.onMalformedInput(CodingErrorAction.REPORT);
      decoder.onUnmappableCharacter(CodingErrorAction.REPORT);
      log.info("Trying to read preferences file with charset: " + charset.displayName());
      try {
        ByteBuffer buffer = ByteBuffer.wrap(Files.readAllBytes(preferencesFile));
        CharBuffer charBuffer = decoder.decode(buffer);
        preferencesContent = ((CharBuffer) charBuffer).toString();
        log.info("Successfully read preferences file with charset: " + charset.displayName());
        break;
      } catch (CharacterCodingException e) {
        log.info("Failed to read preferences file with charset: " + charset.displayName());
        // Try a different character set
        continue;
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }
```

The first code snippet uses the Files.readString method to read the contents of a file into a string. The second code snippet uses a CharsetDecoder to read the contents of the file and convert it into a string. The difference between the two is that the second code snippet provides more control over the character decoding process, as it allows specifying how to handle malformed input and unmappable characters.

The "non-working" Game.prefs could be successfully read in a real environment after it had found a working char set, in the old code it bugged out after the first failed try:

![image](https://user-images.githubusercontent.com/101107758/215793754-cf26c90b-61e5-47fe-abca-d0af6c9b34c5.png)

I have tested several other common 'Game.prefs' in real environment, I would be happy if I can snatch more "non-working" files from the Forum to test it out. I do not want to break more things by trying to make it right.

---

@Sheikah45 I will make a PR soon, so you can have a better look at this idea. I would like to hear your thoughts if this is a relatable solution or not. Take your time, and thanks in advance.
[Game.zip](https://github.com/FAForever/downlords-faf-client/files/10548299/Game.zip)

**Comment by Sheikah45** [comment]
Fixed in #2906
