### ISSUE TITLE
Replays fail to start on Windows due to missing directory.

### ISSUE THREAD

**Issue by alexcthomas** [FAForever/downlords-faf-client#3008]
When launching replays on windows, the following error message appears

> "C:\ProgramData\FAForever\replaydata\bin\ForgedAlliance.exe" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=267, The directory name is invalid
>	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
>	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
>	at com.faforever.client.fa.ForgedAllianceService.launch(ForgedAllianceService.java:159)
>	at com.faforever.client.fa.ForgedAllianceService.startReplay(ForgedAllianceService.java:96)
>	at com.faforever.client.game.GameService.lambda$runWithReplay$35(GameService.java:431)

**To Reproduce**
* Under windows
* Completely uninstall FAF client
* Delete C:\ProgramData\FAForever
* Reinstall FAF client
* Download and try to run a replay

**Fix**
Manually create the directory:
C:\ProgramData\FAForever\bin
Then replays run fine.

**Solution**
FAF client should check for the existence of C:\ProgramData\FAForever\bin on startup.
If not present, it should be created.

**Comment by Sheikah45** [comment]
Really replays should run from the replay data subfolder bin so that needs to be properly set up
