### ISSUE TITLE
[Bug]: Catch OAuth login failures before extracting code and state

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#3257]
### Describe the Bug

A common issue during login an exception due to failing regex parsing the OAuth redirect from Ory Hydra

### Log file or Error Message

Client Version: 2024.8.0
java.lang.IllegalStateException: Could not extract value with pattern 'code=([^ &]+)' from: GET /?error=request_forbidden&error_description=The+request+is+not+allowed.+No+CSRF+value+available+in+the+session+cookie.&state=6NPKAdf1l6gJAUOkFOiWY2ruTnEHrZyUqLEaatbXDjeQzpTAZofpQF9opJnPw04WYYmh7cWu8FvKSsg4ocxObMubbV38Kr HTTP/1.1
    at com.faforever.client.login.OAuthValuesReceiver.extractValue(OAuthValuesReceiver.java:145)
    at com.faforever.client.login.OAuthValuesReceiver.readValues(OAuthValuesReceiver.java:137)
    at com.faforever.client.login.OAuthValuesReceiver.readValues(OAuthValuesReceiver.java:92)
    at com.faforever.client.login.OAuthValuesReceiver.lambda$receiveValues$0(OAuthValuesReceiver.java:53)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

### Reproduce the bug

To reproduce most probably, either delete the CSRF cookie or wait until the CSRF token in login screens times out. (Haven't tested it).

### Expected Behavior

From the redirect url it is obvious that there is an `error` key in the request parameters. In that case fail early and show a different/more useful error to the user.

### Which Operating System are you using?

Linux

**Comment by obydog002** [comment]
An easy way to reproduce this is to clear browser cookies on the Authorize browser page, attempt to authorize, click the error popup that appears, then authorize again. the FAF client will throw the error
