### ISSUE TITLE
Error when uploading mods

### ISSUE THREAD

**Issue by MythixDino** [FAForever/downlords-faf-client#437]
When I'm uploading a mod after some time this error shows up:
```
java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(Unknown Source)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.faforever.client.api.FafApiAccessorImpl.postMultipart(FafApiAccessorImpl.java:293)
	at com.faforever.client.api.FafApiAccessorImpl.uploadMod(FafApiAccessorImpl.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201)
	at com.sun.proxy.$Proxy35.uploadMod(Unknown Source)
	at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:72)
	at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:26)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
I tried several times but every time this error pops up again.

**Comment by micheljung** [comment]
This error has already been fixed.
