### ISSUE TITLE
Inactivity causes error in leaderboard

### ISSUE THREAD

**Issue by Stupinator** [FAForever/downlords-faf-client#454]
i have been removed from ladderboard due to inactivity. This results in an error when i click on ladderboard. attached the exception below

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: com.google.api.client.http.HttpResponseException: 404 NOT FOUND
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: com.google.api.client.http.HttpResponseException: 404 NOT FOUND
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:321)
	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:225)
	at com.faforever.client.api.FafApiAccessorImpl.getRanked1v1Entries(FafApiAccessorImpl.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:320)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:353)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy29.getRanked1v1Entries(Unknown Source)
	at com.faforever.client.remote.FafServiceImpl.lambda$getRanked1v1Entries$0(FafServiceImpl.java:128)
	... 4 more
Caused by: com.google.api.client.http.HttpResponseException: 404 NOT FOUND
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
	at com.faforever.client.api.FafApiAccessorImpl.executeGet(FafApiAccessorImpl.java:333)
	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:310)
	... 22 more
java.util.concurrent.CompletionException: java.lang.RuntimeException: com.google.api.client.http.HttpResponseException: 404 NOT FOUND
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: com.google.api.client.http.HttpResponseException: 404 NOT FOUND
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:321)
	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:225)
	at com.faforever.client.api.FafApiAccessorImpl.getRanked1v1Entries(FafApiAccessorImpl.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:320)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:353)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy29.getRanked1v1Entries(Unknown Source)
	at com.faforever.client.remote.FafServiceImpl.lambda$getRanked1v1Entries$0(FafServiceImpl.java:128)
	... 4 more
Caused by: com.google.api.client.http.HttpResponseException: 404 NOT FOUND
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
	at com.faforever.client.api.FafApiAccessorImpl.executeGet(FafApiAccessorImpl.java:333)
	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:310)
	... 22 more

```

**Comment by axel1200** [comment]
Was that fixed? @micheljung

**Comment by micheljung** [comment]
Umm, no idea, we need someone to test this who isn't active in the leaderboard :D Do you have a test account that never played?

**Comment by axel1200** [comment]
No not really, I got my friends accounts password and he did not play for half a year is that enough?

**Comment by micheljung** [comment]
We can easily test this with a local API

**Comment by micheljung** [comment]
This has been fixed
