### ISSUE TITLE
Mod Upload error java.io.IOException: insufficient data written ( Full error text inside )

### ISSUE THREAD

**Issue by Evonos** [FAForever/downlords-faf-client#498]
So Compressing works stage 2 Upload i get this error between 30-60 mb uploaded.

java.io.IOException: insufficient data written
at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(Unknown Source)
at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
at com.faforever.client.api.FafApiAccessorImpl.postMultipart(FafApiAccessorImpl.java:293)
at com.faforever.client.api.FafApiAccessorImpl.uploadMod(FafApiAccessorImpl.java:252)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201)
at com.sun.proxy.$Proxy35.uploadMod(Unknown Source)
at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:72)
at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:26)
at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

http://forums.faforever.com/viewtopic.php?f=3&t=14006

**Comment by Evonos** [comment]
Do you know when this will be fixed ? because it prevents total mayhem from being Uploadet the probably  biggest unit mod out there :(

**Comment by Geosearchef** [comment]
Does this only happen to this mod? If yes, we would need the file you're trying to upload for testing.

There have already been some changes about that. 952fb3c and 5787b5b (#177) (the stacktrace doesn't apply to the current developement version anymore). @micheljung Is this still the case on the develop branch?

**Comment by Evonos** [comment]
Here is the link to Total mayhem 1.30 
http://faforever.uveso.de/TotalMayhem(AllGameVersions)-v1.30.rar

and heres the thread to it http://forums.faforever.com/viewtopic.php?f=47&t=12248

**Comment by Geosearchef** [comment]
Ok, also mod upload is broken on develop currently:

ModUploadTask.java:79 throws an exception but in the finally block when trying to delete the zip file, it is still in use which causes another exception.

https://gist.github.com/Geosearchef/ef00dcfe1b80329d9f64204f1d44136f
https://gist.github.com/Geosearchef/83b379c880f4f32285dde1c8b4b33a9e

**Comment by micheljung** [comment]
This may or may not be fixed with the next version, we'll test it. Thank @Geosearchef I'll have a look at it.
Sorry @Evonos, but since the release is (hopefully) pretty near, we'll not try to hotfix it :)

**Comment by Evonos** [comment]
that would be sad :( because its actually the Biggest unit mod out there ( probably as big as Nomads or even bigger as that  ) and alot of people try to host 1.20 ( that doesnt work buildings copy itself and stuff )

**Comment by Evonos** [comment]
Update i tried it with the new server update that downlords announced still happening same error

**Comment by MythixDino** [comment]
I had reported this issue much earlier though.
#437

**Comment by micheljung** [comment]
This has already been fixed
