### ISSUE TITLE
Connection check doesn't succeed

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#515]
When trying to check connectivity, the client keeps failing with the following exception:
```
17:40:34.276 [Thread-14] WARN  c.f.c.remote.AbstractServerAccessor - Error while handling server message: {"command": "ConnectivityState", "target": "connectivity", "args": ["STUN", "108.162.72.165:49486"]}
java.lang.NullPointerException: null
	at com.faforever.client.remote.FafServerAccessorImpl.lambda$parseServerObject$1(FafServerAccessorImpl.java:401) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_121]
	at com.faforever.client.remote.FafServerAccessorImpl.parseServerObject(FafServerAccessorImpl.java:401) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.onServerMessage(FafServerAccessorImpl.java:378) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:44) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:229) [downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:205) [downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_121]
	at javafx.concurrent.Service.lambda$null$492(Service.java:725) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at javafx.concurrent.Service.lambda$executeTask$493(Service.java:724) [jfxrt.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]
```

**Comment by micheljung** [comment]
Won't fix since connectivity check won't be a thing in future anymore.
