### ISSUE TITLE
Don't crash if password can not be read

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#539]
After pull client crashed.

**Comment by axel1200** [comment]
From client.prefs:
``
"login": {
    "username": "axel12",
    "password": "xxxxxxxxxx",
    "autoLogin
": true
  }
``
the value of xxxxxx is my real password

This also causes the following error during the log in state:

``java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 21
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.faforever.client.preferences.LoginPrefs.deObfuscate(LoginPrefs.java:95)
	at com.faforever.client.preferences.LoginPrefs.getPassword(LoginPrefs.java:53)
	at com.faforever.client.login.LoginController.display(LoginController.java:64)
	at com.faforever.client.main.MainController.enterLoggedOutState(MainController.java:352)
	at com.faforever.client.main.MainController.display(MainController.java:332)
	at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:95)
	at com.faforever.client.FafClientApplication.start(FafClientApplication.java:81)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more
Exception running application com.faforever.client.FafClientApplication``

**Comment by axel1200** [comment]
Ok i am not sure if i think about it with version set the password without encryption

**Comment by axel1200** [comment]
Maybe we should catch failed encryption and let the user login again, because an error in decyption currently avoids the opening of the application

**Comment by axel1200** [comment]
Ok found the reason: https://github.com/FAForever/downlords-faf-client/commit/ad4633609a2a8a2bf6f8f7f9ea6173b9a20b7034

**Comment by axel1200** [comment]
We should then catch the Exception and simply delete the password if the decryption fails instead of letting the application crash

**Comment by micheljung** [comment]
First, there is no **encryption** anywhere.
Current `master` stores the sha256'd password
Current `develop` stores it in plain text
Current release candidate obfuscates it

**Comment by axel1200** [comment]
Good to know
