### ISSUE TITLE
Error when trying to watch coop live replay

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#560]
I've tried to watch Deering's live replay of a coop game. It showed it's downloading 2 files, once that was done this error poped out.

I switched to FAF client and the live replay worked there. (It asked me if I want to download the map, since I didnt have it, so that might be a clue)
```
java.util.concurrent.CompletionException: com.faforever.commons.mod.ModLoadException: org.luaj.vm2.LuaError: 29041610:20: '}' expected (to close '{' at line 17)
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1356)
	at javafx.concurrent.Task.setState(Task.java:707)
	at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1453)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.faforever.commons.mod.ModLoadException: org.luaj.vm2.LuaError: 29041610:20: '}' expected (to close '{' at line 17)
	at com.faforever.commons.mod.ModReader.readModInfo(ModReader.java:101)
	at com.faforever.client.mod.ModServiceImpl.extractModInfo(ModServiceImpl.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy72.extractModInfo(Unknown Source)
	at com.faforever.client.patch.GitFeaturedModUpdateTaskImpl.call(GitFeaturedModUpdateTaskImpl.java:61)
	at com.faforever.client.patch.GitFeaturedModUpdateTaskImpl.call(GitFeaturedModUpdateTaskImpl.java:23)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: org.luaj.vm2.LuaError: 29041610:20: '}' expected (to close '{' at line 17)
	at org.luaj.vm2.compiler.LexState.lexerror(Unknown Source)
	at org.luaj.vm2.compiler.LexState.syntaxerror(Unknown Source)
	at org.luaj.vm2.compiler.LexState.check_match(Unknown Source)
	at org.luaj.vm2.compiler.LexState.constructor(Unknown Source)
	at org.luaj.vm2.compiler.LexState.simpleexp(Unknown Source)
	at org.luaj.vm2.compiler.LexState.subexpr(Unknown Source)
	at org.luaj.vm2.compiler.LexState.expr(Unknown Source)
	at org.luaj.vm2.compiler.LexState.explist(Unknown Source)
	at org.luaj.vm2.compiler.LexState.assignment(Unknown Source)
	at org.luaj.vm2.compiler.LexState.exprstat(Unknown Source)
	at org.luaj.vm2.compiler.LexState.statement(Unknown Source)
	at org.luaj.vm2.compiler.LexState.statlist(Unknown Source)
	at org.luaj.vm2.compiler.LexState.mainfunc(Unknown Source)
	at org.luaj.vm2.compiler.LuaC$CompileState.luaY_parser(Unknown Source)
	at org.luaj.vm2.compiler.LuaC$CompileState.access$000(Unknown Source)
	at org.luaj.vm2.compiler.LuaC.compile(Unknown Source)
	at org.luaj.vm2.Globals.compilePrototype(Unknown Source)
	at org.luaj.vm2.Globals.loadPrototype(Unknown Source)
	at org.luaj.vm2.Globals.load(Unknown Source)
	at com.faforever.commons.lua.LuaLoader.load(LuaLoader.java:33)
	at com.faforever.commons.mod.ModReader.readModInfo(ModReader.java:72)
	... 15 more
```

**Comment by speed2CZ** [comment]
This doesn't seems to be a problem anymore
