### ISSUE TITLE
Cant download mods using the alpha launcher

### ISSUE THREAD

**Issue by Railgun69** [FAForever/downlords-faf-client#566]
every time i try to download a mod using the alpha launcher it gives me this error
the mod in question is called smart tactical missile launcher, the error is logged into the mod's description after clicking on the download button and the download is stopped

```
java.util.concurrent.CompletionException: java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at 
```

**Comment by 1-alex98** [comment]
should be fixed with mod vault enhancments
