### ISSUE TITLE
Errors in coop tab

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#572]
Version 0.7.1 from slack. When I click on Play tab or every time I change a mission the below error pops out.
So it loads the list of the missions now. But then even if I close the error and try to host a mission, it shows "updating game files" at the bottom but never launches the game.
I also tried to join a hosted game with no success. Double clicking on the one in the list didnt do anything at all.
```
java.util.concurrent.CompletionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.time.Duration from String "06:46:17": Text cannot be parsed to a Duration
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.faforever.client.api.dto.CoopResult["duration"])
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport$CompletableFutureDelegate$1.get(AsyncExecutionAspectSupport.java:324)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.time.Duration from String "06:46:17": Text cannot be parsed to a Duration
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.faforever.client.api.dto.CoopResult["duration"])
	at com.github.jasminb.jsonapi.ResourceConverter.readDocumentCollection(ResourceConverter.java:270)
	at com.faforever.client.api.JsonApiMessageConverter.readInternal(JsonApiMessageConverter.java:43)
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:193)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:104)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:655)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:287)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:525)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:512)
	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:502)
	at com.faforever.client.api.FafApiAccessorImpl.getCoopLeaderboard(FafApiAccessorImpl.java:414)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy63.getCoopLeaderboard(Unknown Source)
	at com.faforever.client.remote.FafServiceImpl.getCoopLeaderboard(FafServiceImpl.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport$CompletableFutureDelegate$1.get(AsyncExecutionAspectSupport.java:321)
	... 4 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.time.Duration from String "06:46:17": Text cannot be parsed to a Duration
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.faforever.client.api.dto.CoopResult["duration"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1410)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._rethrowDateTimeException(JSR310DeserializerBase.java:79)
	at com.fasterxml.jackson.datatype.jsr310.deser.DurationDeserializer.deserialize(DurationDeserializer.java:72)
	at com.fasterxml.jackson.datatype.jsr310.deser.DurationDeserializer.deserialize(DurationDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:357)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3770)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2099)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2596)
	at com.github.jasminb.jsonapi.ResourceConverter.readObject(ResourceConverter.java:294)
	at com.github.jasminb.jsonapi.ResourceConverter.readDocumentCollection(ResourceConverter.java:249)
	... 40 more
Caused by: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
	at java.time.Duration.parse(Unknown Source)
	at com.fasterxml.jackson.datatype.jsr310.deser.DurationDeserializer.deserialize(DurationDeserializer.java:70)
	... 50 more
```

**Comment by speed2CZ** [comment]
This is fixed already
