### ISSUE TITLE
Faulty information in game info

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#573]
![image](https://user-images.githubusercontent.com/19996713/28754068-923f0686-753e-11e7-9b69-b02c29378097.png)
I sort my game table by players in game, if a have a selected the players in that game are shown correctly but if the game list updated. Players information from other games are shown even if title and picture stay the same. Notice how in the picture it says 4/8 and 9 players are listed!!!

**Comment by Geosearchef** [comment]
Afaik the information shown comes from a game that has bren selected before and this game stays the same for all reoccurrinces of the bug until restart. 

_Sent from my HONOR FRD-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Geosearchef** [comment]
Afaik the information shown comes from a game that has bren selected before and this game stays the same for all reoccurrinces of the bug until restart.

_Sent from my HONOR FRD-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by axel1200** [comment]
Error seems related:
`Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -3
	at javafx.collections.transformation.SortedList.findPosition(SortedList.java:318)
	at javafx.collections.transformation.SortedList.update(SortedList.java:380)
	at javafx.collections.transformation.SortedList.sourceChanged(SortedList.java:103)
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:485)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.transformation.FilteredList.sourceChanged(FilteredList.java:147)
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:485)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at com.sun.javafx.collections.ObservableListWrapper.access$200(ObservableListWrapper.java:45)
	at com.sun.javafx.collections.ObservableListWrapper$1$1.invalidated(ObservableListWrapper.java:75)
	at com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(MapListenerHelper.java:320)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at com.sun.javafx.collections.ObservableMapWrapper.putAll(ObservableMapWrapper.java:192)
	at javafx.beans.binding.MapExpression.putAll(MapExpression.java:277)
	at com.faforever.client.game.Game.updateFromGameInfo(Game.java:111)
	at com.faforever.client.game.GameServiceImpl.lambda$onGameInfo$29(GameServiceImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by axel1200** [comment]
Ok Exception is not linked to the problem fixed the problem
