### ISSUE TITLE
Bireus Error

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#616]
```
java.io.FileNotFoundException: http://content.faforever.com/bireus/faf//info.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872) ~[na:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_111]
	at java.net.URL.openStream(URL.java:1045) ~[na:1.8.0_111]
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1547) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:783) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797) ~[jackson-databind-2.8.6.jar:2.8.6]
	at com.faforever.client.patch.BireusFeaturedModUpdater.canUpdate(BireusFeaturedModUpdater.java:57) ~[classes/:na]
	at com.faforever.client.patch.GameUpdaterImpl.updateFeaturedMod(GameUpdaterImpl.java:160) [classes/:na]
	at com.faforever.client.patch.GameUpdaterImpl.update(GameUpdaterImpl.java:78) [classes/:na]
	at com.faforever.client.game.GameServiceImpl.updateGameIfNecessary(GameServiceImpl.java:346) [classes/:na]
	at com.faforever.client.game.GameServiceImpl.lambda$runWithReplay$8(GameServiceImpl.java:217) [classes/:na]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[na:1.8.0_111]
	at com.faforever.client.game.GameServiceImpl.runWithReplay(GameServiceImpl.java:217) [classes/:na]
	at com.faforever.client.replay.ReplayServiceImpl.runFafReplayFile(ReplayServiceImpl.java:374) ~[classes/:na]
	at com.faforever.client.replay.ReplayServiceImpl.runReplayFile(ReplayServiceImpl.java:335) ~[classes/:na]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_111]
	at com.faforever.client.task.CompletableTask.lambda$new$2(CompletableTask.java:18) ~[classes/:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219) ~[jfxrt.jar:na]
	at javafx.concurrent.Task.fireEvent(Task.java:1356) ~[jfxrt.jar:na]
	at javafx.concurrent.Task.setState(Task.java:723) ~[jfxrt.jar:na]
	at javafx.concurrent.Task$TaskCallable.lambda$call$500(Task.java:1434) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_111]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
```

**Comment by Brutus5000** [comment]
Is that already in develop? Apart from the double-slash: the files aren't available on the server yet. I am still adding it to api deployment.
https://github.com/FAForever/faf-java-api/issues/148

**Comment by axel1200** [comment]
Yeah it is in develop

**Comment by Brutus5000** [comment]
You can temporarly remove it by commenting out line 38 in FeaturedModUpdaterConfig

@micheljung The updater is in use because it gets a BireusUrl from the api. But we can't just deactivate all mods it in the api, because we have set the api that it creates the url for all repositories in a defined scheme instead of reading from the database. Either client or api needs to change. Your choice.

**Comment by micheljung** [comment]
Um. darn. We should disable bireus in the client.

**Comment by micheljung** [comment]
Actually, we don't have to disable bireus in the client nor fix anything; It's already built so that **if possible**, it uses bireus to update but if not, it'll just print this exception but continue with the next updating mechanism.

https://github.com/FAForever/downlords-faf-client/blob/498154e26568bbeb7e833074459c08d5f7b0a0da/src/main/java/com/faforever/client/patch/BireusFeaturedModUpdater.java#L62
