### ISSUE TITLE
Mod upload returns Bad request

### ISSUE THREAD

**Issue by MythixDino** [FAForever/downlords-faf-client#619]
This only happens when trying to upload the biggest mod (Total mayhem, version 1.33, [here](http://faforever.uveso.de/TotalMayhem(AllGameVersions)-v1.33.rar))

```
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:168)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
	at com.faforever.client.api.FafApiAccessorImpl.post(FafApiAccessorImpl.java:462)
	at com.faforever.client.api.FafApiAccessorImpl.uploadMod(FafApiAccessorImpl.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy64.uploadMod(Unknown Source)
	at com.faforever.client.remote.FafServiceImpl.uploadMod(FafServiceImpl.java:321)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy72.uploadMod(Unknown Source)
	at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:79)
	at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:29)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by axel1200** [comment]
I get an  `Caused by: java.net.SocketException: Connection reset by peer: socket write error`

**Comment by micheljung** [comment]
The server limits the max file size, currently it says:
```
    # Biggest so far is Total Mayhem with 320 MiB
    client_max_body_size 350m;
```

What's the current size?

**Comment by MythixDino** [comment]
719 Mb when not compressed, however when you upload it, it compresses to 319 Mb

**Comment by Uveso** [comment]
I am getting the same message if i try to upload Total Mayhem.
(At least the upload is now working until end :D)

Client version 0.7.7
```JAVA
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:168)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
	at com.faforever.client.api.FafApiAccessorImpl.post(FafApiAccessorImpl.java:470)
	at com.faforever.client.api.FafApiAccessorImpl.uploadMod(FafApiAccessorImpl.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy64.uploadMod(Unknown Source)
	at com.faforever.client.remote.FafServiceImpl.uploadMod(FafServiceImpl.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy72.uploadMod(Unknown Source)
	at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:79)
	at com.faforever.client.mod.ModUploadTask.call(ModUploadTask.java:29)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by micheljung** [comment]
Uveso has successfully uploaded TotalMayhem so assume this very error to be fixed.
