### ISSUE TITLE
Bireus Mod Update

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#642]
Mod are not downloaded in the current #524 Branch

``` 
java.io.FileNotFoundException: http://content.faforever.com/bireus/faf//info.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) ~[na:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_151]
	at java.net.URL.openStream(URL.java:1045) ~[na:1.8.0_151]
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1547) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:783) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797) ~[jackson-databind-2.8.6.jar:2.8.6]
	at com.faforever.client.patch.BireusFeaturedModUpdater.canUpdate(BireusFeaturedModUpdater.java:57) ~[classes/:na]
	at com.faforever.client.patch.GameUpdaterImpl.updateFeaturedMod(GameUpdaterImpl.java:160) [classes/:na]
	at com.faforever.client.patch.GameUpdaterImpl.update(GameUpdaterImpl.java:78) [classes/:na]
	at com.faforever.client.game.GameServiceImpl.updateGameIfNecessary(GameServiceImpl.java:366) [classes/:na]
	at com.faforever.client.game.GameServiceImpl.lambda$joinGame$6(GameServiceImpl.java:200) [classes/:na]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

**Comment by micheljung** [comment]
Discussed
