### ISSUE TITLE
Chat window is empty

### ISSUE THREAD

**Issue by pavelterex** [FAForever/downlords-faf-client#651]
Chat window doesn't display anything upon being opened (OS: Windows Server 2012R2 x64)
![image](https://user-images.githubusercontent.com/22493159/33238238-90c40126-d29a-11e7-86f0-1e3de0ba25d8.png)
Log do not contain any related errors (one about replay folder seems not related to chat issue)
[downlords-faf-client.zip](https://github.com/FAForever/downlords-faf-client/files/1503743/downlords-faf-client.zip)
Chat in stable FAF client works as expected.

**Comment by axel1200** [comment]
This is the line that is of interest:
2017-11-24 22:16:43.480 ERROR 3104 --- [pool-2-thread-3] org.pircbotx.PircBotX                    : --- PircBotX interrupted during read, aborting reconnect loop and shutting down ---

**Comment by axel1200** [comment]
Does it work if you restart? And why are you using Windows Server 😄

**Comment by pavelterex** [comment]
I've tried several restarts (as an administrator and not) without any success.

I have my own reasons to use Server OS and this is not the subject to discuss within this thread I think ;)

**Comment by Brutus5000** [comment]
The chat uses a WebView component. Is it possible, that you have some specific restrictions for loading webpages? These are usually restricted in Windows server editions.

**Comment by pavelterex** [comment]
**Brutus5000**,  very interesting assumption. I'll check that.

**Comment by ivivaitylin** [comment]
![faf](https://user-images.githubusercontent.com/3431464/33372413-e204402a-d4f5-11e7-9ba4-7a59a7103aa7.jpg)
Same problem here. Windows 10 x64. Issue persists if I right click > run as admin. I do have an error.log in the faf install directory:

`Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.faforever.client.chat.UserInfoWindowController$1.toString(UserInfoWindowController.java:405)
	at com.faforever.client.chat.UserInfoWindowController$1.toString(UserInfoWindowController.java:399)
	at javafx.scene.chart.NumberAxis.measureTickMarkSize(NumberAxis.java:334)
	at javafx.scene.chart.NumberAxis.autoRange(NumberAxis.java:432)
	at javafx.scene.chart.ValueAxis.autoRange(ValueAxis.java:283)
	at javafx.scene.chart.Axis.computePrefHeight(Axis.java:577)
	at javafx.scene.Parent.prefHeight(Parent.java:935)
	at javafx.scene.layout.Region.prefHeight(Region.java:1435)
	at javafx.scene.chart.XYChart.layoutChartChildren(XYChart.java:687)
	at javafx.scene.chart.Chart$1.layoutChildren(Chart.java:94)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
`

New player, so not sure if this is just an issue with the current version or what.

**Comment by axel1200** [comment]
@ivivaitylin its because you are a new player

**Comment by pavelterex** [comment]
Some interesting news to share....
At first, I've checked some server security settings which could possibly cause the issue with chat - nothing suspicious was found.
At second, I've installed "FAF client - alpha" againg having previously installed stable one which I was actually using.... and chat in alpha started to work!
My first assumption was that stable client installation could get along some neccessary missing component (like .dll) for alpha chat to work. So I got rid of both clients and theirs leftovers in ProgramData and AppData, and installed alpha-client alone - chat works fine again.

So the good news is the chat finally start working, but the bad news is that I haven't found why it failed to work at first installation.

**Comment by axel1200** [comment]
Ok its not because you are new player @ivivaitylin  is caused by you being a new player, but is unrealated to the chat not loading

**Comment by axel1200** [comment]
https://github.com/pircbotx/pircbotx/blob/406a0f98a94693a2c8037d82f450e1400bfe767d/src/main/java/org/pircbotx/PircBotX.java#L377

**Comment by axel1200** [comment]
Finally Found the problem. onIdentified() in the pircoboxChatservice.class is not called even though the user registers successfully.

**Comment by axel1200** [comment]
If I call it manually the chat loads without errors
