### ISSUE TITLE
Exception when clicking "join" game twice or more often

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#669]
Exception is shown if you join a game mutiple times. Exception does not happen if the fa instance is closed and the game is joined afterwards. We should think about how to handle join being clicked mutiple times....
```
java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\bin\BugSplat.dll
	at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) ~[na:1.8.0_102]
	at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) ~[na:1.8.0_102]
	at java.util.concurrent.CompletableFuture.uniRelay(Unknown Source) ~[na:1.8.0_102]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source) ~[na:1.8.0_102]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:1.8.0_102]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[na:1.8.0_102]
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17) ~[downlords-faf-client-0.7.7.2-alpha.jar:0.7.7.2-alpha]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219) ~[jfxrt.jar:na]
	at javafx.concurrent.Task.fireEvent(Task.java:1356) ~[jfxrt.jar:na]
	at javafx.concurrent.Task.setState(Task.java:707) ~[jfxrt.jar:na]
	at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1453) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_102]
Caused by: com.github.nocatch.NoCatchException: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\bin\BugSplat.dll
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_102]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_102]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_102]
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82) ~[nocatch-1.1.jar:na]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.lambda$copyGameFilesToFafBinDirectory$4(GameBinariesUpdateTaskImpl.java:130) ~[downlords-faf-client-0.7.7.2-alpha.jar:0.7.7.2-alpha]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:1.8.0_102]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[na:1.8.0_102]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_102]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_102]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.copyGameFilesToFafBinDirectory(GameBinariesUpdateTaskImpl.java:125) ~[downlords-faf-client-0.7.7.2-alpha.jar:0.7.7.2-alpha]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.call(GameBinariesUpdateTaskImpl.java:86) ~[downlords-faf-client-0.7.7.2-alpha.jar:0.7.7.2-alpha]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.call(GameBinariesUpdateTaskImpl.java:39) ~[downlords-faf-client-0.7.7.2-alpha.jar:0.7.7.2-alpha]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_102]
	... 1 common frames omitted
Caused by: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\bin\BugSplat.dll
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source) ~[na:1.8.0_102]
	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source) ~[na:1.8.0_102]
	at java.nio.file.Files.copy(Unknown Source) ~[na:1.8.0_102]
	at com.faforever.client.patch.GameBinariesUpdateTaskImpl.lambda$null$2(GameBinariesUpdateTaskImpl.java:130) ~[downlords-faf-client-0.7.7.2-alpha.jar:0.7.7.2-alpha]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100) ~[nocatch-1.1.jar:na]
	... 20 common frames omitted```

**Comment by axel1200** [comment]
How should we handle it?

**Comment by Sheikah45** [comment]
Client doesn't let you join while joining another game currently
