### ISSUE TITLE
Forged Alliances closes Socket if direct x is not installed

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#681]
Forged Alliances closes Socket if direct x is not installed...
Following exception is thrown:
```
Exception in thread "pool-2-thread-5" com.github.nocatch.NoCatchException: java.net.SocketException: socket closed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.relay.LocalRelayServerImpl.innerStart(LocalRelayServerImpl.java:261)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: socket closed
	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.faforever.client.relay.LocalRelayServerImpl.lambda$innerStart$2(LocalRelayServerImpl.java:273)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	... 5 more
```
Instead the Exception should be shown to the user and he should be given a hint to why this happend("common cause for that is having direct x 9.0c not installed").

**Comment by axel1200** [comment]
It is not fa that closes the socket... any way it will be different with the ice code...
