### ISSUE TITLE
Error watching replay

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#689]
When watching a replay my game fails updating!
```
2018-01-12 20:03:08.374  INFO 194692 --- [pool-2-thread-6] c.f.c.p.GitFeaturedModUpdateTaskImpl     : Updating game files from https://github.com/FAForever/fa.git@refs/tags/3695
2018-01-12 20:04:13.039  WARN 194692 --- [lication Thread] c.f.client.patch.GameUpdaterImpl         : Game could not be joined

java.util.concurrent.CompletionException: org.eclipse.jgit.api.errors.RefNotFoundException: Ref refs/tags/3695 can not be resolved
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[na:1.8.0_151]
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17) ~[classes/:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219) ~[jfxrt.jar:na]
	at javafx.concurrent.Task.fireEvent(Task.java:1356) ~[jfxrt.jar:na]
	at javafx.concurrent.Task.setState(Task.java:707) ~[jfxrt.jar:na]
	at javafx.concurrent.Task$TaskCallable.lambda$call$500(Task.java:1453) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_151]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Caused by: org.eclipse.jgit.api.errors.RefNotFoundException: Ref refs/tags/3695 can not be resolved
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:251) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at com.faforever.client.patch.JGitWrapper.checkoutRef(JGitWrapper.java:66) ~[classes/:na]
	at com.faforever.client.patch.GitFeaturedModUpdateTaskImpl.checkout(GitFeaturedModUpdateTaskImpl.java:86) ~[classes/:na]
	at com.faforever.client.patch.GitFeaturedModUpdateTaskImpl.call(GitFeaturedModUpdateTaskImpl.java:52) ~[classes/:na]
	at com.faforever.client.patch.GitFeaturedModUpdateTaskImpl.call(GitFeaturedModUpdateTaskImpl.java:23) ~[classes/:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	... 1 common frames omitted```

**Comment by micheljung** [comment]
This has been fixed by removing the git updater in #817
