### ISSUE TITLE
Chat breaks

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#694]
Chat does not connect with that message....
````
org.pircbotx.exception.IrcException: CannotLogin: Received error: :irc.faforever.com 451 PING :You have not registered
	at org.pircbotx.InputParser.processConnect(InputParser.java:372) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.InputParser.handleLine(InputParser.java:320) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.processNextLine(PircBotX.java:342) [pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:295) [pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.connect(PircBotX.java:284) [pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.startBot(PircBotX.java:177) [pircbotx-2.1.jar:na]
	at com.faforever.client.chat.PircBotXChatService$1.call(PircBotXChatService.java:431) [classes/:na]
	at com.faforever.client.chat.PircBotXChatService$1.call(PircBotXChatService.java:423) [classes/:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
```

**Comment by axel1200** [comment]
another client was running in background with the ui already closed!!!
