### ISSUE TITLE
Exception in log

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#722]
I get this Exception in the log. @micheljung Idea what that could mean
```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: toIndex = 25
	at java.util.SubList.<init>(AbstractList.java:622)
	at java.util.AbstractList.subList(AbstractList.java:484)
	at javafx.collections.ListChangeListener$Change.getAddedSubList(ListChangeListener.java:242)
	at com.faforever.client.game.GamesTilesContainerController.lambda$null$1(GamesTilesContainerController.java:44)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by micheljung** [comment]
It happens from time to time and is probably because of a race condition, but so far I haven't figured out why

**Comment by 1-alex98** [comment]
What do you mean by race conditions?

**Comment by micheljung** [comment]
Two threads reading/writing the same field concurrently, causing inconsistencies https://en.wikipedia.org/wiki/Race_condition#Software

**Comment by micheljung** [comment]
This might have been fixed
