### ISSUE TITLE
Avoid local replay port being blocked by using random free port

### ISSUE THREAD

**Issue by kyleprice18** [FAForever/downlords-faf-client#792]
java.util.concurrent.CompletionException: java.net.BindException: Address already in use: JVM_Bind
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:114)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:100)
	... 1 more

any ideas to fix, was using the old faf client untill i clean installed the new one.

**Comment by kyleprice18** [comment]
but i can watch replays..

**Comment by 1-alex98** [comment]
Are you sure you dont have another client running along side?

**Comment by 1-alex98** [comment]
Download http://technet.microsoft.com/en-us/sysinternals/bb897437 and have a look which other process is listed on port 15001 locally

**Comment by 1-alex98** [comment]
Some other process seems to have blocked port 15001

**Comment by micheljung** [comment]
Actually, there is no reason that we explicitly open port 15001. We should just use any free port. See also `org.springframework.util.SocketUtils#findAvailableTcpPort()`.
