### ISSUE TITLE
Reconnect for IRC does not work on connection lost

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#809]
Fails with the following exception: 
```
2018-03-20 16:09:22.367 ERROR 3724 --- [pool-2-thread-2] org.pircbotx.PircBotX                    : Exception encountered when parsing line :irc.faforever.com 451 PING :You have not registered

org.pircbotx.exception.IrcException: CannotLogin: Received error: :irc.faforever.com 451 PING :You have not registered
	at org.pircbotx.InputParser.processConnect(InputParser.java:372) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.InputParser.handleLine(InputParser.java:320) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.processNextLine(PircBotX.java:342) [pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:295) [pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.connect(PircBotX.java:284) [pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.startBot(PircBotX.java:177) [pircbotx-2.1.jar:na]
	at com.faforever.client.chat.PircBotXChatService$1.call(PircBotXChatService.java:445) [classes/:na]
	at com.faforever.client.chat.PircBotXChatService$1.call(PircBotXChatService.java:437) [classes/:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
```

**Comment by 1-alex98** [comment]
Ok wait it did reconect after like 2 minutes

**Comment by micheljung** [comment]
And did you mean "IRC" in the title instead of "ICE"?

**Comment by 1-alex98** [comment]
Yeah I did
