### ISSUE TITLE
Improve how the client reacts to missing message keys in messages.properties

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#812]
If message keys are missing in the main messages.properties file, the client crashes or is partly unusable. I get the following exception if a message key of the login dialog is missing:
```
2018-03-16 23:25:27.667  INFO 2604 --- [JavaFX-Launcher] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService  'taskScheduler'
2018-03-16 23:25:28.212  INFO 2604 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 11.813 seconds (JVM running for 31.062)
Exception in Application start method
2018-03-16 23:25:29.850  INFO 2604 --- [lication Thread] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@33adb000: startup date [Fri Mar 16 23:25:18 CET 2018]; root of context hierarchy
2018-03-16 23:25:29.864  INFO 2604 --- [lication Thread] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-03-16 23:25:29.881  WARN 2604 --- [lication Thread] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'asyncConfig': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'taskExecutor': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
    at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.nocatch.NoCatchException: javafx.fxml.LoadException: Resource "login.create" not found.
/<path>/git/downlords-faf-client/bin/theme/login.fxml:74

    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53)
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
    at com.faforever.client.theme.UiServiceImpl.loadFxml(UiServiceImpl.java:334)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy73.loadFxml(Unknown Source)
    at com.faforever.client.main.MainController.enterLoggedOutState(MainController.java:346)
    at com.faforever.client.main.MainController.display(MainController.java:328)
    at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:97)
    at com.faforever.client.FafClientApplication.start(FafClientApplication.java:83)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
    ... 1 more
Caused by: javafx.fxml.LoadException: Resource "login.create" not found.
/<path>/git/downlords-faf-client/bin/theme/login.fxml:74

    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
    at javafx.fxml.FXMLLoader.access$100(FXMLLoader.java:103)
    at javafx.fxml.FXMLLoader$Element.resolvePrefixedValue(FXMLLoader.java:424)
    at javafx.fxml.FXMLLoader$Element.processValue(FXMLLoader.java:363)
    at javafx.fxml.FXMLLoader$Element.processPropertyAttribute(FXMLLoader.java:325)
    at javafx.fxml.FXMLLoader$Element.processInstancePropertyAttributes(FXMLLoader.java:235)
    at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:767)
    at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2823)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
    ... 22 more
Exception running application com.faforever.client.FafClientApplication
```
Depending on which key is missing, the UI either crashes or is partly unusable. In this case the main tab Vault does not load/throws an exception because I commented "vault.liveReplays":
```
2018-03-17 00:15:39.010  INFO 2200 --- [JavaFX-Launcher] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService  'taskScheduler'
2018-03-17 00:15:40.495  INFO 2200 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 16.106 seconds (JVM running for 131.819)
2018-03-17 00:18:32.106  INFO 2200 --- [      Thread-14] c.f.client.remote.FafServerAccessorImpl  : Trying to connect to FAF server at lobby.faforever.com:8001
2018-03-17 00:18:32.236  INFO 2200 --- [      Thread-14] c.f.client.remote.FafServerAccessorImpl  : FAF server connection established
2018-03-17 00:18:32.472  INFO 2200 --- [      Thread-14] c.f.client.remote.FafServerAccessorImpl  : FAF session initiated, session ID: 1174439727
2018-03-17 00:18:39.509  INFO 2200 --- [      Thread-14] c.f.client.remote.FafServerAccessorImpl  : FAF login succeeded
2018-03-17 00:18:39.973  INFO 2200 --- [pool-2-thread-3] c.f.client.update.CheckForUpdateTask     : Checking for client update
2018-03-17 00:18:40.008  INFO 2200 --- [pool-2-thread-4] c.f.client.chat.PircBotXChatService      : Connecting to IRC at irc.faforever.com:8167
2018-03-17 00:18:41.343  WARN 2200 --- [lication Thread] com.faforever.client.config.BaseConfig   : Exception in 'class com.faforever.client.main.MainController#onNavigateEvent' while handling event: com.faforever.client.main.NavigateEvent@3bf3512e

com.google.common.util.concurrent.UncheckedExecutionException: com.github.nocatch.NoCatchException: javafx.fxml.LoadException: Resource "vault.liveReplays" not found.
/<path>/git/downlords-faf-client/bin/theme/vault/vault.fxml:49

    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739) ~[guava-18.0.jar:na]
    at com.faforever.client.main.MainController.lambda$14(MainController.java:467) ~[bin/:na]
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100) ~[nocatch-1.1.jar:na]
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82) ~[nocatch-1.1.jar:na]
    at com.faforever.client.main.MainController.loadView(MainController.java:467) ~[bin/:na]
    at com.faforever.client.main.MainController.onNavigateEvent(MainController.java:452) ~[bin/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-18.0.jar:na]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-18.0.jar:na]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-18.0.jar:na]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-18.0.jar:na]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-18.0.jar:na]
    at com.faforever.client.main.MainController.restoreLastView(MainController.java:416) ~[bin/:na]
    at com.faforever.client.main.MainController.enterLoggedInState(MainController.java:405) ~[bin/:na]
    at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:na]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_161]
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:na]
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
    at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:na]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Caused by: com.github.nocatch.NoCatchException: javafx.fxml.LoadException: Resource "vault.liveReplays" not found.
/<path>/git/downlords-faf-client/bin/theme/vault/vault.fxml:49

    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_161]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_161]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_161]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_161]
    at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61) ~[nocatch-1.1.jar:na]
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53) ~[nocatch-1.1.jar:na]
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34) ~[nocatch-1.1.jar:na]
    at com.faforever.client.theme.UiServiceImpl.loadFxml(UiServiceImpl.java:334) ~[bin/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    at com.sun.proxy.$Proxy73.loadFxml(Unknown Source) ~[na:na]
    at com.faforever.client.main.MainController.lambda$18(MainController.java:467) ~[bin/:na]
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742) ~[guava-18.0.jar:na]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
    ... 25 common frames omitted
Caused by: javafx.fxml.LoadException: Resource "vault.liveReplays" not found.
/<path>/git/downlords-faf-client/bin/theme/vault/vault.fxml:49

    at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader.access$100(FXMLLoader.java:103) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader$Element.resolvePrefixedValue(FXMLLoader.java:424) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader$Element.processValue(FXMLLoader.java:363) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader$Element.processPropertyAttribute(FXMLLoader.java:325) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader$Element.processInstancePropertyAttributes(FXMLLoader.java:235) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:767) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2823) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:na]
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:na]
    at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49) ~[nocatch-1.1.jar:na]
    ... 40 common frames omitted

2018-03-17 00:18:42.542  INFO 2200 --- [pool-2-thread-3] c.f.client.update.CheckForUpdateTask     : Current version is snapshot, newest version is v0.7.7.2-alpha
```

**Comment by germanicianus** [comment]
So either crash on all message keys with an error dialog on startup or keep the UI usable. The first one would require the UI to initialize all of it’s components on startup to determine if a message is missing which would slow down the startup process.

The current behavior is inconsistent and requires having a look at the error log because there is no error dialog.
