### ISSUE TITLE
Fix screen detection on maximize (add fallback)

### ISSUE THREAD

**Issue by EmielWitteman** [FAForever/downlords-faf-client#860]
After installing dfc_windows_0_8_0-beta.exe I get error screen right away, a previous 0.7 version did work (not sure but probably v0.7.7.2-alpha)
After reading some other issues I tried : 

1. deleting C:\ProgramData\FAForever\cache
2. starting as admin
3. deleting C:\ProgramData\FAForever
4. reinstalling several times
5. running at one screen at 1080p@100% scaling after cleaning window Size/Location cache with ccleaner

But problem remained. Running on Windows 10 Pro, version 1709
My laptop with Windows 10 Home, also 1709, runs this client fine.

It might have to do with my screen settings, I have 1 4k@150% screen and 2 1080p@100% screens.
I noticed before the java client gets confused when having screens at different scaling, but step 5 didn't fix this either.

error.log:
`Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at com.faforever.client.fx.WindowController.getVisualBounds(WindowController.java:68)
	at com.faforever.client.fx.WindowController.maximize(WindowController.java:115)
	at com.faforever.client.fx.WindowController.maximize(WindowController.java:72)
	at com.faforever.client.main.MainController.display(MainController.java:337)
	at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:97)
	at com.faforever.client.FafClientApplication.start(FafClientApplication.java:83)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	... 1 more`

**Comment by Geosearchef** [comment]
Seems like JavaFx can't find a screen for the current center of the application to maximize on.

https://github.com/FAForever/downlords-faf-client/blob/bfb5e289ac8d5840a30338f1f22dcd3d47a1a033/src/main/java/com/faforever/client/fx/WindowController.java#L62-L69

As a quickfix, you could try having a look at the properties file of the client (.faforever in home directory on linux, currently trying the find out the windows location, I'd guess it's in Documents\My Games) and unset the maximized option, and then, don't maximize it.
The VisualBounds of the current screen are just requested when maxmizing.

**Comment by Geosearchef** [comment]
Why do we look for the center of the current window? Why not check for all intersecting with the current window borders and take the one with the greatest overlap? (easy to calculate) We should also definetly add a fallback to `Screen.getPrimary()`.

@EmielWitteman If you still need it, the config file for the client is located `%APPDATA%/Forged Alliance/client.prefs`. Probably the center of you window is located outside of all screens at the moment of maximizing. Without more debug information I can't say a lot about why this happening.
You could help us with finding the problem by running this adapted version of the client (prints more debug information) and telling us the parts of the log that contain "WindowController". 

Just replace the jar in `C:/Program Files (x86)/Downlord's FAF Client/lib/downlords-faf-client-0.8.0-beta.jar` with the one in the zip file (make a backup first). 
[adaptedVersion.zip](https://github.com/FAForever/downlords-faf-client/files/1887317/adaptedVersion.zip)

**Comment by micheljung** [comment]
Because the center *is* on the screen with the greatest overlap :)

**Comment by Geosearchef** [comment]
No, not if it is offscreen.

**Comment by micheljung** [comment]
Ok for off-screen we definitely need a fallback ;) But I wonder how that can happen.

**Comment by Geosearchef** [comment]
I hope we can see this in the logs of the adapted version. It should print current stage pos and all screen bounds.

**Comment by EmielWitteman** [comment]
Thanks for the quick response. The client.prefs file caused the problem, changing the x to positive fixes the problem:
`{
  "mainWindow": {
    "width": 1280,
    "height": 693,
    "maximized": true,
    "lastView": "VAULT",
    "lastChildViews": {},
    "x": -1279.3333740234375,
    "y": 720.0
  },
`
the adapterVersion doesn't seem to print more debug

**Comment by Geosearchef** [comment]
Oh, ok, didn't realize the old position gets stored in there aswell. So if the window is created of screen, that explains the error. Nonetheless we should add a default fallback (e.g. primary screen, or add a more complicated computation) mechanism.

Thanks for testing, the adapted version should just print about 4 - 8 lines of debug information to the warning output, which should be enabled on the default log level of the application. But I don't think there is a need to investigate this further. Thanks for your help/report, gonna fix that now.
