### ISSUE TITLE
Random IndexOutOfBoundsException when adding listener

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#864]
```
Exception in thread "pool-2-thread-7" java.lang.ArrayIndexOutOfBoundsException: 11
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$1(ChannelTabController.java:161)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-2-thread-4" java.lang.ArrayIndexOutOfBoundsException: 12
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$1(ChannelTabController.java:161)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-2-thread-9" java.lang.ArrayIndexOutOfBoundsException: 13
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$1(ChannelTabController.java:161)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread13" java.lang.ArrayIndexOutOfBoundsException: 14
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread14" java.lang.ArrayIndexOutOfBoundsException: 15
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread13" java.lang.ArrayIndexOutOfBoundsException: 16
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread14" java.lang.ArrayIndexOutOfBoundsException: 17
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread13" java.lang.ArrayIndexOutOfBoundsException: 18
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread14" java.lang.ArrayIndexOutOfBoundsException: 19
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread14" java.lang.ArrayIndexOutOfBoundsException: 20
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "listenerPool0-thread13" java.lang.ArrayIndexOutOfBoundsException: 21
	at com.sun.javafx.binding.ExpressionHelper$Generic.addListener(ExpressionHelper.java:295)
	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:69)
	at javafx.beans.property.BooleanPropertyBase.addListener(BooleanPropertyBase.java:85)
	at com.faforever.client.chat.ChannelTabController.onUserJoinedChannel(ChannelTabController.java:429)
	at com.faforever.client.chat.ChannelTabController.lambda$setChannel$0(ChannelTabController.java:150)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at javafx.collections.FXCollections$SynchronizedObservableMap.lambda$new$69(FXCollections.java:2760)
	at javafx.collections.WeakMapChangeListener.onChanged(WeakMapChangeListener.java:88)
	at com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:163)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at javafx.collections.FXCollections$SynchronizedMap.put(FXCollections.java:2571)
	at com.faforever.client.chat.Channel.addUser(Channel.java:46)
	at com.faforever.client.chat.PircBotXChatService.onUserJoinedChannel(PircBotXChatService.java:310)
	at com.faforever.client.chat.PircBotXChatService.lambda$postConstruct$4(PircBotXChatService.java:183)
	at com.faforever.client.chat.PircBotXChatService.lambda$onEvent$14(PircBotXChatService.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.faforever.client.chat.PircBotXChatService.onEvent(PircBotXChatService.java:383)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
	at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
	at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Has been reported as [JDK-8164446](https://bugs.openjdk.java.net/browse/JDK-8164446) but closed since no reproducer could be provided.

Either we have to synchronize on the property, or we only add listeners on the application thread.

**Comment by micheljung** [comment]
This reproduces the error
```
public class JDK8164446 extends Application {

  @Override
  public void start(Stage primaryStage) {
    StringProperty stringProperty = new SimpleStringProperty();

    new Thread(() -> {
      while (true) {
        stringProperty.addListener((observable, oldValue, newValue) -> noop());
      }
    }).start();

    while (true) {
      stringProperty.addListener((observable, oldValue, newValue) -> noop());
    }
  }

  private static void noop() {

  }

  public static void main(String[] args) {
    launch(args);
  }
}
```

**Comment by micheljung** [comment]
Confirmed as "works as designed" (https://bugs.openjdk.java.net/browse/JDK-8201635)
