### ISSUE TITLE
Error handling server message

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#891]
Got this from a users log:
```
23:46:04.941 [Thread-15] WARN  c.f.c.remote.AbstractServerAccessor - Error while handling server message: {"command": "social", "autojoin": ["#ONI_clan"], "friends": [7740, 17480, 17861, 17884, 18220, 23178, 23240, 30361, 49130, 64928, 66471, 77178, 85465, 89988, 92766, 93450, 100287, 108093, 111077, 115737, 115983, 116029, 125351, 129150, 135418, 137050, 137868, 139665, 144921, 149539, 152796, 156254, 159761, 160748, 161548, 166198, 172376, 173120, 173802, 175041, 175165, 175302, 176445, 177202, 177810, 177886, 178246, 180337, 180818, 181229, 181562, 182671, 183883, 184048, 186589, 197424, 198535, 205501, 211144], "foes": [], "power": 0, "channels": ["#ONI_clan"]}
com.github.nocatch.NoCatchException: java.lang.InterruptedException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_171]
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34) ~[nocatch-1.1.jar:na]
	at com.faforever.client.chat.PircBotXChatService.joinChannel(PircBotXChatService.java:524) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_171]
	at com.faforever.client.chat.PircBotXChatService.joinAutoChannels(PircBotXChatService.java:236) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.chat.PircBotXChatService.onSocialMessage(PircBotXChatService.java:335) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.lambda$parseServerObject$1(FafServerAccessorImpl.java:401) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_171]
	at com.faforever.client.remote.FafServerAccessorImpl.parseServerObject(FafServerAccessorImpl.java:401) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.onServerMessage(FafServerAccessorImpl.java:378) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:44) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:229) [downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:205) [downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
	at javafx.concurrent.Service.lambda$null$493(Service.java:725) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_171]
	at javafx.concurrent.Service.lambda$executeTask$494(Service.java:724) [jfxrt.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_171]
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source) ~[na:1.8.0_171]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source) ~[na:1.8.0_171]
	at java.util.concurrent.CountDownLatch.await(Unknown Source) ~[na:1.8.0_171]
	at com.faforever.client.chat.PircBotXChatService.lambda$joinChannel$20(PircBotXChatService.java:524) ~[downlords-faf-client-0.6.32-alpha.jar:0.6.32-alpha]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49) ~[nocatch-1.1.jar:na]
	... 20 common frames omitted
```

**Comment by micheljung** [comment]
Anything happened? Looks like the client got closed, before IRC was ready, nothing to worry about
