### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by ghost** [FAForever/downlords-faf-client#940]
```
java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:912)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'onGameFullNotifier' defined in URL [jar:file:/C:/Program%20Files%20(x86)/Downlord's%20FAF%20Client/lib/downlords-faf-client-0.8.0-beta.jar!/com/faforever/client/fa/OnGameFullNotifier.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapServiceImpl' defined in URL [jar:file:/C:/Program%20Files%20(x86)/Downlord's%20FAF%20Client/lib/downlords-faf-client-0.8.0-beta.jar!/com/faforever/client/map/MapServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'uiServiceImpl': Invocation of init method failed; nested exception is java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\cache\stylesheets\style-webview4619492292306772386.css
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at com.faforever.client.FafClientApplication.init(FafClientApplication.java:76)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	... 2 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapServiceImpl' defined in URL [jar:file:/C:/Program%20Files%20(x86)/Downlord's%20FAF%20Client/lib/downlords-faf-client-0.8.0-beta.jar!/com/faforever/client/map/MapServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'uiServiceImpl': Invocation of init method failed; nested exception is java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\cache\stylesheets\style-webview4619492292306772386.css
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 20 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'uiServiceImpl': Invocation of init method failed; nested exception is java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\cache\stylesheets\style-webview4619492292306772386.css
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 34 more
Caused by: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\cache\stylesheets\style-webview4619492292306772386.css
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at com.faforever.client.io.FileUtils$1.visitFile(FileUtils.java:22)
	at com.faforever.client.io.FileUtils$1.visitFile(FileUtils.java:19)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at com.faforever.client.io.FileUtils.deleteRecursively(FileUtils.java:19)
	at com.faforever.client.theme.UiServiceImpl.postConstruct(UiServiceImpl.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	... 47 more
```

**Comment by Geosearchef** [comment]
The client can't read the file at `Caused by: java.nio.file.AccessDeniedException: C:\ProgramData\FAForever\cache\stylesheets\style-webview4619492292306772386.css`.

Try giving it permission to read that file. Maybe you did start the client/installer using admin rights the first time?

**Comment by 1-alex98** [comment]
This is a permission problem you installed the client being administrator and then started it with normal user, this is an known problem. Hard to fix, the original client has the same issue

**Comment by ghost** [comment]
Ok, thank you, hopefully this sovles my problem.

Edit: Ok, i just tried uninstalling and installing with administrator permissions and that fixed my problem. Thanks for assisting, hopefully this persisting issue will be fixed in the future for both launchers.

**Comment by 1-alex98** [comment]
Well you should install it without admin rights and start it without admin rights

**Comment by 1-alex98** [comment]
But once you started it with admin rights you will always need admin rights 😢

**Comment by germanicianus** [comment]
Installing **without** admin rights is **not** possible (at least currently/with 0.8.0-beta):
![image](https://user-images.githubusercontent.com/37223176/41830705-d3a1761a-7842-11e8-951b-6c9080ab5d2a.png)
On canceling this request for admin rights:
![image](https://user-images.githubusercontent.com/37223176/41830723-f0739192-7842-11e8-83ba-90327a508587.png)
I mentioned it in my Steam guide ["Howto: Getting started with Forged Alliance Forever (FAF)"](https://steamcommunity.com/sharedfiles/filedetails/?id=1421011712) (Step 3).

Nevertheless I had **no** problems launching it as normal user, even after having it started once with admin rights. I installed it into the default location.

**Comment by 1-alex98** [comment]
Well maybe it was running the programm with admin rights i would need to try

**Comment by Geosearchef** [comment]
Maybe it's due running it with admin rights the first time you start it. So the configuration files are written with the wrong permissions.
